const { withErrors, ok, fail, requireMethod, getBody } = require('../../lib/http');
const gameManager = require('../../lib/gameManager');
const roomStore = require('../../lib/roomStore');
const { broadcast } = require('../../lib/pusherServer');
const { broadcastGameOver } = require('../../lib/roomEvents');
const playerStats = require('../../lib/playerStats');
const cardProgression = require('../../lib/cardProgression');
const { sql } = require('../../lib/db');
module.exports=withErrors(async(req,res)=>{if(!requireMethod(req,res,'POST'))return;const{playerId,code,submissionIndex}=getBody(req);if(!playerId||!code)return fail(res,400,'playerId e code são obrigatórios.');const room=await roomStore.loadRoom(code);if(!room)return fail(res,404,'Sala não encontrada.');const{winnerId,winnerNickname,winnerCard,gameOver}=gameManager.pickWinner(room,playerId,submissionIndex);const winner=room.players.get(winnerId);if(winner?.userId){await playerStats.recordBlackWin(winner.userId,room.currentRound.blackCard);if(winnerCard)await sql`INSERT INTO user_cards(user_id,type,text,owned,times_won) VALUES(${winner.userId},'whiteCards',${winnerCard},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_won=user_cards.times_won+1,updated_at=now()`;}await playerStats.recordRoundReplay(room);const progression=process.env.CARD_PROGRESSION_V2_ENABLED==='false'?{winnerOriginal:false}:await cardProgression.recordResolvedRound(room);await roomStore.saveRoom(room);await broadcast(room.code,'round_result',{winnerNickname,winnerCard,blackCard:room.currentRound.blackCard,roundNumber:room.currentRound.number,scores:gameManager.getScoresForRoom(room),gameOver,originalCelebration:progression.winnerOriginal?{kind:'original_win',message:'🏆 O ORIGINAL FUNCIONA',detail:`${winnerNickname} venceu usando uma carta criada por si.`}:null});if(gameOver)await broadcastGameOver(room,'O jogo acabou!');ok(res);});
