'use strict';
const{sql}=require('./db');const advanced=require('./advancedRoundEngine');
function progressionRoom(room){
 if(!advanced.isV2(room.currentRound))return room;
 const out={...room,players:new Map(room.players),currentRound:{...room.currentRound,submissions:new Map()}},r=room.currentRound;
 for(const s of advanced.entries(r,{activeOnly:false})){const key=`sub:${s.id}`,source=room.players.get(String(s.userId)),alias=s.temporary?{...(source||{}),userId:null}:source;if(alias)out.players.set(key,alias);out.currentRound.submissions.set(key,{card:s.card,submissionId:s.id,temporary:!!s.temporary});}
 const answer=advanced.findAnswer(room,r.winnerSubmissionId||'');
 if(answer){const source=room.players.get(String(answer.userId)),key=`winner:${answer.answerId}`;out.players.set(key,answer.temporary?{...(source||{}),userId:null}:source);out.currentRound.winnerId=key;out.currentRound.winnerCards=[...(answer.cards||[])];out.currentRound.winnerSubmissionIds=[...(answer.submissionIds||[])];out.currentRound.winnerCard=(answer.cards||[]).join(' / ');}
 return out;
}
async function recordRoundReplay(room){const r=room.currentRound;if(!advanced.isV2(r))return null;const master=room.players.get(String(r.hostId)),subs=advanced.entries(r,{activeOnly:false}).map(s=>{const p=room.players.get(String(s.userId));return{submissionId:s.id,userId:p?.userId||Number(s.userId)||null,nickname:p?.nickname||'Jogador',card:s.card,status:s.status,temporary:!!s.temporary};}),scores=Array.from(room.players.values()).filter(p=>p.active!==false).map(p=>({userId:p.userId,nickname:p.nickname,score:p.score})),winner=room.players.get(String(r.winnerId)),events=await sql`SELECT event_type,actor_user_id,target_user_id,submission_id,payload,created_at FROM round_engine_events WHERE room_code=${room.code} AND round_number=${r.number} ORDER BY id`;await sql`INSERT INTO match_rounds(room_code,round_number,black_card,master_user_id,master_nickname,submissions,winner_user_id,winner_nickname,winner_card,scores,engine_version,event_log,rotation_direction,winner_submission_id,scoring_user_id) VALUES(${room.code},${r.number},${r.blackCard},${master?.userId||null},${master?.nickname||null},${JSON.stringify(subs)}::jsonb,${winner?.userId||null},${winner?.nickname||null},${r.winnerCard||null},${JSON.stringify(scores)}::jsonb,${advanced.VERSION},${JSON.stringify(events)}::jsonb,${advanced.roomState(r).rotationDirection},${r.winnerSubmissionId||null},${room.players.get(String(r.winnerScoringUserId))?.userId||null}) ON CONFLICT(room_code,round_number) DO UPDATE SET black_card=EXCLUDED.black_card,master_user_id=EXCLUDED.master_user_id,master_nickname=EXCLUDED.master_nickname,submissions=EXCLUDED.submissions,winner_user_id=EXCLUDED.winner_user_id,winner_nickname=EXCLUDED.winner_nickname,winner_card=EXCLUDED.winner_card,scores=EXCLUDED.scores,engine_version=EXCLUDED.engine_version,event_log=EXCLUDED.event_log,rotation_direction=EXCLUDED.rotation_direction,winner_submission_id=EXCLUDED.winner_submission_id,scoring_user_id=EXCLUDED.scoring_user_id`;return{submissions:subs,events};}
function redactEvent(e){const p=e?.payload||{};return{eventType:e.event_type||e.eventType,buffKey:p.buffKey||null,submissionId:e.submission_id||e.submissionId||null,createdAt:e.created_at||e.createdAt||null};}
async function publicReplay(roomCode){const rows=await sql`SELECT round_number,black_card,master_nickname,submissions,winner_nickname,winner_card,scores,engine_version,event_log,rotation_direction,winner_submission_id FROM match_rounds WHERE room_code=${String(roomCode)} ORDER BY round_number`;return rows.map(r=>({roundNumber:r.round_number,blackCard:r.black_card,masterNickname:r.master_nickname,submissions:(r.submissions||[]).map(s=>({submissionId:s.submissionId||null,card:s.card,status:s.status||'active',temporary:!!s.temporary})),winnerNickname:r.winner_nickname,winnerCard:r.winner_card,scores:r.scores||[],engineVersion:r.engine_version,rotationDirection:Number(r.rotation_direction||1),winnerSubmissionId:r.winner_submission_id||null,eventLog:(r.event_log||[]).map(redactEvent)}));}
module.exports={recordRoundReplay,progressionRoom,publicReplay};
