'use strict';
const crypto=require('crypto');
const{GAME_STATES}=require('./constants');
const{drawCard,shuffleArray}=require('./gameLogic');
const{whiteCardsRequiredForBlack}=require('./cardIdentity');
const VERSION='advanced-round-v1';
const enabled=()=>process.env.ADVANCED_ROUND_ENGINE!=='false';
const isV2=r=>r?.engineVersion===VERSION;
const clone=x=>JSON.parse(JSON.stringify(x));
function defaultRoomState(){return{version:VERSION,rotationDirection:1,repeatCurrentMasterOnce:false,reactionsDisabled:false,blackoutRound:null,temporaryPossessions:{},actionSeq:0};}
function defaultRoundState(){return{requiredSubmissions:{},blockedCards:{},needsSubmission:{},protectedUsers:{},revealAuthorsToMaster:false,revealOrder:[],answerRevealOrder:[],globalLocks:{},chaosActivators:[],latestCancellable:null,quePoder:null,pendingTrim:{}};}
function roomState(round){if(!round.roomState||round.roomState.version!==VERSION)round.roomState={...defaultRoomState(),...(round.roomState||{}),version:VERSION};round.roomState.temporaryPossessions||={};return round.roomState;}
function roundState(round){if(!round.roundState)round.roundState=defaultRoundState();const s=round.roundState;s.requiredSubmissions||={};s.blockedCards||={};s.needsSubmission||={};s.protectedUsers||={};s.revealOrder||=[];s.answerRevealOrder||=[];s.globalLocks||={};s.chaosActivators||=[];s.pendingTrim||={};return s;}
function cardsPerAnswer(round){return whiteCardsRequiredForBlack(round?.blackCard||'');}
function answerCount(round,userId){return Math.max(1,Number(roundState(round).requiredSubmissions[String(userId)]||1));}
function makeRound(room,{number,blackCard,hostIndex,hostId,previousRoomState=null}){return{engineVersion:VERSION,number,blackCard,hostIndex,hostId:String(hostId),submissions:new Map(),winnerId:null,winnerScoringUserId:null,winnerSubmissionId:null,winnerSubmissionIds:[],winnerCard:null,winnerCards:[],roomState:{...defaultRoomState(),...(previousRoomState?clone(previousRoomState):{})},roundState:defaultRoundState(),buffState:null};}
function startFirstRound(room,blackCard,hostIndex){const idx=hostIndex??room.playerOrder.findIndex(id=>room.players.get(id)?.active!==false);room.currentRound=makeRound(room,{number:1,blackCard,hostIndex:Math.max(0,idx),hostId:room.playerOrder[Math.max(0,idx)]});return room.currentRound;}
function entries(round,{activeOnly=true}={}){if(!round?.submissions)return[];const a=[];for(const[id,raw]of round.submissions){const s={id:String(raw?.id||id),userId:String(raw?.userId||raw?.playerId||id),card:raw?.card,status:raw?.status||'active',temporary:!!raw?.temporary,temporaryOriginalUserId:raw?.temporaryOriginalUserId||null,createdAt:raw?.createdAt||null};if(!activeOnly||s.status==='active')a.push(s);}return a;}
function forUser(round,userId,opt){const id=String(userId);return entries(round,opt).filter(s=>String(s.userId)===id);}
function hasPlayerSubmission(round,userId){return forUser(round,userId).length>0;}
function required(round,userId){return cardsPerAnswer(round)*answerCount(round,userId);}
function progress(room){const r=room.currentRound,players=room.playerOrder.filter(id=>id!==r.hostId&&room.players.get(id)?.active!==false&&room.players.get(id)?.connected!==false);let expected=0,received=0;for(const id of players){expected+=required(r,id);received+=Math.min(required(r,id),forUser(r,id).length);}return{players,expected,received,allPlayed:players.every(id=>forUser(r,id).length>=required(r,id))};}
function answerId(round,userId,index){return`a${round.number}_${String(userId)}_${index}`;}
function answerGroups(room,{completeOnly=true}={}){const r=room.currentRound,size=cardsPerAnswer(r),out=[];for(const id of room.playerOrder){if(String(id)===String(r.hostId))continue;const subs=forUser(r,id);for(let i=0;i<subs.length;i+=size){const chunk=subs.slice(i,i+size);if(completeOnly&&chunk.length<size)continue;out.push({answerId:answerId(r,id,Math.floor(i/size)),userId:String(id),submissionIds:chunk.map(s=>s.id),cards:chunk.map(s=>s.card),temporary:chunk.some(s=>s.temporary)});}}return out;}
function revealAnswers(room,{forMaster=false}={}){const r=room.currentRound,s=roundState(r),groups=answerGroups(room),map=new Map(groups.map(g=>[g.answerId,g])),order=s.answerRevealOrder?.length?s.answerRevealOrder:groups.map(g=>g.answerId);return order.map((id,index)=>{const a=map.get(String(id));if(!a)return null;const p=room.players.get(String(a.userId));return{index,answerId:a.answerId,submissionId:a.answerId,submissionIds:a.submissionIds,cards:a.cards,card:a.cards.join(' / '),...(forMaster&&s.revealAuthorsToMaster?{authorUserId:p?.userId||Number(a.userId)||null,authorNickname:p?.nickname||'Jogador'}:{})};}).filter(Boolean);}
function findAnswer(room,selector){const groups=answerGroups(room),str=String(selector??'');let a=groups.find(x=>x.answerId===str||x.submissionIds.includes(str));if(a)return a;const n=Number(selector);if(Number.isInteger(n)){const row=revealAnswers(room,{forMaster:true})[n];if(row)a=groups.find(x=>x.answerId===row.answerId);}return a||null;}
function clearReactionWindow(round){const rs=roomState(round);rs.actionSeq=(Number(rs.actionSeq)||0)+1;roundState(round).latestCancellable=null;}
function tempList(round,userId){const rs=roomState(round),id=String(userId);return rs.temporaryPossessions[id]||(rs.temporaryPossessions[id]=[]);}
function addTemporaryMeta(round,userId,meta){if(!meta?.card)return null;const row={...meta};tempList(round,userId).push(row);return row;}
function takeTemporaryMeta(round,userId,card){const arr=tempList(round,userId),i=arr.findIndex(x=>x&&x.card===card);if(i<0)return null;return arr.splice(i,1)[0];}
function moveTemporaryMeta(round,fromUserId,toUserId,card){const m=takeTemporaryMeta(round,fromUserId,card);if(m)addTemporaryMeta(round,toUserId,m);return m;}
function makeSubmissionId(round,userId){return`s${round.number}_${String(userId)}_${crypto.randomUUID()}`;}
function playCard(room,userId,cardIndex){const id=String(userId),r=room.currentRound,p=room.players.get(id);if(!isV2(r))throw new Error('Round Engine v2 não está ativo.');if(room.insufficientSince)throw new Error('A partida está pausada aguardando jogadores reingressarem.');if(room.state!==GAME_STATES.EM_ANDAMENTO)throw new Error('Não é possível jogar cartas neste momento.');if(!p||p.active===false||!p.connected)throw new Error('Você não está ativo na partida.');if(r.hostId===id)throw new Error('O Mestre da rodada não pode jogar cartas.');const have=forUser(r,id).length,want=required(r,id);if(have>=want)throw new Error('Você já enviou todas as cartas exigidas nesta rodada.');if(!Number.isInteger(cardIndex)||cardIndex<0||cardIndex>=p.hand.length)throw new Error('Índice de carta inválido.');const blocked=roundState(r).blockedCards[id]||[],card=p.hand[cardIndex];if(blocked.includes(card))throw new Error('Essa carta foi bloqueada nesta rodada. Escolha outra.');clearReactionWindow(r);p.hand.splice(cardIndex,1);const temp=takeTemporaryMeta(r,id,card),submissionId=makeSubmissionId(r,id);r.submissions.set(submissionId,{id:submissionId,userId:id,card,status:'active',temporary:!!temp,temporaryOriginalUserId:temp?.originalUserId||null,createdAt:new Date().toISOString()});delete roundState(r).needsSubmission[id];const pg=progress(room);if(pg.allPlayed){const rs=roundState(r);rs.revealOrder=shuffleArray(entries(r).map(s=>s.id));rs.answerRevealOrder=shuffleArray(answerGroups(room).map(a=>a.answerId));room.state=GAME_STATES.VOTACAO;}return{room,submissionId,playedCard:card,temporary:!!temp,temporaryOriginalUserId:temp?.originalUserId||null,allPlayed:pg.allPlayed,progress:pg};}
function revealSubmissions(room,{forMaster=false}={}){const r=room.currentRound,s=roundState(r),map=new Map(entries(r).map(x=>[x.id,x])),order=s.revealOrder?.length?s.revealOrder:entries(r).map(x=>x.id);return order.map((id,index)=>{const sub=map.get(String(id));if(!sub)return null;const p=room.players.get(String(sub.userId));return{index,submissionId:sub.id,card:sub.card,...(forMaster&&s.revealAuthorsToMaster?{authorUserId:p?.userId||Number(sub.userId)||null,authorNickname:p?.nickname||'Jogador'}:{})};}).filter(Boolean);}
function findSubmission(room,selector){const active=entries(room.currentRound);if(typeof selector==='string')return active.find(s=>s.id===selector)||null;const n=Number(selector);if(Number.isInteger(n)){const row=revealSubmissions(room,{forMaster:true})[n];return row?active.find(s=>s.id===row.submissionId)||null:null;}return null;}
function assertCanPick(room,userId){const id=String(userId),r=room.currentRound;if(room.insufficientSince)throw new Error('A partida está pausada aguardando jogadores reingressarem.');if(room.state!==GAME_STATES.VOTACAO)throw new Error('Não é possível escolher o vencedor neste momento.');if(r.hostId!==id)throw new Error('Apenas o Mestre da rodada pode escolher o vencedor.');if(!progress(room).allPlayed)throw new Error('Nem todos os jogadores ativos enviaram suas respostas.');}
function pickWinner(room,userId,selector){assertCanPick(room,userId);const r=room.currentRound,answer=findAnswer(room,selector);if(!answer)throw new Error('Resposta inválida.');const q=roundState(r).quePoder;if(q&&!answer.submissionIds.includes(String(q.submissionId)))throw new Error('Que Poder está vinculado à resposta selecionada. Confirme essa resposta.');clearReactionWindow(r);const source=room.players.get(String(answer.userId)),scoringId=q?String(r.hostId):String(answer.userId),scoring=room.players.get(scoringId);if(!source||!scoring)throw new Error('Jogador vencedor não encontrado.');scoring.score++;r.winnerId=String(answer.userId);r.winnerScoringUserId=scoringId;r.winnerSubmissionId=answer.answerId;r.winnerSubmissionIds=[...answer.submissionIds];r.winnerCards=[...answer.cards];r.winnerCard=answer.cards.join(' / ');const gameOver=scoring.score>=room.pointsToWin;room.state=gameOver?GAME_STATES.FINALIZADA:GAME_STATES.RESULTADO_RODADA;return{room,winnerId:String(answer.userId),scoringUserId:scoringId,winnerNickname:scoring.nickname,responseAuthorNickname:source.nickname,winnerCard:r.winnerCard,winnerCards:[...answer.cards],winnerSubmissionId:answer.answerId,winnerSubmissionIds:[...answer.submissionIds],quePoderUsed:!!q,gameOver};}
function nextMaster(room){const r=room.currentRound,rs=roomState(r);if(rs.repeatCurrentMasterOnce){rs.repeatCurrentMasterOnce=false;return{hostIndex:r.hostIndex,hostId:r.hostId,roomState:rs,repeated:true};}const total=room.playerOrder.length,dir=Number(rs.rotationDirection)===-1?-1:1;for(let pass=0;pass<2;pass++)for(let step=1;step<=total;step++){const idx=(r.hostIndex+dir*step%total+total)%total,p=room.players.get(room.playerOrder[idx]);if(p&&p.active!==false&&(pass===1||p.connected!==false))return{hostIndex:idx,hostId:room.playerOrder[idx],roomState:rs,repeated:false};}return{hostIndex:r.hostIndex,hostId:r.hostId,roomState:rs,repeated:false};}
async function nextRound(room){const old=room.currentRound;if(!isV2(old))throw new Error('Round Engine v2 não está ativo.');clearReactionWindow(old);for(const s of entries(old)){const p=room.players.get(String(s.userId));if(p&&p.active!==false)drawCard(room,String(s.userId));}if(!room.blackDeck.length){room.state=GAME_STATES.FINALIZADA;return{room,gameOver:true};}const next=nextMaster(room),blackCard=room.blackDeck.pop(),rs=clone(next.roomState);if(rs.blackoutRound&&Number(rs.blackoutRound)<old.number+1)rs.blackoutRound=null;room.currentRound=makeRound(room,{number:old.number+1,blackCard,hostIndex:next.hostIndex,hostId:next.hostId,previousRoomState:rs});room.state=GAME_STATES.EM_ANDAMENTO;return{room,gameOver:false,repeatedMaster:next.repeated,rotationDirection:room.currentRound.roomState.rotationDirection};}
function redactHand(room,userId,styledHand){const r=room.currentRound;if(!isV2(r))return styledHand;const hidden=(roundState(r).chaosActivators||[]).some(id=>String(id)!==String(userId));if(!hidden)return styledHand;return(styledHand||[]).map((_,i)=>({text:'████',hidden:true,position:i,materialTier:'standard',borderTier:'standard',isPlayerCard:false}));}
function spectatorView(room){const r=room.currentRound;if(!r)return null;return{engineVersion:r.engineVersion||'legacy-v1',roundNumber:r.number,blackCard:r.blackCard,hostId:r.hostId,rotationDirection:isV2(r)?roomState(r).rotationDirection:1,state:room.state,submissionCount:isV2(r)?entries(r).length:r.submissions?.size||0,submissions:room.state===GAME_STATES.VOTACAO&&isV2(r)?revealAnswers(room):null,scores:Array.from(room.players.values()).filter(p=>p.active!==false).map(p=>({nickname:p.nickname,score:p.score}))};}
function serializeRound(r){if(!r)return null;return{engineVersion:r.engineVersion||null,number:r.number,blackCard:r.blackCard,hostIndex:r.hostIndex,hostId:r.hostId,submissions:Object.fromEntries(r.submissions||new Map()),winnerId:r.winnerId||null,winnerScoringUserId:r.winnerScoringUserId||null,winnerSubmissionId:r.winnerSubmissionId||null,winnerSubmissionIds:r.winnerSubmissionIds||[],winnerCard:r.winnerCard||null,winnerCards:r.winnerCards||[],roomState:r.roomState||null,roundState:r.roundState||null,buffState:r.buffState||null};}
module.exports={VERSION,enabled,isV2,defaultRoomState,defaultRoundState,roomState,roundState,cardsPerAnswer,answerCount,makeRound,startFirstRound,entries,forUser,hasPlayerSubmission,required,progress,answerGroups,revealAnswers,findAnswer,clearReactionWindow,tempList,addTemporaryMeta,takeTemporaryMeta,moveTemporaryMeta,playCard,revealSubmissions,findSubmission,pickWinner,nextRound,redactHand,spectatorView,serializeRound};
