'use strict';
const{sql}=require('./db');
const{GAME_STATES}=require('./constants');
const defs=require('./buffDefinitions');
const ENGINE_VERSION='simple-buffs-v1';
const RETRYABLE=new Set(['40001','23505','22012']);
const uid=x=>Number(x)||0;
const aid=x=>String(x||'').trim();
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function ensureState(round){if(!round.buffState||round.buffState.version!==ENGINE_VERSION)round.buffState={version:ENGINE_VERSION,protectedUsers:{},blockedReplayCards:{},pendingTrim:{}};round.buffState.protectedUsers||={};round.buffState.blockedReplayCards||={};round.buffState.pendingTrim||={};return round.buffState;}
function phaseFor(room,userId){if(!room?.currentRound)return defs.PHASES.PREPARATION;const id=String(userId);if(room.state===GAME_STATES.EM_ANDAMENTO)return room.currentRound.submissions?.has(id)?defs.PHASES.SUBMISSIONS:defs.PHASES.HAND;if(room.state===GAME_STATES.VOTACAO)return defs.PHASES.MASTER_CHOICE;if(room.state===GAME_STATES.RESULTADO_RODADA)return defs.PHASES.RESULT;if(room.state===GAME_STATES.FINALIZADA)return defs.PHASES.FINAL_REWARD;return defs.PHASES.TRANSITION;}
function serialRound(r){if(!r)return null;return{number:r.number,blackCard:r.blackCard,hostIndex:r.hostIndex,hostId:r.hostId,submissions:Object.fromEntries(r.submissions||new Map()),winnerId:r.winnerId||null,winnerCard:r.winnerCard||null,buffState:r.buffState||null};}
function snapshot(room){return{round:serialRound(room.currentRound),deck:[...(room.whiteDeck||[])],hands:new Map(Array.from(room.players.entries()).map(([id,p])=>[String(id),[...(p.hand||[])]]))};}
function changedHands(before,room){const out=[];for(const[id,p]of room.players){const old=before.hands.get(String(id))||[],now=p.hand||[];if(JSON.stringify(old)!==JSON.stringify(now))out.push({id:String(id),userId:uid(p.userId||id),old,now:[...now]});}return out;}
async function inventory(userId){return sql`SELECT bi.buff_key,bi.quantity,mc.name,mc.description,mc.price FROM buff_inventory bi JOIN market_catalog mc ON mc.product_key=bi.buff_key WHERE bi.user_id=${uid(userId)} AND bi.quantity>0 ORDER BY mc.sort_order,mc.product_key`;}
async function priorActivation(userId,activationId){return(await sql`SELECT * FROM buff_activations WHERE user_id=${uid(userId)} AND activation_id=${aid(activationId)} LIMIT 1`)[0]||null;}
function validateBase(room,userId,buffKey,activationId){const id=String(userId),player=room?.players?.get(id),def=defs.get(buffKey),phase=phaseFor(room,id);if(process.env.BUFFS_FEATURE_ENABLED==='false')return{error:'feature_disabled'};if(!room?.buffsEnabled)return{error:'room_disabled'};if(!room.currentRound)return{error:'no_round'};if(!player||player.active===false)return{error:'not_player'};if(!def)return{error:'invalid_buff'};if(aid(activationId).length<8)return{error:'invalid_activation_id'};if(!def.phases.includes(phase))return{error:'wrong_phase',phase};return{player,def,phase};}
function opponent(room,actorId,targetUserId){const tid=String(targetUserId||''),t=room.players.get(tid);if(!tid||tid===String(actorId)||!t||t.active===false)throw Object.assign(new Error('Escolha um adversário ativo.'),{buffCode:'invalid_target'});return[tid,t];}
function applyEffect(room,userId,def,input={}){const id=String(userId),p=room.players.get(id),r=room.currentRound,s=ensureState(r);let effect={},publicMessage='';
 if(def.key==='buff_dedo_no_olho'){const[tid,t]=opponent(room,id,input.targetUserId);if(!(t.hand||[]).length)throw Object.assign(new Error('O adversário não possui cartas na mão.'),{buffCode:'empty_target_hand'});const seen=t.hand[Math.floor(Math.random()*t.hand.length)];effect={targetUserId:uid(t.userId||tid),targetNickname:t.nickname,seenCard:seen};publicMessage=`👁️ ${p.nickname} meteu o Dedo no Olho de ${t.nickname}.`;}
 else if(def.key==='buff_foi_sem_querer'){if(r.hostId===id)throw Object.assign(new Error('O Mestre não possui submissão para recolher.'),{buffCode:'role_invalid'});const sub=r.submissions.get(id);if(!sub)throw Object.assign(new Error('Envie uma resposta antes de usar este buff.'),{buffCode:'submission_required'});r.submissions.delete(id);p.hand.push(sub.card);s.blockedReplayCards[id]=sub.card;effect={returnedCard:sub.card,requiresNewSubmission:true};publicMessage=`↩️ ${p.nickname} fingiu que foi sem querer e recolheu a própria resposta.`;}
 else if(def.key==='buff_amigo_de_merda'){const[tid,t]=opponent(room,id,input.targetUserId);if(tid===String(r.hostId)||r.submissions.has(tid))throw Object.assign(new Error('O alvo precisa ainda estar aguardando para responder.'),{buffCode:'target_already_submitted'});if((t.hand||[]).length<2)throw Object.assign(new Error('A mão do alvo não pode ser embaralhada agora.'),{buffCode:'empty_target_hand'});shuffle(t.hand);effect={targetUserId:uid(t.userId||tid),targetNickname:t.nickname};publicMessage=`🌀 ${p.nickname} foi um Amigo de Merda e bagunçou a mão de ${t.nickname}.`;}
 else if(def.key==='buff_xo_ve_aqui'){if(r.submissions.has(id))throw Object.assign(new Error('Use este buff antes de enviar sua resposta.'),{buffCode:'already_submitted'});const[tid,t]=opponent(room,id,input.targetUserId);const idx=Number(input.cardIndex);if(!Number.isInteger(idx)||idx<0||idx>=p.hand.length)throw Object.assign(new Error('Escolha uma carta válida da sua mão.'),{buffCode:'invalid_card'});if(!(t.hand||[]).length)throw Object.assign(new Error('O adversário não possui cartas para trocar.'),{buffCode:'empty_target_hand'});const ti=Math.floor(Math.random()*t.hand.length),mine=p.hand[idx],theirs=t.hand[ti];p.hand[idx]=theirs;t.hand[ti]=mine;effect={targetUserId:uid(t.userId||tid),targetNickname:t.nickname,receivedCard:theirs,gaveCard:mine};publicMessage=`🔄 ${p.nickname} mandou um “Xô vê aqui” em ${t.nickname}.`;}
 else if(def.key==='buff_mao_de_vaca'){if(r.submissions.has(id))throw Object.assign(new Error('Use este buff antes de enviar sua resposta.'),{buffCode:'already_submitted'});if(s.pendingTrim[id])throw Object.assign(new Error('Você já precisa devolver cartas antes de continuar.'),{buffCode:'pending_resolution'});if((room.whiteDeck||[]).length<2)throw Object.assign(new Error('Não há duas cartas disponíveis no pool para este efeito.'),{buffCode:'deck_insufficient'});p.hand.push(room.whiteDeck.pop(),room.whiteDeck.pop());s.pendingTrim[id]={count:2,normalSize:p.hand.length-2};effect={pendingReturn:2,handSize:p.hand.length};publicMessage=`🐄 ${p.nickname} abriu a Mão de Vaca e comprou duas cartas extras.`;}
 else if(def.key==='buff_testemunha_protegida'){if(r.hostId===id||!r.submissions.has(id))throw Object.assign(new Error('Proteja sua resposta depois de submetê-la e antes da revelação.'),{buffCode:'submission_required'});s.protectedUsers[id]=true;effect={protected:true};publicMessage=`🛡️ ${p.nickname} entrou no programa Testemunha Protegida.`;}
 else if(def.key==='buff_toque_de_midas'){if(r.submissions.has(id))throw Object.assign(new Error('Use este buff antes de enviar sua resposta.'),{buffCode:'already_submitted'});const n=p.hand.length;if(!n)throw Object.assign(new Error('Sua mão está vazia.'),{buffCode:'empty_hand'});room.whiteDeck.push(...p.hand.splice(0));shuffle(room.whiteDeck);for(let i=0;i<n;i++)p.hand.push(room.whiteDeck.pop());effect={newHandSize:n};publicMessage=`✨ ${p.nickname} usou o Toque de Midas e trocou a mão inteira.`;}
 else throw Object.assign(new Error('Buff indisponível neste engine.'),{buffCode:'invalid_buff'});
 return{effect,publicMessage};}
function withdrawnUseQueries(room,userId,def,effect){if(def.key!=='buff_foi_sem_querer'||!effect.returnedCard)return[];const id=uid(userId),card=effect.returnedCard;return[
 sql`UPDATE user_cards uc SET times_used=GREATEST(0,uc.times_used-1),matches_used=GREATEST(0,uc.matches_used-CASE WHEN COALESCE((SELECT cmu.used_count FROM card_match_usage cmu WHERE cmu.room_code=${room.code} AND cmu.user_id=${id} AND cmu.type='whiteCards' AND cmu.text=${card}),0)=1 THEN 1 ELSE 0 END),updated_at=now() WHERE uc.user_id=${id} AND uc.type='whiteCards' AND uc.text=${card}`,
 sql`UPDATE card_match_usage SET used_count=GREATEST(0,used_count-1) WHERE room_code=${room.code} AND user_id=${id} AND type='whiteCards' AND text=${card}`
 ];}
async function persistActivation(room,userId,def,activationId,phase,before,effect){const id=uid(userId),a=aid(activationId),afterRound=serialRound(room.currentRound),afterDeck=[...(room.whiteDeck||[])],changes=changedHands(before,room),q=[];
 q.push(sql`SELECT user_id FROM buff_inventory WHERE user_id=${id} AND buff_key=${def.key} FOR UPDATE`);
 q.push(sql`SELECT 1/(SELECT COUNT(*)::int FROM buff_inventory WHERE user_id=${id} AND buff_key=${def.key} AND quantity>0) ok`);
 q.push(sql`SELECT 1/(1-(SELECT COUNT(*)::int FROM buff_activations WHERE room_code=${room.code} AND round_number=${room.currentRound.number} AND user_id=${id})) ok`);
 q.push(sql`UPDATE rooms SET current_round=${JSON.stringify(afterRound)}::jsonb,white_deck=${JSON.stringify(afterDeck)}::jsonb,updated_at=now() WHERE code=${room.code} AND current_round IS NOT DISTINCT FROM ${JSON.stringify(before.round)}::jsonb AND white_deck=${JSON.stringify(before.deck)}::jsonb`);
 q.push(sql`SELECT 1/(SELECT COUNT(*)::int FROM rooms WHERE code=${room.code} AND current_round IS NOT DISTINCT FROM ${JSON.stringify(afterRound)}::jsonb AND white_deck=${JSON.stringify(afterDeck)}::jsonb) ok`);
 for(const c of changes){q.push(sql`UPDATE players SET hand=${JSON.stringify(c.now)}::jsonb WHERE room_code=${room.code} AND user_id=${c.userId} AND hand=${JSON.stringify(c.old)}::jsonb`);q.push(sql`SELECT 1/(SELECT COUNT(*)::int FROM players WHERE room_code=${room.code} AND user_id=${c.userId} AND hand=${JSON.stringify(c.now)}::jsonb) ok`);}
 q.push(...withdrawnUseQueries(room,id,def,effect));
 q.push(sql`INSERT INTO buff_activations(activation_id,room_code,round_number,user_id,buff_key,target_user_id,phase,status,effect) VALUES(${a},${room.code},${room.currentRound.number},${id},${def.key},${effect.targetUserId||null},${phase},${effect.pendingReturn?'applied':'resolved'},${JSON.stringify(effect)}::jsonb)`);
 q.push(sql`UPDATE buff_inventory SET quantity=quantity-1,updated_at=now() WHERE user_id=${id} AND buff_key=${def.key} AND quantity>0`);
 q.push(sql`INSERT INTO buff_inventory_ledger(user_id,buff_key,delta,transaction_type,idempotency_key,reference_type,reference_id,metadata) VALUES(${id},${def.key},-1,'activation',${`activation:${id}:${a}`},'match',${room.code},jsonb_build_object('round',${room.currentRound.number},'engineVersion',${ENGINE_VERSION}))`);
 q.push(sql`SELECT 1/(SELECT COUNT(*)::int FROM buff_activations WHERE user_id=${id} AND activation_id=${a}) committed`);
 return sql.transaction(q,{isolationMode:'Serializable'});
}
async function activate(room,userId,buffKey,activationId,input={}){const id=uid(userId),a=aid(activationId);const old=await priorActivation(id,a);if(old)return{status:'ok',replayed:true,activation:old,effect:old.effect||{},inventory:await inventory(id)};const base=validateBase(room,id,buffKey,a);if(base.error)return{status:base.error,phase:base.phase};const before=snapshot(room);let applied;try{applied=applyEffect(room,id,base.def,input);}catch(e){return{status:e.buffCode||'invalid_effect',message:e.message};}
 for(let attempt=0;attempt<3;attempt++)try{await persistActivation(room,id,base.def,a,base.phase,before,applied.effect);return{status:'ok',replayed:false,effect:applied.effect,publicMessage:applied.publicMessage,inventory:await inventory(id)};}catch(e){const prior=await priorActivation(id,a);if(prior)return{status:'ok',replayed:true,activation:prior,effect:prior.effect||{},inventory:await inventory(id)};if(String(e.code)==='22012')return{status:'conflict',message:'O estado da rodada mudou. Atualize e tente novamente.'};if(String(e.code)==='23505')return{status:'quota_used',message:'Você já ativou um buff nesta rodada.'};if(RETRYABLE.has(String(e.code))&&attempt<2)continue;throw e;}
 return{status:'conflict'};}
async function resolveMaoDeVaca(room,userId,activationId,returnIndices){const id=uid(userId),a=aid(activationId),row=await priorActivation(id,a);if(!row||row.buff_key!=='buff_mao_de_vaca'||row.room_code!==room.code)return{status:'invalid_activation'};if(row.status==='resolved')return{status:'ok',replayed:true,effect:row.effect||{}};const p=room.players.get(String(id)),r=room.currentRound,s=r&&ensureState(r),pending=s?.pendingTrim?.[String(id)];if(!p||!pending)return{status:'missing_pending'};const ix=[...new Set((returnIndices||[]).map(Number))];if(ix.length!==2||ix.some(i=>!Number.isInteger(i)||i<0||i>=p.hand.length))return{status:'invalid_selection'};const before=snapshot(room),returned=[];ix.sort((x,y)=>y-x).forEach(i=>returned.push(p.hand.splice(i,1)[0]));room.whiteDeck.push(...returned);shuffle(room.whiteDeck);delete s.pendingTrim[String(id)];const afterRound=serialRound(room.currentRound),afterDeck=[...room.whiteDeck],oldHand=before.hands.get(String(id))||[],q=[sql`UPDATE rooms SET current_round=${JSON.stringify(afterRound)}::jsonb,white_deck=${JSON.stringify(afterDeck)}::jsonb,updated_at=now() WHERE code=${room.code} AND current_round IS NOT DISTINCT FROM ${JSON.stringify(before.round)}::jsonb AND white_deck=${JSON.stringify(before.deck)}::jsonb`,sql`SELECT 1/(SELECT COUNT(*)::int FROM rooms WHERE code=${room.code} AND current_round IS NOT DISTINCT FROM ${JSON.stringify(afterRound)}::jsonb AND white_deck=${JSON.stringify(afterDeck)}::jsonb) ok`,sql`UPDATE players SET hand=${JSON.stringify(p.hand)}::jsonb WHERE room_code=${room.code} AND user_id=${id} AND hand=${JSON.stringify(oldHand)}::jsonb`,sql`SELECT 1/(SELECT COUNT(*)::int FROM players WHERE room_code=${room.code} AND user_id=${id} AND hand=${JSON.stringify(p.hand)}::jsonb) ok`,sql`UPDATE buff_activations SET status='resolved',resolved_at=now(),effect=effect||${JSON.stringify({pendingReturn:0,returnedCount:2})}::jsonb WHERE user_id=${id} AND activation_id=${a} AND status='applied'`,sql`SELECT 1/(SELECT COUNT(*)::int FROM buff_activations WHERE user_id=${id} AND activation_id=${a} AND status='resolved') committed`];try{await sql.transaction(q,{isolationMode:'Serializable'});return{status:'ok',replayed:false,effect:{returnedCount:2}};}catch(e){if(String(e.code)==='22012')return{status:'conflict'};throw e;}}
async function getState(room,userId){const id=uid(userId),phase=phaseFor(room,id),r=room.currentRound,s=r?ensureState(r):null,used=r?(await sql`SELECT buff_key,activation_id,status,effect,created_at FROM buff_activations WHERE room_code=${room.code} AND round_number=${r.number} AND user_id=${id} LIMIT 1`)[0]||null:null;return{featureEnabled:process.env.BUFFS_FEATURE_ENABLED!=='false',roomEnabled:!!room.buffsEnabled,engineVersion:ENGINE_VERSION,phase,roundNumber:r?.number||0,usedThisRound:used,inventory:await inventory(id),pendingAction:s?.pendingTrim?.[String(id)]?{type:'mao_de_vaca',activationId:used?.activation_id||null,count:2}:null,protectedSubmission:!!s?.protectedUsers?.[String(id)],players:Array.from(room.players.values()).filter(p=>p.active!==false&&String(p.userId)!==String(id)).map(p=>({userId:p.userId,nickname:p.nickname,isMaster:r?String(r.hostId)===String(p.userId):false,hasSubmitted:r?!!r.submissions?.has(String(p.userId)):false})),definitions:defs.list()};}
function assertCanPlay(room,userId,cardIndex){const id=String(userId),r=room.currentRound;if(!r)return;const s=ensureState(r),p=room.players.get(id);if(s.pendingTrim[id])throw new Error('Devolva duas cartas da Mão de Vaca antes de responder.');const blocked=s.blockedReplayCards[id];if(blocked&&p&&Number.isInteger(cardIndex)&&p.hand[cardIndex]===blocked)throw new Error('Você precisa escolher outra carta nesta rodada.');}
function assertCanResolveRound(room){const r=room?.currentRound;if(!r)return;const pending=ensureState(r).pendingTrim||{};const blocking=Object.keys(pending).find(id=>{const p=room.players.get(String(id));return p&&p.active!==false&&p.connected!==false;});if(blocking)throw new Error('Há uma Mão de Vaca pendente. O jogador precisa devolver duas cartas antes do resultado.');}
module.exports={ENGINE_VERSION,ensureState,phaseFor,activate,resolveMaoDeVaca,getState,assertCanPlay,assertCanResolveRound,inventory,serialRound};
