'use strict';
const{sql}=require('./db');const{canonicalIdentity}=require('./cardIdentity');const rules=require('./cardProgressionRules');
async function card(type,text){try{const i=canonicalIdentity(type,text);return(await sql`SELECT * FROM canonical_cards WHERE card_type=${i.cardType} AND normalized_text=${i.normalizedText} LIMIT 1`)[0]||null;}catch(_){return null;}}
async function ensure(userId,cardId){await sql`INSERT INTO user_card_progress(user_id,canonical_card_id) VALUES(${userId},${cardId}) ON CONFLICT DO NOTHING`;}
async function owns(userId,cardId){return!!(await sql`SELECT 1 FROM canonical_card_ownerships WHERE user_id=${userId} AND canonical_card_id=${cardId} LIMIT 1`).length;}
async function original(cardId,userId){return!!(await sql`SELECT 1 FROM canonical_card_authors WHERE canonical_card_id=${cardId} AND user_id=${userId} LIMIT 1`).length;}
async function stats(cardId){const x=(await sql`SELECT (SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_ownerships WHERE canonical_card_id=${cardId}) reach,(SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_ownerships WHERE canonical_card_id=${cardId} AND acquisition_source='match_loot') adoption,(SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_creation_events WHERE canonical_card_id=${cardId} AND creation_kind='independent') coincidence,(SELECT COUNT(*)::int FROM canonical_card_match_presence WHERE canonical_card_id=${cardId}) presence,(SELECT COUNT(*)::int FROM canonical_card_round_events WHERE canonical_card_id=${cardId} AND event_type IN('white_revealed','black_used')) uses,(SELECT COUNT(*)::int FROM canonical_card_round_events WHERE canonical_card_id=${cardId} AND event_type='white_win') wins`)[0]||{},score=rules.legacyScore({reach:x.reach,adoption:x.adoption,coincidence:x.coincidence,presence:x.presence,wins:x.wins}),level=rules.legacyLevel(score);await sql`INSERT INTO canonical_card_stats(canonical_card_id,reach_count,adoption_count,creative_coincidence_count,presence_count,total_uses,global_wins,legacy_score,legacy_level) VALUES(${cardId},${x.reach||0},${x.adoption||0},${x.coincidence||0},${x.presence||0},${x.uses||0},${x.wins||0},${score},${level.key}) ON CONFLICT(canonical_card_id) DO UPDATE SET reach_count=EXCLUDED.reach_count,adoption_count=EXCLUDED.adoption_count,creative_coincidence_count=EXCLUDED.creative_coincidence_count,presence_count=EXCLUDED.presence_count,total_uses=EXCLUDED.total_uses,global_wins=EXCLUDED.global_wins,legacy_score=EXCLUDED.legacy_score,legacy_level=EXCLUDED.legacy_level,updated_at=now()`;for(const a of await sql`SELECT user_id FROM canonical_card_authors WHERE canonical_card_id=${cardId}`)for(const t of rules.LEGACY_THRESHOLDS.filter(v=>v.key!=='nascente'&&score>=v.min))await sql`INSERT INTO canonical_card_legacy_milestones(canonical_card_id,creator_user_id,milestone_key) VALUES(${cardId},${a.user_id},${`legacy_level:${t.key}`}) ON CONFLICT DO NOTHING`;return{...x,score,level:level.key,label:level.label};}
async function globalEvent(cardId,matchId,round,eventType,source=null){const ins=await sql`INSERT INTO canonical_card_round_events(canonical_card_id,match_id,round_number,event_type,source_user_id) VALUES(${cardId},${String(matchId)},${Number(round)||0},${eventType},${source||null}) ON CONFLICT DO NOTHING RETURNING id`;if(eventType==='white_revealed'||eventType==='black_used')await sql`INSERT INTO canonical_card_match_presence(canonical_card_id,match_id,first_round_number) VALUES(${cardId},${String(matchId)},${Number(round)||0}) ON CONFLICT DO NOTHING`;return!!ins.length;}
async function personal(userId,cardId,matchId,round,metric){if(!await owns(userId,cardId))return false;await ensure(userId,cardId);const col=metric==='white_personal_win'?'white_personal_wins':'black_personal_uses';const rows=await sql`WITH ins AS (INSERT INTO card_personal_progress_events(user_id,canonical_card_id,match_id,round_number,metric) VALUES(${userId},${cardId},${String(matchId)},${Number(round)||0},${metric}) ON CONFLICT DO NOTHING RETURNING 1),upd AS (UPDATE user_card_progress SET white_personal_wins=white_personal_wins+CASE WHEN ${col}='white_personal_wins' THEN COALESCE((SELECT COUNT(*) FROM ins),0) ELSE 0 END,black_personal_uses=black_personal_uses+CASE WHEN ${col}='black_personal_uses' THEN COALESCE((SELECT COUNT(*) FROM ins),0) ELSE 0 END,updated_at=now() WHERE user_id=${userId} AND canonical_card_id=${cardId} RETURNING 1) SELECT COUNT(*)::int applied FROM ins`;return Number(rows[0]?.applied||0)>0;}
async function external(room,cardId,source,round){const participants=new Set(Array.from(room.players.values()).filter(p=>p.userId&&p.active!==false).map(p=>String(p.userId)));let n=0;for(const o of await sql`SELECT user_id FROM canonical_card_ownerships WHERE canonical_card_id=${cardId}`){if(!participants.has(String(o.user_id))||String(o.user_id)===String(source))continue;await ensure(o.user_id,cardId);const rows=await sql`WITH ins AS (INSERT INTO card_external_presence_events(user_id,canonical_card_id,match_id,first_round_number,source_user_id) VALUES(${o.user_id},${cardId},${String(room.code)},${Number(round)||0},${source}) ON CONFLICT DO NOTHING RETURNING 1),upd AS (UPDATE user_card_progress SET external_presence_matches=external_presence_matches+COALESCE((SELECT COUNT(*) FROM ins),0),updated_at=now() WHERE user_id=${o.user_id} AND canonical_card_id=${cardId} RETURNING 1) SELECT COUNT(*)::int applied FROM ins`;n+=Number(rows[0]?.applied||0);}return n;}
function same(type,a,b){try{return canonicalIdentity(type,a).normalizedText===canonicalIdentity(type,b).normalizedText;}catch(_){return false;}}
function contributor(room,type,text){const f=type==='blackCards'?'blackCards':'whiteCards';for(const p of room.players.values())if(p.userId&&p.active!==false&&(p[f]||[]).some(v=>same(type,v,text)))return p.userId;return null;}
async function recordResolvedRound(room){
 const r=room.currentRound;if(!r?.number)return{winnerOriginal:false,winnerCanonicalCardIds:[],originalPlays:[]};
 const touched=new Set(),originalPlays=[];
 const black=await card('blackCards',r.blackCard);
 if(black){const source=contributor(room,'blackCards',r.blackCard);await globalEvent(black.id,room.code,r.number,'black_used',source);if(source){await personal(source,black.id,room.code,r.number,'black_personal_use');await external(room,black.id,source,r.number);if(await original(black.id,source)){const p=Array.from(room.players.values()).find(x=>String(x.userId)===String(source));originalPlays.push({userId:source,nickname:p?.nickname||'Jogador',card:black.display_text,type:'black'});}}touched.add(black.id);}
 for(const[id,s]of r.submissions||[]){const p=room.players.get(String(id)),source=p?.userId||Number(id)||null,c=await card('whiteCards',s?.card);if(!c)continue;await globalEvent(c.id,room.code,r.number,'white_revealed',source);if(source){await external(room,c.id,source,r.number);if(await original(c.id,source))originalPlays.push({userId:source,nickname:p?.nickname||'Jogador',card:c.display_text,type:'white'});}touched.add(c.id);}
 let winnerOriginal=false;const winnerCanonicalCardIds=[];
 if(r.winnerId){const p=room.players.get(String(r.winnerId)),source=p?.userId||Number(r.winnerId)||null,winnerTexts=Array.isArray(r.winnerCards)&&r.winnerCards.length?r.winnerCards:(r.winnerCard?[r.winnerCard]:[]);for(const text of winnerTexts){const c=await card('whiteCards',text);if(!c)continue;winnerCanonicalCardIds.push(c.id);await globalEvent(c.id,room.code,r.number,'white_win',source);if(source)await personal(source,c.id,room.code,r.number,'white_personal_win');if(await original(c.id,source))winnerOriginal=true;touched.add(c.id);}}
 for(const id of touched)await stats(id);
 return{winnerOriginal,winnerCanonicalCardId:winnerCanonicalCardIds[0]||null,winnerCanonicalCardIds,originalPlays};
}
async function getLegacyProfile(userId){const authored=await sql`SELECT canonical_card_id id FROM canonical_card_authors WHERE user_id=${userId}`;for(const c of authored)await stats(c.id);const cards=authored.length?await sql`SELECT cc.id,cc.display_text,cc.card_type,s.reach_count,s.adoption_count,s.creative_coincidence_count,s.presence_count,s.global_wins,s.total_uses,s.legacy_score::float,s.legacy_level FROM canonical_card_authors a JOIN canonical_cards cc ON cc.id=a.canonical_card_id JOIN canonical_card_stats s ON s.canonical_card_id=cc.id WHERE a.user_id=${userId} ORDER BY s.legacy_score DESC,cc.created_at`:[],reached=(await sql`SELECT COUNT(DISTINCT o.user_id)::int n FROM canonical_card_authors a JOIN canonical_card_ownerships o ON o.canonical_card_id=a.canonical_card_id WHERE a.user_id=${userId} AND o.user_id<>${userId}`)[0]?.n||0;return{originalCards:cards.length,playersReached:Number(reached),adoptions:cards.reduce((n,c)=>n+Number(c.adoption_count||0),0),creativeCoincidences:cards.reduce((n,c)=>n+Number(c.creative_coincidence_count||0),0),globalPresence:cards.reduce((n,c)=>n+Number(c.presence_count||0),0),globalWins:cards.reduce((n,c)=>n+Number(c.global_wins||0),0),viralOrAbove:cards.filter(c=>['viral','classico','folclore'].includes(c.legacy_level)).length,cards};}
module.exports={...rules,recordResolvedRound,getLegacyProfile,refreshCanonicalStats:stats,originalByUser:original};
