'use strict';
const{sql}=require('./db');
const{canonicalIdentity}=require('./cardIdentity');

const MATERIAL_THRESHOLDS=[{key:'copper',label:'Bronze',min:10},{key:'silver',label:'Prata',min:30},{key:'gold',label:'Ouro',min:60},{key:'platinum',label:'Platina',min:100}];
const BORDER_THRESHOLDS=[{key:'copper',label:'Bronze',min:5},{key:'silver',label:'Prata',min:15},{key:'gold',label:'Ouro',min:40},{key:'platinum',label:'Platina',min:100}];
const LEGACY_THRESHOLDS=[{key:'nascente',label:'Nascente',min:0},{key:'espalhando',label:'Espalhando',min:4},{key:'viral',label:'Viral',min:12},{key:'classico',label:'Clássico',min:30},{key:'folclore',label:'Folclore',min:60}];
const LEGACY_WEIGHTS={reach:1,adoption:1.4,coincidence:.8,presence:1.1,wins:1.3};

function tierFor(score,kind='material'){const thresholds=kind==='border'?BORDER_THRESHOLDS:MATERIAL_THRESHOLDS;const n=Math.max(0,Number(score)||0);let tier={key:'standard',label:'Sem tier',min:0};for(const t of thresholds)if(n>=t.min)tier=t;return tier;}
function progressFor(score,kind='material'){const thresholds=kind==='border'?BORDER_THRESHOLDS:MATERIAL_THRESHOLDS,n=Math.max(0,Number(score)||0),current=tierFor(n,kind),next=thresholds.find(t=>n<t.min)||null;return{score:n,tier:current.key,label:current.label,nextTier:next?.key||null,nextLabel:next?.label||null,target:next?.min||null,remaining:next?Math.max(0,next.min-n):0};}
function legacyScore({reach=0,adoption=0,coincidence=0,presence=0,wins=0}={}){const log=v=>Math.log1p(Math.max(0,Number(v)||0));return log(reach)*LEGACY_WEIGHTS.reach+log(adoption)*LEGACY_WEIGHTS.adoption+log(coincidence)*LEGACY_WEIGHTS.coincidence+log(presence)*LEGACY_WEIGHTS.presence+log(wins)*LEGACY_WEIGHTS.wins;}
function legacyLevel(score){const n=Math.max(0,Number(score)||0);let level=LEGACY_THRESHOLDS[0];for(const t of LEGACY_THRESHOLDS)if(n>=t.min)level=t;return level;}
async function canonicalByText(type,text){let identity;try{identity=canonicalIdentity(type,text);}catch(_){return null;}return(await sql`SELECT * FROM canonical_cards WHERE card_type=${identity.cardType} AND normalized_text=${identity.normalizedText} LIMIT 1`)[0]||null;}
async function ensureProgress(userId,cardId){if(!userId||!cardId)return;await sql`INSERT INTO user_card_progress(user_id,canonical_card_id) VALUES(${userId},${cardId}) ON CONFLICT(user_id,canonical_card_id) DO NOTHING`;}
async function owns(userId,cardId){if(!userId||!cardId)return false;return Boolean((await sql`SELECT 1 FROM canonical_card_ownerships WHERE user_id=${userId} AND canonical_card_id=${cardId} LIMIT 1`).length);}
async function refreshCanonicalStats(cardId){if(!cardId)return null;const row=(await sql`SELECT (SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_ownerships WHERE canonical_card_id=${cardId}) reach,(SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_ownerships WHERE canonical_card_id=${cardId} AND acquisition_source='match_loot') adoption,(SELECT COUNT(DISTINCT user_id)::int FROM canonical_card_creation_events WHERE canonical_card_id=${cardId} AND creation_kind='independent') coincidence,(SELECT COUNT(*)::int FROM canonical_card_match_presence WHERE canonical_card_id=${cardId}) presence,(SELECT COUNT(*)::int FROM canonical_card_round_events WHERE canonical_card_id=${cardId} AND event_type IN('white_revealed','black_used')) uses,(SELECT COUNT(*)::int FROM canonical_card_round_events WHERE canonical_card_id=${cardId} AND event_type='white_win') wins`)[0]||{};const score=legacyScore({reach:row.reach,adoption:row.adoption,coincidence:row.coincidence,presence:row.presence,wins:row.wins}),level=legacyLevel(score);await sql`INSERT INTO canonical_card_stats(canonical_card_id,reach_count,adoption_count,creative_coincidence_count,presence_count,total_uses,global_wins,legacy_score,legacy_level) VALUES(${cardId},${row.reach||0},${row.adoption||0},${row.coincidence||0},${row.presence||0},${row.uses||0},${row.wins||0},${score},${level.key}) ON CONFLICT(canonical_card_id) DO UPDATE SET reach_count=EXCLUDED.reach_count,adoption_count=EXCLUDED.adoption_count,creative_coincidence_count=EXCLUDED.creative_coincidence_count,presence_count=EXCLUDED.presence_count,total_uses=EXCLUDED.total_uses,global_wins=EXCLUDED.global_wins,legacy_score=EXCLUDED.legacy_score,legacy_level=EXCLUDED.legacy_level,updated_at=now()`;const authors=await sql`SELECT user_id FROM canonical_card_authors WHERE canonical_card_id=${cardId}`;for(const a of authors){for(const t of LEGACY_THRESHOLDS.filter(x=>x.key!=='nascente'&&score>=x.min))await sql`INSERT INTO canonical_card_legacy_milestones(canonical_card_id,creator_user_id,milestone_key) VALUES(${cardId},${a.user_id},${`legacy_level:${t.key}`}) ON CONFLICT DO NOTHING`;}return{...row,score,level:level.key,label:level.label};}
async function recordGlobalEvent(cardId,matchId,roundNumber,eventType,sourceUserId=null){if(!cardId||!matchId)return false;const inserted=await sql`INSERT INTO canonical_card_round_events(canonical_card_id,match_id,round_number,event_type,source_user_id) VALUES(${cardId},${String(matchId)},${Number(roundNumber)||0},${eventType},${sourceUserId||null}) ON CONFLICT DO NOTHING RETURNING id`;if(!inserted.length)return false;if(eventType==='white_revealed'||eventType==='black_used')await sql`INSERT INTO canonical_card_match_presence(canonical_card_id,match_id,first_round_number) VALUES(${cardId},${String(matchId)},${Number(roundNumber)||0}) ON CONFLICT(canonical_card_id,match_id) DO NOTHING`;await refreshCanonicalStats(cardId);return true;}
async function recordPersonal(userId,cardId,matchId,roundNumber,metric){if(!await owns(userId,cardId))return false;await ensureProgress(userId,cardId);const inserted=await sql`INSERT INTO card_personal_progress_events(user_id,canonical_card_id,match_id,round_number,metric) VALUES(${userId},${cardId},${String(matchId)},${Number(roundNumber)||0},${metric}) ON CONFLICT DO NOTHING RETURNING user_id`;if(!inserted.length)return false;if(metric==='white_personal_win')await sql`UPDATE user_card_progress SET white_personal_wins=white_personal_wins+1,updated_at=now() WHERE user_id=${userId} AND canonical_card_id=${cardId}`;else await sql`UPDATE user_card_progress SET black_personal_uses=black_personal_uses+1,updated_at=now() WHERE user_id=${userId} AND canonical_card_id=${cardId}`;return true;}
async function recordExternal(room,cardId,sourceUserId,roundNumber){if(!cardId||!sourceUserId)return 0;const participants=new Set(Array.from(room.players.values()).filter(p=>p.userId&&p.active!==false).map(p=>String(p.userId)));const owners=await sql`SELECT user_id FROM canonical_card_ownerships WHERE canonical_card_id=${cardId}`;let count=0;for(const o of owners){if(!participants.has(String(o.user_id))||String(o.user_id)===String(sourceUserId))continue;await ensureProgress(o.user_id,cardId);const ins=await sql`INSERT INTO card_external_presence_events(user_id,canonical_card_id,match_id,first_round_number,source_user_id) VALUES(${o.user_id},${cardId},${String(room.code)},${Number(roundNumber)||0},${sourceUserId}) ON CONFLICT DO NOTHING RETURNING user_id`;if(ins.length){count++;await sql`UPDATE user_card_progress SET external_presence_matches=external_presence_matches+1,updated_at=now() WHERE user_id=${o.user_id} AND canonical_card_id=${cardId}`;}}return count;}
function sameCard(type,a,b){try{return canonicalIdentity(type,a).normalizedText===canonicalIdentity(type,b).normalizedText;}catch(_){return false;}}
function firstContributor(room,type,text){const field=type==='blackCards'?'blackCards':'whiteCards';for(const p of room.players.values()){if(!p.userId||p.active===false)continue;if((p[field]||[]).some(x=>sameCard(type,x,text)))return p.userId;}return null;}
async function originalByUser(cardId,userId){if(!cardId||!userId)return false;return Boolean((await sql`SELECT 1 FROM canonical_card_authors WHERE canonical_card_id=${cardId} AND user_id=${userId} LIMIT 1`).length);}
async function recordResolvedRound(room){const r=room.currentRound;if(!r?.number)return{winnerOriginal:false};const touched=new Set();const black=await canonicalByText('blackCards',r.blackCard);if(black){const source=firstContributor(room,'blackCards',r.blackCard);await recordGlobalEvent(black.id,room.code,r.number,'black_used',source);if(source)await recordPersonal(source,black.id,room.code,r.number,'black_personal_use');if(source)await recordExternal(room,black.id,source,r.number);touched.add(black.id);}for(const[id,s]of r.submissions||[]){const p=room.players.get(String(id)),source=p?.userId||Number(id)||null,card=await canonicalByText('whiteCards',s?.card);if(!card)continue;await recordGlobalEvent(card.id,room.code,r.number,'white_revealed',source);if(source)await recordExternal(room,card.id,source,r.number);touched.add(card.id);}let winnerOriginal=false,winnerCanonicalCardId=null;if(r.winnerCard&&r.winnerId){const p=room.players.get(String(r.winnerId)),source=p?.userId||Number(r.winnerId)||null,card=await canonicalByText('whiteCards',r.winnerCard);if(card){winnerCanonicalCardId=card.id;await recordGlobalEvent(card.id,room.code,r.number,'white_win',source);if(source)await recordPersonal(source,card.id,room.code,r.number,'white_personal_win');winnerOriginal=await originalByUser(card.id,source);touched.add(card.id);}}for(const id of touched)await refreshCanonicalStats(id);return{winnerOriginal,winnerCanonicalCardId};}
async function getProgress(userId,cardIds=[]){if(!cardIds.length)return new Map();const rows=await sql`SELECT * FROM user_card_progress WHERE user_id=${userId}`;return new Map(rows.filter(r=>cardIds.some(id=>String(id)===String(r.canonical_card_id))).map(r=>{const materialScore=Number(r.white_personal_wins||0)+Number(r.black_personal_uses||0),borderScore=Number(r.external_presence_matches||0);return[String(r.canonical_card_id),{whitePersonalWins:Number(r.white_personal_wins||0),blackPersonalUses:Number(r.black_personal_uses||0),externalPresenceMatches:borderScore,material:progressFor(materialScore,'material'),border:progressFor(borderScore,'border')}];}));}
async function getLegacyProfile(userId){const authored=await sql`SELECT cc.id,cc.display_text,cc.card_type,COALESCE(s.reach_count,0)::int reach_count,COALESCE(s.adoption_count,0)::int adoption_count,COALESCE(s.creative_coincidence_count,0)::int creative_coincidence_count,COALESCE(s.presence_count,0)::int presence_count,COALESCE(s.global_wins,0)::int global_wins,COALESCE(s.total_uses,0)::int total_uses,COALESCE(s.legacy_score,0)::float legacy_score,COALESCE(s.legacy_level,'nascente') legacy_level FROM canonical_card_authors a JOIN canonical_cards cc ON cc.id=a.canonical_card_id LEFT JOIN canonical_card_stats s ON s.canonical_card_id=cc.id WHERE a.user_id=${userId} ORDER BY COALESCE(s.legacy_score,0) DESC,cc.created_at`;for(const c of authored)await refreshCanonicalStats(c.id);const fresh=authored.length?await sql`SELECT cc.id,cc.display_text,cc.card_type,s.reach_count,s.adoption_count,s.creative_coincidence_count,s.presence_count,s.global_wins,s.total_uses,s.legacy_score::float,s.legacy_level FROM canonical_card_authors a JOIN canonical_cards cc ON cc.id=a.canonical_card_id JOIN canonical_card_stats s ON s.canonical_card_id=cc.id WHERE a.user_id=${userId} ORDER BY s.legacy_score DESC,cc.created_at`:[];const reached=(await sql`SELECT COUNT(DISTINCT o.user_id)::int n FROM canonical_card_authors a JOIN canonical_card_ownerships o ON o.canonical_card_id=a.canonical_card_id WHERE a.user_id=${userId} AND o.user_id<>${userId}`)[0]?.n||0;return{originalCards:fresh.length,playersReached:Number(reached),adoptions:fresh.reduce((n,c)=>n+Number(c.adoption_count||0),0),creativeCoincidences:fresh.reduce((n,c)=>n+Number(c.creative_coincidence_count||0),0),globalPresence:fresh.reduce((n,c)=>n+Number(c.presence_count||0),0),globalWins:fresh.reduce((n,c)=>n+Number(c.global_wins||0),0),viralOrAbove:fresh.filter(c=>['viral','classico','folclore'].includes(c.legacy_level)).length,cards:fresh};}
module.exports={MATERIAL_THRESHOLDS,BORDER_THRESHOLDS,LEGACY_THRESHOLDS,LEGACY_WEIGHTS,tierFor,progressFor,legacyScore,legacyLevel,ensureProgress,refreshCanonicalStats,recordResolvedRound,getProgress,getLegacyProfile,originalByUser};
