'use strict';
const{sql}=require('./db');
const{requireUser}=require('./auth');

const CREATOR_ADMIN_USER_ID=1;
function cleanText(v,max=240){return String(v||'').trim().slice(0,max);}
async function requireCreatorAdmin(req,res){const user=await requireUser(req,res);if(!user)return null;if(Number(user.id)!==CREATOR_ADMIN_USER_ID){res.statusCode=403;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({success:false,error:'Ferramenta exclusiva do administrador do jogo.'}));return null;}return user;}
async function resolveUser(target){const q=cleanText(target,80);if(!q)return null;const rows=await sql`SELECT id,username,display_name FROM users WHERE lower(username)=lower(${q}) OR lower(display_name)=lower(${q}) ORDER BY CASE WHEN lower(username)=lower(${q}) THEN 0 ELSE 1 END,id LIMIT 3`;if(!rows.length)return null;if(rows.length>1&&String(rows[0].username).toLowerCase()!==q.toLowerCase()&&String(rows[0].display_name).toLowerCase()===q.toLowerCase())return{ambiguous:true,matches:rows};return rows[0];}
function validateAmount(v){const n=Math.trunc(Number(v));return Number.isInteger(n)&&n>0&&n<=10000000?n:null;}
function safeOperationId(v){const x=String(v||'').trim();return /^[a-zA-Z0-9_-]{8,120}$/.test(x)?x:null;}
function individualCreditQuery(userId,amount,operationId,message){const id=Number(userId),key=`admin:${operationId}:${id}`,metadata={source:'creator_admin',message:cleanText(message,240)};return sql`WITH ins AS (INSERT INTO dirty_coin_ledger(user_id,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) VALUES(${id},${amount},'adjustment',${key},'admin_grant',${operationId},${JSON.stringify(metadata)}::jsonb) ON CONFLICT(idempotency_key) DO NOTHING RETURNING amount) UPDATE dirty_coin_wallets SET balance=balance+COALESCE((SELECT SUM(amount) FROM ins),0),updated_at=now() WHERE user_id=${id} RETURNING balance`;}
async function creditIndividual(userId,amount,operationId,message){const id=Number(userId);const result=await sql.transaction([sql`INSERT INTO dirty_coin_wallets(user_id,balance) VALUES(${id},0) ON CONFLICT(user_id) DO NOTHING`,individualCreditQuery(id,amount,operationId,message)],{isolationMode:'Serializable'});return Number(result?.[1]?.[0]?.balance||0);}
async function creditAll(amount,operationId,message){const prefix=`admin:${operationId}:`,metadata={source:'creator_admin',message:cleanText(message,240),scope:'global'};const result=await sql.transaction([sql`INSERT INTO dirty_coin_wallets(user_id,balance) SELECT id,0 FROM users ON CONFLICT(user_id) DO NOTHING`,sql`WITH ins AS (INSERT INTO dirty_coin_ledger(user_id,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) SELECT u.id,${amount},'adjustment',${prefix}||u.id::text,'admin_grant',${operationId},${JSON.stringify(metadata)}::jsonb FROM users u ON CONFLICT(idempotency_key) DO NOTHING RETURNING user_id,amount),s AS (SELECT user_id,SUM(amount)::bigint amount FROM ins GROUP BY user_id),upd AS (UPDATE dirty_coin_wallets w SET balance=w.balance+s.amount,updated_at=now() FROM s WHERE w.user_id=s.user_id RETURNING w.user_id) SELECT COUNT(*)::int credited FROM upd`],{isolationMode:'Serializable'});return Number(result?.[1]?.[0]?.credited||0);}
module.exports={CREATOR_ADMIN_USER_ID,cleanText,requireCreatorAdmin,resolveUser,validateAmount,safeOperationId,creditIndividual,creditAll};
