const { GAME_STATES, MIN_PLAYERS, HAND_SIZE } = require('./constants');
const { validateNickname, validateCards, validateRoomJoin, validateCardPlay, validatePickWinner } = require('./validators');
const { generateRoomCode, buildDecks, dealHands, drawCard, getNextHostIndex, calculateRanking } = require('./gameLogic');
const roomStore = require('./roomStore');
const deckStore = require('./deckStore');
const playerStats = require('./playerStats');

async function createRoom(playerId,nickname,config={}){
 const v=validateNickname(nickname);if(!v.valid)throw new Error(v.error);let code;do{code=generateRoomCode();}while(await roomStore.roomExists(code));
 const room={code,creatorId:playerId,maxPlayers:config.maxPlayers||8,blackCardsPerPlayer:0,whiteCardsPerPlayer:0,pointsToWin:config.pointsToWin||5,handSize:config.handSize||5,useStandardDeck:config.useStandardDeck!==false,cardCreationEnabled:config.cardCreationEnabled!==false,state:GAME_STATES.AGUARDANDO_JOGADORES,players:new Map(),playerOrder:[],blackDeck:[],whiteDeck:[],currentRound:null};
 room.players.set(playerId,{userId:null,nickname:nickname.trim(),score:0,hand:[],cardsReady:false,blackCards:[],whiteCards:[],connected:true,lastActive:Date.now()});room.playerOrder.push(playerId);await roomStore.insertRoom(room);return{code,room};
}
async function joinRoom(room,playerId,nickname){const v=validateNickname(nickname);if(!v.valid)throw new Error(v.error);const j=validateRoomJoin(room,nickname.trim(),playerId);if(!j.valid)throw new Error(j.error);if(j.isRejoin){const p=room.players.get(playerId);p.nickname=nickname.trim();p.connected=true;p.lastActive=Date.now();return{room,isRejoin:true};}room.players.set(playerId,{userId:null,nickname:nickname.trim(),score:0,hand:[],cardsReady:false,blackCards:[],whiteCards:[],connected:true,lastActive:Date.now()});room.playerOrder.push(playerId);if(room.players.size>=MIN_PLAYERS&&room.state===GAME_STATES.AGUARDANDO_JOGADORES)room.state=GAME_STATES.CADASTRO_CARTAS;return{room};}
function updateRoomConfig(room,playerId,partial){if(room.creatorId===playerId&&room.players.has(playerId)&&partial.maxPlayers)room.maxPlayers=partial.maxPlayers;return room;}
async function submitCards(room,playerId,blackCards,whiteCards,meta={}){const p=room.players.get(playerId);if(!p)throw new Error('Você não está nesta sala.');if(p.cardsReady)throw new Error('Você já concluiu suas Cartas de Jogador.');if(![GAME_STATES.CADASTRO_CARTAS,GAME_STATES.AGUARDANDO_JOGADORES].includes(room.state))throw new Error('Não é possível enviar cartas neste momento.');const v=validateCards(blackCards,whiteCards);if(!v.valid)throw new Error(v.error);p.blackCards=(blackCards||[]).map(x=>x.trim());p.whiteCards=(whiteCards||[]).map(x=>x.trim());p.cardsReady=true;if(p.userId){await playerStats.ensureOwnedCards(p.userId,'blackCards',p.blackCards);await playerStats.ensureOwnedCards(p.userId,'whiteCards',p.whiteCards);await playerStats.markCreatedDuplicates(room,p.userId,'blackCards',meta.createdBlackCards||[]);await playerStats.markCreatedDuplicates(room,p.userId,'whiteCards',meta.createdWhiteCards||[]);}let allReady=true;for(const[,x]of room.players)if(!x.cardsReady){allReady=false;break;}if(allReady&&room.players.size>=MIN_PLAYERS)room.state=GAME_STATES.PRONTA_PARA_INICIAR;return{room,allReady};}
async function startGame(room,playerId){if(room.creatorId!==playerId)throw new Error('Apenas o criador da sala pode iniciar o jogo.');if(room.state!==GAME_STATES.PRONTA_PARA_INICIAR)throw new Error('O jogo ainda não está pronto. Todos devem concluir a etapa de Cartas de Jogador.');if(room.players.size<MIN_PLAYERS)throw new Error(`São necessários pelo menos ${MIN_PLAYERS} jogadores.`);for(const[,p]of room.players)if(!p.cardsReady)throw new Error('Nem todos os jogadores estão prontos.');const host=room.players.get(room.creatorId);const hostDeck=room.useStandardDeck?await deckStore.getUserDeck(host?.userId):{blackCards:[],whiteCards:[]};const {newBlackCards,newWhiteCards}=buildDecks(room,hostDeck);for(const text of newBlackCards)await deckStore.addCard('blackCards',text,false);for(const text of newWhiteCards)await deckStore.addCard('whiteCards',text,false);if(room.blackDeck.length<1||room.whiteDeck.length<room.players.size*room.handSize)throw new Error('O deck do Host + Cartas de Jogadores não possui cartas suficientes para iniciar.');dealHands(room);room.state=GAME_STATES.EM_ANDAMENTO;room.currentRound={number:1,blackCard:room.blackDeck.pop(),hostIndex:0,hostId:room.playerOrder[0],submissions:new Map(),winnerId:null,winnerCard:null};await playerStats.recordSeen(room,'blackCards',room.currentRound.blackCard);return{room};}
function playCard(room,playerId,cardIndex){const v=validateCardPlay(room,playerId);if(!v.valid)throw new Error(v.error);const p=room.players.get(playerId);if(typeof cardIndex!=='number'||cardIndex<0||cardIndex>=p.hand.length)throw new Error('Índice de carta inválido.');const[card]=p.hand.splice(cardIndex,1);room.currentRound.submissions.set(playerId,{card});const others=room.playerOrder.filter(id=>id!==room.currentRound.hostId&&room.players.has(id)&&room.players.get(id).connected);const allPlayed=others.every(id=>room.currentRound.submissions.has(id));if(allPlayed)room.state=GAME_STATES.VOTACAO;return{room,allPlayed,playedCard:card};}
function pickWinner(room,playerId,submissionIndex){const v=validatePickWinner(room,playerId);if(!v.valid)throw new Error(v.error);const arr=Array.from(room.currentRound.submissions.entries());if(typeof submissionIndex!=='number'||submissionIndex<0||submissionIndex>=arr.length)throw new Error('Índice de submissão inválido.');const[winnerId,submission]=arr[submissionIndex],winner=room.players.get(winnerId);if(!winner)throw new Error('Jogador vencedor não encontrado.');winner.score++;room.currentRound.winnerId=winnerId;room.currentRound.winnerCard=submission.card;const gameOver=winner.score>=room.pointsToWin;room.state=gameOver?GAME_STATES.FINALIZADA:GAME_STATES.RESULTADO_RODADA;return{room,winnerId,winnerNickname:winner.nickname,winnerCard:submission.card,gameOver};}
async function nextRound(room){for(const[playerId]of room.currentRound.submissions)drawCard(room,playerId);if(!room.blackDeck.length){room.state=GAME_STATES.FINALIZADA;return{room,gameOver:true};}const hostIndex=getNextHostIndex(room),hostId=room.playerOrder[hostIndex],blackCard=room.blackDeck.pop();room.currentRound={number:room.currentRound.number+1,blackCard,hostIndex,hostId,submissions:new Map(),winnerId:null,winnerCard:null};room.state=GAME_STATES.EM_ANDAMENTO;await playerStats.recordSeen(room,'blackCards',blackCard);return{room,gameOver:false};}
function removePlayer(room,playerId,explicitLeave=false){const p=room.players.get(playerId);if(!p)return{room,removed:false};const nickname=p.nickname;let masterDropped=false,gameOver=false,destroyed=false;const wasCreator=room.creatorId===playerId,isMid=[GAME_STATES.EM_ANDAMENTO,GAME_STATES.VOTACAO].includes(room.state);p.connected=false;if(!isMid||explicitLeave){room.players.delete(playerId);room.playerOrder=room.playerOrder.filter(id=>id!==playerId);if([GAME_STATES.AGUARDANDO_JOGADORES,GAME_STATES.CADASTRO_CARTAS,GAME_STATES.PRONTA_PARA_INICIAR].includes(room.state)){if(room.players.size>0&&wasCreator)destroyed=true;else if(room.players.size<MIN_PLAYERS)room.state=GAME_STATES.AGUARDANDO_JOGADORES;}else if(isMid){if(room.players.size<MIN_PLAYERS)gameOver=true;else if(room.currentRound?.hostId===playerId)masterDropped=true;}}else if(room.currentRound?.hostId===playerId)masterDropped=true;return{room,removed:true,nickname,czarDropped:masterDropped,masterDropped,gameOver,destroyed};}
const DISCONNECTED_AFTER_MS=35*1000,REMOVED_AFTER_MS=120*1000;
function sweepPresence(room){const now=Date.now(),events={disconnected:[],removed:[]};for(const[playerId,p]of Array.from(room.players.entries())){const idle=now-p.lastActive;if(p.connected&&idle>DISCONNECTED_AFTER_MS){p.connected=false;events.disconnected.push({playerId,nickname:p.nickname});}if(idle>REMOVED_AFTER_MS){const r=removePlayer(room,playerId,false);if(r.removed)events.removed.push({playerId,nickname:r.nickname,czarDropped:r.czarDropped,masterDropped:r.masterDropped,gameOver:r.gameOver,destroyed:r.destroyed});}}return events;}
function getPlayerList(room){const out=[];for(const[id,p]of room.players)out.push({nickname:p.nickname,score:p.score,cardsReady:p.cardsReady,connected:p.connected,isCreator:id===room.creatorId});return out;}
function getScoresForRoom(room){return Array.from(room.players.values()).map(p=>({nickname:p.nickname,score:p.score})).sort((a,b)=>b.score-a.score);}
module.exports={createRoom,joinRoom,updateRoomConfig,submitCards,startGame,playCard,pickWinner,nextRound,removePlayer,sweepPresence,getPlayerList,getScoresForRoom,calculateRanking,HAND_SIZE};
