const { GAME_STATES, MIN_PLAYERS, HAND_SIZE } = require('./constants');
const { validateNickname, validateCards, validateRoomJoin, validateCardPlay, validatePickWinner } = require('./validators');
const { generateRoomCode, buildDecks, dealHands, drawCard, getNextHostIndex, calculateRanking } = require('./gameLogic');
const roomStore=require('./roomStore'),deckStore=require('./deckStore'),playerStats=require('./playerStats');
const activeEntries=room=>Array.from(room.players.entries()).filter(([,p])=>p.active!==false);
const activeCount=room=>activeEntries(room).length;
function makePlayer(playerId,nickname,meta={}){return{userId:Number(playerId)||null,visualId:meta.visualId||null,nickname:nickname.trim(),avatarData:meta.avatarData||null,titleKey:meta.titleKey||null,frameKey:meta.frameKey||null,score:0,hand:[],cardsReady:false,blackCards:[],whiteCards:[],connected:true,active:true,lastActive:Date.now()};}
async function createRoom(playerId,nickname,config={}){const v=validateNickname(nickname);if(!v.valid)throw new Error(v.error);let code;do{code=generateRoomCode();}while(await roomStore.roomExists(code));const room={code,creatorId:String(playerId),maxPlayers:config.maxPlayers||8,blackCardsPerPlayer:0,whiteCardsPerPlayer:0,pointsToWin:config.pointsToWin||5,handSize:config.handSize||5,useStandardDeck:config.useStandardDeck!==false,cardCreationEnabled:config.cardCreationEnabled!==false,state:GAME_STATES.AGUARDANDO_JOGADORES,players:new Map(),playerOrder:[],blackDeck:[],whiteDeck:[],currentRound:null};const key=String(playerId);room.players.set(key,makePlayer(playerId,nickname,config));room.playerOrder.push(key);await roomStore.insertRoom(room);return{code,room};}
async function joinRoom(room,playerId,nickname,meta={}){const key=String(playerId),v=validateNickname(nickname);if(!v.valid)throw new Error(v.error);const j=validateRoomJoin(room,nickname.trim(),key);if(!j.valid)throw new Error(j.error);if(j.isRejoin){const p=room.players.get(key);p.nickname=nickname.trim();p.avatarData=meta.avatarData||p.avatarData||null;p.visualId=meta.visualId||p.visualId||null;p.titleKey=meta.titleKey!==undefined?meta.titleKey:p.titleKey||null;p.frameKey=meta.frameKey!==undefined?meta.frameKey:p.frameKey||null;p.connected=true;p.active=true;p.lastActive=Date.now();if(!room.playerOrder.includes(key))room.playerOrder.push(key);return{room,isRejoin:true,resumed:true};}room.players.set(key,makePlayer(playerId,nickname,meta));room.playerOrder.push(key);if(activeCount(room)>=MIN_PLAYERS&&room.state===GAME_STATES.AGUARDANDO_JOGADORES)room.state=GAME_STATES.CADASTRO_CARTAS;return{room,isRejoin:false};}
function updateRoomConfig(room,playerId,partial){const key=String(playerId);if(room.creatorId===key&&room.players.has(key)&&partial.maxPlayers)room.maxPlayers=partial.maxPlayers;return room;}
async function submitCards(room,playerId,blackCards,whiteCards,meta={}){const p=room.players.get(String(playerId));if(!p||p.active===false)throw new Error('Você não está nesta sala.');if(p.cardsReady)throw new Error('Você já concluiu suas Cartas de Jogador.');if(![GAME_STATES.CADASTRO_CARTAS,GAME_STATES.AGUARDANDO_JOGADORES].includes(room.state))throw new Error('Não é possível enviar cartas neste momento.');const v=validateCards(blackCards,whiteCards);if(!v.valid)throw new Error(v.error);p.blackCards=(blackCards||[]).map(x=>x.trim());p.whiteCards=(whiteCards||[]).map(x=>x.trim());p.cardsReady=true;if(p.userId){await playerStats.registerSubmittedCards(room,p,'blackCards',p.blackCards,meta.createdBlackCards||[]);await playerStats.registerSubmittedCards(room,p,'whiteCards',p.whiteCards,meta.createdWhiteCards||[]);await playerStats.ensureOwnedCards(p.userId,'blackCards',p.blackCards);await playerStats.ensureOwnedCards(p.userId,'whiteCards',p.whiteCards);await playerStats.markCreatedDuplicates(room,p.userId,'blackCards',meta.createdBlackCards||[]);await playerStats.markCreatedDuplicates(room,p.userId,'whiteCards',meta.createdWhiteCards||[]);}const active=activeEntries(room);const allReady=active.every(([,x])=>x.cardsReady);if(allReady&&active.length>=MIN_PLAYERS)room.state=GAME_STATES.PRONTA_PARA_INICIAR;return{room,allReady};}
async function startGame(room,playerId){const key=String(playerId);if(room.creatorId!==key)throw new Error('Apenas o criador da sala pode iniciar o jogo.');if(room.state!==GAME_STATES.PRONTA_PARA_INICIAR)throw new Error('O jogo ainda não está pronto. Todos devem concluir a etapa de Cartas de Jogador.');const active=activeEntries(room);if(active.length<MIN_PLAYERS)throw new Error(`São necessários pelo menos ${MIN_PLAYERS} jogadores.`);for(const[,p]of active)if(!p.cardsReady)throw new Error('Nem todos os jogadores estão prontos.');const sharedBlack=[],sharedWhite=[];for(const[,p]of active){sharedBlack.push(...(p.blackCards||[]));sharedWhite.push(...(p.whiteCards||[]));}await playerStats.sharePlayerCards(room,'blackCards',sharedBlack);await playerStats.sharePlayerCards(room,'whiteCards',sharedWhite);const host=room.players.get(room.creatorId),hostDeck=room.useStandardDeck?await deckStore.getUserDeck(host?.userId):{blackCards:[],whiteCards:[]};const {newBlackCards,newWhiteCards}=buildDecks(room,hostDeck);for(const t of newBlackCards)await deckStore.addCard('blackCards',t,false);for(const t of newWhiteCards)await deckStore.addCard('whiteCards',t,false);if(room.blackDeck.length<1||room.whiteDeck.length<active.length*room.handSize)throw new Error('O deck do Host + Cartas de Jogadores não possui cartas suficientes para iniciar.');await playerStats.recordRoomCardVisits(room);dealHands(room);room.state=GAME_STATES.EM_ANDAMENTO;const firstIndex=room.playerOrder.findIndex(id=>room.players.get(id)?.active!==false);room.currentRound={number:1,blackCard:room.blackDeck.pop(),hostIndex:Math.max(0,firstIndex),hostId:room.playerOrder[Math.max(0,firstIndex)],submissions:new Map(),winnerId:null,winnerCard:null};await playerStats.recordSeen(room,'blackCards',room.currentRound.blackCard);return{room};}
function playCard(room,playerId,cardIndex){const key=String(playerId),v=validateCardPlay(room,key);if(!v.valid)throw new Error(v.error);const p=room.players.get(key);if(typeof cardIndex!=='number'||cardIndex<0||cardIndex>=p.hand.length)throw new Error('Índice de carta inválido.');const[card]=p.hand.splice(cardIndex,1);room.currentRound.submissions.set(key,{card});const others=room.playerOrder.filter(id=>id!==room.currentRound.hostId&&room.players.get(id)?.active!==false&&room.players.get(id)?.connected);const allPlayed=others.every(id=>room.currentRound.submissions.has(id));if(allPlayed)room.state=GAME_STATES.VOTACAO;return{room,allPlayed,playedCard:card};}
function pickWinner(room,playerId,submissionIndex){const key=String(playerId),v=validatePickWinner(room,key);if(!v.valid)throw new Error(v.error);const arr=Array.from(room.currentRound.submissions.entries());if(typeof submissionIndex!=='number'||submissionIndex<0||submissionIndex>=arr.length)throw new Error('Índice de submissão inválido.');const[winnerId,submission]=arr[submissionIndex],winner=room.players.get(winnerId);if(!winner)throw new Error('Jogador vencedor não encontrado.');winner.score++;room.currentRound.winnerId=winnerId;room.currentRound.winnerCard=submission.card;const gameOver=winner.score>=room.pointsToWin;room.state=gameOver?GAME_STATES.FINALIZADA:GAME_STATES.RESULTADO_RODADA;return{room,winnerId,winnerNickname:winner.nickname,winnerCard:submission.card,gameOver};}
async function nextRound(room){for(const[id]of room.currentRound.submissions)if(room.players.get(id)?.active!==false)drawCard(room,id);if(!room.blackDeck.length){room.state=GAME_STATES.FINALIZADA;return{room,gameOver:true};}const hostIndex=getNextHostIndex(room),hostId=room.playerOrder[hostIndex],blackCard=room.blackDeck.pop();room.currentRound={number:room.currentRound.number+1,blackCard,hostIndex,hostId,submissions:new Map(),winnerId:null,winnerCard:null};room.state=GAME_STATES.EM_ANDAMENTO;await playerStats.recordSeen(room,'blackCards',blackCard);return{room,gameOver:false};}
function removePlayer(room,playerId,explicitLeave=false){const key=String(playerId),p=room.players.get(key);if(!p||p.active===false)return{room,removed:false};const nickname=p.nickname;let masterDropped=false,gameOver=false,destroyed=false;const wasCreator=room.creatorId===key,isMid=[GAME_STATES.EM_ANDAMENTO,GAME_STATES.VOTACAO].includes(room.state);p.connected=false;p.active=false;const remaining=activeCount(room);if(!isMid&&explicitLeave&&wasCreator&&remaining>0)destroyed=true;if(!isMid&&remaining<MIN_PLAYERS)room.state=GAME_STATES.AGUARDANDO_JOGADORES;if(isMid){if(explicitLeave&&remaining<MIN_PLAYERS)gameOver=true;else if(room.currentRound?.hostId===key)masterDropped=true;}return{room,removed:true,nickname,czarDropped:masterDropped,masterDropped,gameOver,destroyed,canRejoin:!explicitLeave||isMid};}
const DISCONNECTED_AFTER_MS=35*1000,REMOVED_AFTER_MS=120*1000;
function sweepPresence(room){const now=Date.now(),events={disconnected:[],removed:[]};for(const[id,p]of room.players){if(p.active===false)continue;const idle=now-p.lastActive;if(p.connected&&idle>DISCONNECTED_AFTER_MS){p.connected=false;events.disconnected.push({playerId:id,nickname:p.nickname});}if(idle>REMOVED_AFTER_MS){const r=removePlayer(room,id,false);if(r.removed)events.removed.push({playerId:id,nickname:r.nickname,czarDropped:r.czarDropped,masterDropped:r.masterDropped,gameOver:false,destroyed:r.destroyed,canRejoin:true});}}return events;}
function getPlayerList(room){const out=[];for(const[id,p]of room.players){if(p.active===false)continue;out.push({userId:p.userId,nickname:p.nickname,avatarData:p.avatarData||null,titleKey:p.titleKey||null,frameKey:p.frameKey||null,score:p.score,cardsReady:p.cardsReady,connected:p.connected,isCreator:id===room.creatorId});}return out;}
function getScoresForRoom(room){return activeEntries(room).map(([,p])=>({userId:p.userId,nickname:p.nickname,avatarData:p.avatarData||null,titleKey:p.titleKey||null,frameKey:p.frameKey||null,score:p.score})).sort((a,b)=>b.score-a.score);}
module.exports={createRoom,joinRoom,updateRoomConfig,submitCards,startGame,playCard,pickWinner,nextRound,removePlayer,sweepPresence,getPlayerList,getScoresForRoom,calculateRanking,HAND_SIZE,activeEntries,activeCount};
