'use strict';
const{sql}=require('./db');
const cleanCards=require('./cleanCards');
const BEST_WORLD_RANK_VERSION='best-world-v1';
const RETRYABLE=new Set(['40001','23505']);
const uid=x=>Number(x)||0;
const pid=x=>String(x||'').trim();

async function balances(userId){await cleanCards.ensureStarterCleanCards(userId);await sql`INSERT INTO dirty_coin_wallets(user_id,balance) VALUES(${uid(userId)},0) ON CONFLICT(user_id) DO NOTHING`;const[d,c]=await Promise.all([sql`SELECT balance FROM dirty_coin_wallets WHERE user_id=${uid(userId)}`,sql`SELECT white_balance,black_balance FROM clean_card_wallets WHERE user_id=${uid(userId)}`]);return{dirtyBalance:Number(d[0]?.balance||0),whiteBalance:Number(c[0]?.white_balance||0),blackBalance:Number(c[0]?.black_balance||0)};}
async function getProduct(key){return(await sql`SELECT product_key,name,description,category,product_kind,price,config,catalog_version,enabled,sort_order FROM market_catalog WHERE product_key=${String(key||'')} LIMIT 1`)[0]||null;}
async function getPurchase(userId,purchaseId){return(await sql`SELECT * FROM market_purchases WHERE user_id=${uid(userId)} AND purchase_id=${pid(purchaseId)} LIMIT 1`)[0]||null;}
async function availablePackCards(userId){return Number((await sql`SELECT COUNT(*)::int n FROM canonical_cards cc WHERE NOT EXISTS(SELECT 1 FROM canonical_card_ownerships o WHERE o.user_id=${uid(userId)} AND o.canonical_card_id=cc.id)`)[0]?.n||0);}
function shapePurchase(row,b,replayed=false){return{status:'ok',replayed,purchasePk:row.id,productKey:row.product_key,price:Number(row.price_paid||0),itemCount:Number(row.item_count||0),grants:Array.isArray(row.grants)?row.grants:[],...b};}

async function reserveQuery(userId,productKey,purchaseId,category,poolRule='none'){
 const poolCondition=poolRule==='random'?sql`AND EXISTS(SELECT 1 FROM canonical_cards cc WHERE NOT EXISTS(SELECT 1 FROM canonical_card_ownerships o WHERE o.user_id=${uid(userId)} AND o.canonical_card_id=cc.id))`:poolRule==='best'?sql`AND (SELECT COUNT(*) FROM canonical_cards cc WHERE NOT EXISTS(SELECT 1 FROM canonical_card_ownerships o WHERE o.user_id=${uid(userId)} AND o.canonical_card_id=cc.id))>=COALESCE((c.config->>'quantity')::int,3)`:sql``;
 return sql`INSERT INTO market_purchases(user_id,purchase_id,product_key,product_name,price_paid,catalog_version,product_config)
 SELECT ${uid(userId)},${pid(purchaseId)},c.product_key,c.name,c.price,c.catalog_version,c.config FROM market_catalog c JOIN dirty_coin_wallets w ON w.user_id=${uid(userId)}
 WHERE c.product_key=${productKey} AND c.enabled=true AND c.category=${category} AND w.balance>=c.price ${poolCondition} RETURNING id`;
}
function chargeQueries(userId,purchaseId){return[
 sql`UPDATE dirty_coin_wallets w SET balance=w.balance-mp.price_paid,updated_at=now() FROM market_purchases mp WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)} AND w.user_id=mp.user_id RETURNING w.balance`,
 sql`INSERT INTO dirty_coin_ledger(user_id,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) SELECT mp.user_id,-mp.price_paid,'marketplace_purchase',${`purchase:market:${uid(userId)}:${pid(purchaseId)}`},'market_product',mp.product_key,jsonb_build_object('catalogVersion',mp.catalog_version,'productName',mp.product_name) FROM market_purchases mp WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`
 ];}
async function runClean(userId,product,purchaseId){const reserve=await reserveQuery(userId,product.product_key,purchaseId,'clean_cards');const q=[reserve,...chargeQueries(userId,purchaseId),
 sql`UPDATE clean_card_wallets cw SET white_balance=cw.white_balance+COALESCE((mp.product_config->>'white')::int,0),black_balance=cw.black_balance+COALESCE((mp.product_config->>'black')::int,0),updated_at=now() FROM market_purchases mp WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)} AND cw.user_id=mp.user_id`,
 sql`INSERT INTO clean_card_ledger(user_id,card_type,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) SELECT mp.user_id,'white',(mp.product_config->>'white')::int,'purchase',${`purchase:market:${uid(userId)}:${pid(purchaseId)}:white`},'market_purchase',mp.id::text,jsonb_build_object('productKey',mp.product_key) FROM market_purchases mp WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)} AND COALESCE((mp.product_config->>'white')::int,0)>0`,
 sql`INSERT INTO clean_card_ledger(user_id,card_type,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) SELECT mp.user_id,'black',(mp.product_config->>'black')::int,'purchase',${`purchase:market:${uid(userId)}:${pid(purchaseId)}:black`},'market_purchase',mp.id::text,jsonb_build_object('productKey',mp.product_key) FROM market_purchases mp WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)} AND COALESCE((mp.product_config->>'black')::int,0)>0`,
 sql`UPDATE market_purchases mp SET item_count=COALESCE((mp.product_config->>'white')::int,0)+COALESCE((mp.product_config->>'black')::int,0),grants=jsonb_build_array(jsonb_build_object('kind','clean_cards','white',COALESCE((mp.product_config->>'white')::int,0),'black',COALESCE((mp.product_config->>'black')::int,0))) WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`,
 sql`SELECT mp.*,w.balance dirty_balance,cw.white_balance,cw.black_balance FROM market_purchases mp JOIN dirty_coin_wallets w ON w.user_id=mp.user_id JOIN clean_card_wallets cw ON cw.user_id=mp.user_id WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`];return sql.transaction(q,{isolationMode:'Serializable'});}

function packGrantQuery(userId,purchaseId,kind){const source=kind==='pack_best_world'?'pack_best_world':'pack_random';const order=kind==='pack_best_world'?sql`ORDER BY (2.0*ln(1+COALESCE(ev.wins,0))+CASE WHEN cc.card_type='white' AND COALESCE(ev.uses,0)>=5 THEN 3.0*(ev.wins::numeric/ev.uses) ELSE 0 END+1.3*ln(1+COALESCE(pr.presence,0))+1.5*ln(1+COALESCE(ad.adoptions,0))+1.1*ln(1+COALESCE(ow.reach,0))+0.5*ln(1+GREATEST(0,EXTRACT(EPOCH FROM(now()-cc.created_at))/2592000.0))) DESC,cc.id`:sql`ORDER BY random()`;
 return sql`WITH mp AS(SELECT * FROM market_purchases WHERE user_id=${uid(userId)} AND purchase_id=${pid(purchaseId)}),candidates AS MATERIALIZED(
 SELECT cc.id,cc.card_type,cc.display_text FROM canonical_cards cc
 LEFT JOIN LATERAL(SELECT COUNT(*) FILTER(WHERE e.event_type='white_win')::int wins,COUNT(*) FILTER(WHERE e.event_type IN('white_revealed','black_used'))::int uses FROM canonical_card_round_events e WHERE e.canonical_card_id=cc.id)ev ON true
 LEFT JOIN LATERAL(SELECT COUNT(*)::int presence FROM canonical_card_match_presence m WHERE m.canonical_card_id=cc.id)pr ON true
 LEFT JOIN LATERAL(SELECT COUNT(DISTINCT o.user_id)::int adoptions FROM canonical_card_ownerships o WHERE o.canonical_card_id=cc.id AND o.acquisition_source='match_loot')ad ON true
 LEFT JOIN LATERAL(SELECT COUNT(DISTINCT o.user_id)::int reach FROM canonical_card_ownerships o WHERE o.canonical_card_id=cc.id)ow ON true,mp
 WHERE NOT EXISTS(SELECT 1 FROM canonical_card_ownerships o WHERE o.user_id=${uid(userId)} AND o.canonical_card_id=cc.id) ${order} LIMIT COALESCE((mp.product_config->>'quantity')::int,0)
 ),legacy AS(INSERT INTO user_cards(user_id,type,text,owned,is_player_card) SELECT ${uid(userId)},CASE WHEN c.card_type='white' THEN 'whiteCards' ELSE 'blackCards' END,c.display_text,true,true FROM candidates c ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,is_player_card=true,updated_at=now() RETURNING id,type,text),owned AS(
 INSERT INTO canonical_card_ownerships(user_id,canonical_card_id,legacy_user_card_id,acquisition_source) SELECT ${uid(userId)},c.id,l.id,${source} FROM candidates c JOIN legacy l ON l.type=CASE WHEN c.card_type='white' THEN 'whiteCards' ELSE 'blackCards' END AND l.text=c.display_text RETURNING canonical_card_id
 ),numbered AS(SELECT canonical_card_id,row_number() OVER(ORDER BY canonical_card_id)::int ordinal FROM owned)
 INSERT INTO market_purchase_card_grants(purchase_pk,canonical_card_id,acquisition_source,ordinal) SELECT mp.id,n.canonical_card_id,${source},n.ordinal FROM numbered n,mp RETURNING canonical_card_id`;
}
async function runPack(userId,product,purchaseId){const rule=product.product_kind==='pack_best_world'?'best':'random',reserve=await reserveQuery(userId,product.product_key,purchaseId,'card_pack',rule),source=product.product_kind==='pack_best_world'?'pack_best_world':'pack_random';const q=[reserve,...chargeQueries(userId,purchaseId),packGrantQuery(userId,purchaseId,product.product_kind),
 sql`UPDATE market_purchases mp SET item_count=x.n,grants=x.grants FROM(SELECT g.purchase_pk,COUNT(*)::int n,COALESCE(jsonb_agg(jsonb_build_object('kind','player_card','canonicalCardId',cc.id,'type',cc.card_type,'text',cc.display_text,'acquisitionSource',g.acquisition_source) ORDER BY g.ordinal),'[]'::jsonb) grants FROM market_purchase_card_grants g JOIN canonical_cards cc ON cc.id=g.canonical_card_id GROUP BY g.purchase_pk)x WHERE mp.id=x.purchase_pk AND mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`,
 sql`SELECT mp.*,w.balance dirty_balance,cw.white_balance,cw.black_balance FROM market_purchases mp JOIN dirty_coin_wallets w ON w.user_id=mp.user_id JOIN clean_card_wallets cw ON cw.user_id=mp.user_id WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`];const out=await sql.transaction(q,{isolationMode:'Serializable'}),final=out[out.length-1]?.[0];if(final&&source==='pack_best_world'&&Number(final.item_count)!==Number(product.config?.quantity||3))throw Object.assign(new Error('premium_pack_incomplete'),{code:'P05PREMIUM'});return out;}

async function purchase(userId,productKey,purchaseId){const id=uid(userId),key=String(productKey||''),purchaseKey=pid(purchaseId);if(!id)return{status:'invalid_user'};if(purchaseKey.length<8)return{status:'invalid_idempotency_key'};await balances(id);let old=await getPurchase(id,purchaseKey);if(old)return shapePurchase(old,await balances(id),true);const product=await getProduct(key);if(!product||!product.enabled)return{status:'invalid_product'};
 for(let attempt=0;attempt<3;attempt++)try{const out=product.category==='clean_cards'?await runClean(id,product,purchaseKey):await runPack(id,product,purchaseKey),final=out[out.length-1]?.[0];if(final)return shapePurchase(final,{dirtyBalance:Number(final.dirty_balance||0),whiteBalance:Number(final.white_balance||0),blackBalance:Number(final.black_balance||0)},false);break;}catch(e){old=await getPurchase(id,purchaseKey);if(old)return shapePurchase(old,await balances(id),true);if((RETRYABLE.has(String(e.code))||e.code==='P05PREMIUM')&&attempt<2)continue;throw e;}
 const b=await balances(id);if(b.dirtyBalance<Number(product.price))return{status:'insufficient_dirty_coins',price:Number(product.price),...b};if(product.category==='card_pack'){const available=await availablePackCards(id),required=Number(product.config?.quantity||0);if(product.product_kind==='pack_random'&&available===0)return{status:'empty_pool',available,...b};if(product.product_kind==='pack_best_world'&&available<required)return{status:'insufficient_pool',available,required,...b};}return{status:'unavailable',...b};}

async function getState(userId){const id=uid(userId),b=await balances(id);const[catalog,purchases,packCards,ledger]=await Promise.all([
 sql`SELECT product_key,name,description,category,product_kind,price,config,catalog_version,sort_order FROM market_catalog WHERE enabled=true ORDER BY sort_order,product_key`,
 sql`SELECT id,purchase_id,product_key,product_name,price_paid,catalog_version,item_count,grants,created_at FROM market_purchases WHERE user_id=${id} ORDER BY created_at DESC,id DESC LIMIT 30`,
 sql`SELECT cc.id canonical_card_id,cc.card_type,cc.display_text,o.acquisition_source,o.acquired_at,COALESCE((SELECT json_agg(COALESCE(u.display_name,a.author_name_snapshot,u.username,'Criador desconhecido') ORDER BY a.authored_at,a.user_id) FROM canonical_card_authors a LEFT JOIN users u ON u.id=a.user_id WHERE a.canonical_card_id=cc.id),'[]'::json) authors FROM canonical_card_ownerships o JOIN canonical_cards cc ON cc.id=o.canonical_card_id WHERE o.user_id=${id} AND o.acquisition_source IN('pack_random','pack_best_world') ORDER BY o.acquired_at DESC LIMIT 50`,
 sql`SELECT amount,transaction_type,reference_type,reference_id,metadata,created_at FROM dirty_coin_ledger WHERE user_id=${id} ORDER BY created_at DESC,id DESC LIMIT 50`]);return{catalog,purchases,packCards,ledger,...b,rankVersion:BEST_WORLD_RANK_VERSION};}
module.exports={BEST_WORLD_RANK_VERSION,getState,purchase,availablePackCards};
