'use strict';
const{sql}=require('./db');
const cleanCards=require('./cleanCards');
const uid=x=>Number(x)||0,pid=x=>String(x||'').trim();
async function balances(userId){const id=uid(userId);await cleanCards.ensureStarterCleanCards(id);await sql`INSERT INTO dirty_coin_wallets(user_id,balance) VALUES(${id},0) ON CONFLICT(user_id) DO NOTHING`;const[d,c]=await Promise.all([sql`SELECT balance FROM dirty_coin_wallets WHERE user_id=${id}`,sql`SELECT white_balance,black_balance FROM clean_card_wallets WHERE user_id=${id}`]);return{dirtyBalance:Number(d[0]?.balance||0),whiteBalance:Number(c[0]?.white_balance||0),blackBalance:Number(c[0]?.black_balance||0)};}
async function getProduct(key){return(await sql`SELECT product_key,name,description,category,product_kind,price,config,catalog_version,enabled,sort_order FROM market_catalog WHERE product_key=${String(key||'')} LIMIT 1`)[0]||null;}
async function getPurchase(userId,purchaseId){return(await sql`SELECT * FROM market_purchases WHERE user_id=${uid(userId)} AND purchase_id=${pid(purchaseId)} LIMIT 1`)[0]||null;}
async function availablePackCards(userId){return Number((await sql`SELECT COUNT(*)::int n FROM canonical_cards cc WHERE NOT EXISTS(SELECT 1 FROM canonical_card_ownerships o WHERE o.user_id=${uid(userId)} AND o.canonical_card_id=cc.id)`)[0]?.n||0);}
function shapePurchase(row,b,replayed=false){return{status:'ok',replayed,purchasePk:row.id,productKey:row.product_key,price:Number(row.price_paid||0),itemCount:Number(row.item_count||0),grants:Array.isArray(row.grants)?row.grants:[],...b};}
function walletLock(userId){return sql`SELECT user_id,balance FROM dirty_coin_wallets WHERE user_id=${uid(userId)} FOR UPDATE`;}
function chargeQueries(userId,purchaseId){const id=uid(userId),p=pid(purchaseId);return[sql`UPDATE dirty_coin_wallets w SET balance=w.balance-mp.price_paid,updated_at=now() FROM market_purchases mp WHERE mp.user_id=${id} AND mp.purchase_id=${p} AND w.user_id=mp.user_id RETURNING w.balance`,sql`INSERT INTO dirty_coin_ledger(user_id,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) SELECT mp.user_id,-mp.price_paid,'marketplace_purchase',${`purchase:market:${id}:${p}`},'market_product',mp.product_key,jsonb_build_object('catalogVersion',mp.catalog_version,'productName',mp.product_name) FROM market_purchases mp WHERE mp.user_id=${id} AND mp.purchase_id=${p}`];}
function finalQuery(userId,purchaseId){return sql`SELECT mp.*,w.balance dirty_balance,cw.white_balance,cw.black_balance FROM market_purchases mp JOIN dirty_coin_wallets w ON w.user_id=mp.user_id JOIN clean_card_wallets cw ON cw.user_id=mp.user_id WHERE mp.user_id=${uid(userId)} AND mp.purchase_id=${pid(purchaseId)}`;}
module.exports={sql,uid,pid,balances,getProduct,getPurchase,availablePackCards,shapePurchase,walletLock,chargeQueries,finalQuery};
