const crypto=require('crypto');
const{sql}=require('./db');
const{cardMaterialTier}=require('./auth');

const RARITIES={common:{label:'Comum',color:'#f4f4f5',order:1},rare:{label:'Raro',color:'#22c55e',order:2},superrare:{label:'Super Raro',color:'#3b82f6',order:3},epic:{label:'Épico',color:'#a855f7',order:4},legendary:{label:'Lendário',color:'#facc15',order:5}};
const TITLES=[
 {key:'ta-so-comecando',name:'Tô Só Começando',icon:'🎴',rarity:'common',description:'Conclua sua primeira partida.',metric:'matches',target:1},
 {key:'rindo-de-nervoso',name:'Rindo de Nervoso',icon:'😅',rarity:'common',description:'Ganhe sua primeira rodada.',metric:'rounds_won',target:1},
 {key:'mao-leve',name:'Mão Leve',icon:'🖐️',rarity:'common',description:'Use 25 cartas em partidas.',metric:'card_uses',target:25},
 {key:'fede-nem-cheira',name:'Fede, nem cheira',icon:'😶',rarity:'rare',description:'Em 15 partidas, termine sem ficar nem em primeiro nem em último.',metric:'middle_finishes',target:15},
 {key:'filho-da-mae',name:'Filho da Mãe',icon:'🫢',rarity:'rare',description:"Use uma carta contendo 'sua mãe' mais de 50 vezes.",metric:'sua_mae_uses',target:51},
 {key:'rei-do-ctrl-c',name:'Rei do Ctrl+C',icon:'📋',rarity:'rare',description:'Tenha suas cartas recriadas 20 vezes por outros jogadores.',metric:'recreated_received',target:20},
 {key:'sem-freio',name:'Sem Freio',icon:'😂',rarity:'rare',description:'Envie 50 reações durante partidas.',metric:'reactions',target:50},
 {key:'mestre-da-piada',name:'Mestre da Piada',icon:'👑',rarity:'superrare',description:'Ganhe 10 partidas seguidas.',metric:'max_win_streak',target:10},
 {key:'sem-amigos',name:'Sem Amigos',icon:'💀',rarity:'superrare',description:'Perca 10 partidas seguidas.',metric:'max_loss_streak',target:10},
 {key:'inimigo-da-familia',name:'Inimigo da Família',icon:'🏚️',rarity:'superrare',description:'Ganhe 5 rodadas seguidas em 3 partidas diferentes.',metric:'five_round_streak_matches',target:3},
 {key:'galanteador-nato',name:'Galanteador(a) Nato(a)',icon:'🌹',rarity:'superrare',description:'Seja escolhido 20 vezes pelo mesmo Mestre em partidas diferentes.',metric:'same_chooser_match_votes',target:20},
 {key:'safado-mor',name:'Safado(a) Mór',icon:'😈',rarity:'superrare',description:'Saia invicto de uma partida: vença todas as rodadas em que respondeu, com pelo menos 3 vitórias.',metric:'invincible_matches',target:1},
 {key:'meme-ambulante',name:'Meme Ambulante',icon:'🤡',rarity:'superrare',description:'Envie 150 reações.',metric:'reactions',target:150},
 {key:'dono-da-mesa',name:'Dono da Mesa',icon:'🪑',rarity:'epic',description:'Vença 25 partidas.',metric:'matches_won',target:25},
 {key:'necromante-da-piada',name:'Necromante da Piada',icon:'🧙',rarity:'epic',description:'Tenha 3 cartas Platinum.',metric:'platinum_cards',target:3},
 {key:'colecionador-compulsivo',name:'Colecionador Compulsivo',icon:'🃏',rarity:'epic',description:'Tenha 250 Cartas de Jogador.',metric:'player_cards',target:250},
 {key:'carreira-solo',name:'Carreira Solo',icon:'🎭',rarity:'epic',description:'Vença partidas usando pelo menos 5 apelidos diferentes.',metric:'winning_aliases',target:5},
 {key:'deja-vu',name:'Déjà Vu',icon:'🔁',rarity:'epic',description:'Vença 20 rodadas com a mesma carta.',metric:'same_card_wins',target:20},
 {key:'imortal-do-cartaralho',name:'Imortal do Cartaralho',icon:'🏛️',rarity:'legendary',description:'Jogue 250 partidas e vença pelo menos 100.',metric:'legend_progress',target:250},
 {key:'lenda-urbana',name:'Lenda Urbana',icon:'💎',rarity:'legendary',description:'Tenha 10 cartas Platinum.',metric:'platinum_cards',target:10},
 {key:'a-piada-e-minha',name:'A Piada É Minha',icon:'©️',rarity:'legendary',description:'Uma carta criada por você precisa visitar 100 mesas diferentes.',metric:'creator_card_rooms',target:100},
 {key:'contra-tudo-e-todos',name:'Contra Tudo e Todos',icon:'⚔️',rarity:'legendary',description:'Ganhe 20 partidas seguidas.',metric:'max_win_streak',target:20},
 {key:'o-escolhido',name:'O Escolhido',icon:'✨',rarity:'legendary',description:'Seja escolhido pelo mesmo Mestre em 50 partidas diferentes.',metric:'same_chooser_match_votes',target:50}
];
const FRAME_DEFS=[
 {key:'bronze',name:'Bronze',rarity:'rare',tier:'copper',target:5,description:'Tenha 5 cartas Copper/Bronze no seu baralho.'},
 {key:'silver',name:'Silver',rarity:'superrare',tier:'silver',target:5,description:'Tenha 5 cartas Silver no seu baralho.'},
 {key:'gold',name:'Gold',rarity:'epic',tier:'gold',target:5,description:'Tenha 5 cartas Gold no seu baralho.'},
 {key:'platinum',name:'Platinum',rarity:'legendary',tier:'platinum',target:5,description:'Tenha 5 cartas Platinum no seu baralho.'}
];
function normCard(text){return String(text||'').normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();}
function maxStreak(history,wantWin){let max=0,cur=0;for(const h of [...history].reverse()){if(!!h.won_match===wantWin){cur++;max=Math.max(max,cur);}else cur=0;}return max;}
async function getMetrics(userId){
 const totals=(await sql`SELECT COUNT(*)::int matches,COALESCE(SUM(rounds_won),0)::int rounds_won,COALESCE(SUM(CASE WHEN won_match THEN 1 ELSE 0 END),0)::int matches_won,COALESCE(SUM(final_score),0)::int total_points,COALESCE(SUM(CASE WHEN final_position>1 AND final_position<total_players THEN 1 ELSE 0 END),0)::int middle_finishes,COUNT(DISTINCT CASE WHEN won_match THEN nickname END)::int winning_aliases FROM match_players WHERE user_id=${userId}`)[0]||{};
 const history=await sql`SELECT room_code,won_match,final_position,total_players,nickname,finished_at FROM match_players WHERE user_id=${userId} ORDER BY finished_at ASC`;
 const cardRows=await sql`SELECT matches_used,is_player_card,owned,times_used,duplicate_creation_count,text FROM user_cards WHERE user_id=${userId}`;
 const tierCounts={copper:0,silver:0,gold:0,platinum:0};let playerCards=0,cardUses=0,recreated=0,suaMaeUses=0;
 for(const c of cardRows){const tier=cardMaterialTier(c.matches_used);if(tierCounts[tier]!==undefined&&c.owned)tierCounts[tier]++;if(c.is_player_card&&c.owned)playerCards++;cardUses+=Number(c.times_used||0);recreated+=Number(c.duplicate_creation_count||0);if(normCard(c.text).includes('sua mãe'))suaMaeUses+=Number(c.times_used||0);}
 const reactions=Number((await sql`SELECT COUNT(*)::int n FROM user_reactions WHERE user_id=${userId}`)[0]?.n||0);
 const pair=Number((await sql`SELECT COALESCE(MAX(n),0)::int n FROM (SELECT chooser_user_id,COUNT(DISTINCT room_code)::int n FROM round_votes WHERE winner_user_id=${userId} AND chooser_user_id IS NOT NULL GROUP BY chooser_user_id) q`)[0]?.n||0);
 const sameCardWins=Number((await sql`SELECT COALESCE(MAX(n),0)::int n FROM (SELECT lower(winner_card) k,COUNT(*)::int n FROM match_rounds WHERE winner_user_id=${userId} AND winner_card IS NOT NULL GROUP BY lower(winner_card)) q`)[0]?.n||0);
 const creatorRooms=Number((await sql`SELECT COALESCE(MAX(n),0)::int n FROM (SELECT co.id,COUNT(DISTINCT crp.room_code)::int n FROM card_origins co LEFT JOIN card_room_presence crp ON crp.type=co.type AND crp.text_key=co.text_key WHERE co.creator_user_id=${userId} GROUP BY co.id) q`)[0]?.n||0);
 const rounds=await sql`SELECT room_code,round_number,winner_user_id,submissions FROM match_rounds WHERE winner_user_id=${userId} OR submissions @> ${JSON.stringify([{userId:Number(userId)}])}::jsonb ORDER BY room_code,round_number`;
 const byRoom=new Map();for(const r of rounds){if(!byRoom.has(r.room_code))byRoom.set(r.room_code,[]);byRoom.get(r.room_code).push(r);}
 let fiveRoundStreakMatches=0,invincibleMatches=0;
 for(const rows of byRoom.values()){let streak=0,max=0,participated=0,wins=0;for(const r of rows){const subs=Array.isArray(r.submissions)?r.submissions:[];const did=subs.some(s=>String(s.userId)===String(userId));if(did){participated++;if(String(r.winner_user_id)===String(userId)){wins++;streak++;max=Math.max(max,streak);}else streak=0;}}if(max>=5)fiveRoundStreakMatches++;if(participated>=3&&wins===participated)invincibleMatches++;}
 return{...totals,player_cards:playerCards,card_uses:cardUses,recreated_received:recreated,sua_mae_uses:suaMaeUses,reactions,max_win_streak:maxStreak(history,true),max_loss_streak:maxStreak(history,false),five_round_streak_matches:fiveRoundStreakMatches,same_chooser_match_votes:pair,invincible_matches:invincibleMatches,winning_aliases:Number(totals.winning_aliases||0),same_card_wins:sameCardWins,creator_card_rooms:creatorRooms,platinum_cards:tierCounts.platinum,gold_cards:tierCounts.gold,silver_cards:tierCounts.silver,copper_cards:tierCounts.copper,legend_progress:(Number(totals.matches_won||0)>=100?Number(totals.matches||0):Math.min(Number(totals.matches||0),249)),tierCounts};
}
function buildTitles(metrics){return TITLES.map(t=>{const p=Number(metrics[t.metric]||0);return{...t,rarityInfo:RARITIES[t.rarity],progress:Math.min(p,t.target),rawProgress:p,unlocked:p>=t.target};});}
async function frameStatus(userId,metrics){const seasonal=await sql`SELECT sh.position,s.name FROM season_hall_of_fame sh JOIN seasons s ON s.id=sh.season_id WHERE sh.user_id=${userId} ORDER BY sh.awarded_at DESC`;const frames=FRAME_DEFS.map(f=>({...f,rarityInfo:RARITIES[f.rarity],progress:metrics.tierCounts[f.tier]||0,unlocked:(metrics.tierCounts[f.tier]||0)>=f.target}));for(const h of seasonal){const map={1:['season-champion','Campeão de Temporada','legendary','👑'],2:['season-runner-up','Vice de Temporada','epic','🥈'],3:['season-third','Pódio de Temporada','superrare','🥉']},m=map[h.position];if(m&&!frames.some(f=>f.key===m[0]))frames.push({key:m[0],name:m[1],rarity:m[2],rarityInfo:RARITIES[m[2]],icon:m[3],description:`Conquistada no Hall da Fama — ${h.name}.`,progress:1,target:1,unlocked:true});}return frames;}
async function syncUnlocks(userId){const metrics=await getMetrics(userId),titles=buildTitles(metrics),frames=await frameStatus(userId,metrics);for(const t of titles.filter(x=>x.unlocked)){await sql`INSERT INTO user_unlocks(user_id,unlock_type,unlock_key) VALUES(${userId},'badge',${t.key}) ON CONFLICT DO NOTHING`;await sql`INSERT INTO user_unlocks(user_id,unlock_type,unlock_key) VALUES(${userId},'title',${t.key}) ON CONFLICT DO NOTHING`;}for(const f of frames.filter(x=>x.unlocked))await sql`INSERT INTO user_unlocks(user_id,unlock_type,unlock_key) VALUES(${userId},'frame',${f.key}) ON CONFLICT DO NOTHING`;return{metrics,titles,frames};}
async function equip(userId,titleKey,frameKey){const state=await syncUnlocks(userId);if(titleKey){const ok=state.titles.some(t=>t.key===titleKey&&t.unlocked);if(!ok)throw new Error('Título ainda não desbloqueado.');}if(frameKey){const ok=state.frames.some(f=>f.key===frameKey&&f.unlocked);if(!ok)throw new Error('Moldura ainda não desbloqueada.');}await sql`UPDATE users SET equipped_title_key=${titleKey||null},equipped_frame_key=${frameKey||null} WHERE id=${userId}`;return{titleKey:titleKey||null,frameKey:frameKey||null};}
function monthName(key){const[,m]=String(key).split('-');return['','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][Number(m)]||m;}
async function finalizeSeason(season){if(!season||season.finalized_at)return;const rank=await sql`SELECT user_id,COALESCE(SUM(final_score),0)::int points,COALESCE(SUM(CASE WHEN won_match THEN 1 ELSE 0 END),0)::int wins,COUNT(*)::int matches FROM match_players WHERE season_id=${season.id} AND user_id IS NOT NULL GROUP BY user_id ORDER BY points DESC,wins DESC,matches ASC LIMIT 3`;for(let i=0;i<rank.length;i++){const r=rank[i];await sql`INSERT INTO season_hall_of_fame(season_id,user_id,position,points,wins,matches) VALUES(${season.id},${r.user_id},${i+1},${r.points},${r.wins},${r.matches}) ON CONFLICT DO NOTHING`;}await sql`UPDATE seasons SET is_active=false,finalized_at=now(),ends_at=COALESCE(ends_at,now()) WHERE id=${season.id}`;}
async function ensureMonthlySeason(){const info=(await sql`SELECT to_char(now() AT TIME ZONE 'America/Sao_Paulo','YYYY-MM') key,(date_trunc('month',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo') starts,((date_trunc('month',now() AT TIME ZONE 'America/Sao_Paulo')+interval '1 month') AT TIME ZONE 'America/Sao_Paulo') ends`)[0];let current=(await sql`SELECT * FROM seasons WHERE season_key=${info.key} LIMIT 1`)[0];const active=await sql`SELECT * FROM seasons WHERE is_active=true AND (season_key IS DISTINCT FROM ${info.key})`;for(const s of active)await finalizeSeason(s);if(!current){const year=String(info.key).slice(0,4),name=`Temporada ${monthName(info.key)} ${year}`;await sql`INSERT INTO seasons(name,season_key,starts_at,ends_at,is_active) VALUES(${name},${info.key},${info.starts},${info.ends},true) ON CONFLICT DO NOTHING`;current=(await sql`SELECT * FROM seasons WHERE season_key=${info.key} LIMIT 1`)[0];}if(current&&!current.is_active)await sql`UPDATE seasons SET is_active=true WHERE id=${current.id}`;return current;}
const DAILY=[{key:'d-play',name:'Bater ponto',description:'Jogue 1 partida hoje.',target:1,xp:100,metric:'matches'},{key:'d-rounds',name:'Arranca risada',description:'Ganhe 3 rodadas hoje.',target:3,xp:150,metric:'rounds'},{key:'d-react',name:'Plateia barulhenta',description:'Envie 5 reações hoje.',target:5,xp:75,metric:'reactions'}];
const WEEKLY=[{key:'w-play',name:'Sem vida social',description:'Jogue 5 partidas nesta semana.',target:5,xp:350,metric:'matches'},{key:'w-win',name:'Dono do rolê',description:'Vença 2 partidas nesta semana.',target:2,xp:500,metric:'wins'},{key:'w-rounds',name:'Metralhadora de piada',description:'Ganhe 10 rodadas nesta semana.',target:10,xp:450,metric:'rounds'},{key:'w-react',name:'Torcida organizada',description:'Envie 20 reações nesta semana.',target:20,xp:250,metric:'reactions'}];
async function missionPeriod(){return(await sql`SELECT to_char(now() AT TIME ZONE 'America/Sao_Paulo','YYYY-MM-DD') daily,to_char(date_trunc('week',now() AT TIME ZONE 'America/Sao_Paulo'),'IYYY-IW') weekly`)[0];}
async function missionProgress(userId,kind){const period=kind==='daily'?`date_trunc('day',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo'`:`date_trunc('week',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo'`;const p={};p.matches=Number((await sql.unsafe(`SELECT COUNT(*)::int n FROM match_players WHERE user_id=$1 AND finished_at>=${period}`,[userId]))[0]?.n||0);p.wins=Number((await sql.unsafe(`SELECT COUNT(*)::int n FROM match_players WHERE user_id=$1 AND won_match=true AND finished_at>=${period}`,[userId]))[0]?.n||0);p.rounds=Number((await sql.unsafe(`SELECT COUNT(*)::int n FROM match_rounds WHERE winner_user_id=$1 AND created_at>=${period}`,[userId]))[0]?.n||0);p.reactions=Number((await sql.unsafe(`SELECT COUNT(*)::int n FROM user_reactions WHERE user_id=$1 AND created_at>=${period}`,[userId]))[0]?.n||0);return p;}
async function syncMissions(userId){const period=await missionPeriod(),out=[];for(const[kind,defs]of [['daily',DAILY],['weekly',WEEKLY]]){const key=period[kind],progress=await missionProgress(userId,kind);for(const d of defs){const val=Math.min(Number(progress[d.metric]||0),d.target);let row=(await sql`SELECT completed FROM user_missions WHERE user_id=${userId} AND mission_key=${d.key} AND period_key=${key}`)[0];if(!row){await sql`INSERT INTO user_missions(user_id,mission_key,period_type,period_key,progress,target,xp_reward,completed) VALUES(${userId},${d.key},${kind},${key},${val},${d.target},${d.xp},false)`;row={completed:false};}if(!row.completed&&val>=d.target){await sql`UPDATE user_missions SET progress=${val},completed=true,completed_at=now(),updated_at=now() WHERE user_id=${userId} AND mission_key=${d.key} AND period_key=${key}`;await sql`UPDATE users SET xp=xp+${d.xp} WHERE id=${userId}`;row.completed=true;}else await sql`UPDATE user_missions SET progress=${val},updated_at=now() WHERE user_id=${userId} AND mission_key=${d.key} AND period_key=${key}`;out.push({...d,periodType:kind,periodKey:key,progress:val,completed:!!row.completed});}}
 const user=(await sql`SELECT xp FROM users WHERE id=${userId}`)[0];return{missions:out,xp:Number(user?.xp||0),level:Math.floor(Number(user?.xp||0)/1000)+1,nextLevelXp:(Math.floor(Number(user?.xp||0)/1000)+1)*1000};}
function inviteCode(){return crypto.randomBytes(4).toString('hex').toUpperCase();}
module.exports={RARITIES,TITLES,FRAME_DEFS,normCard,getMetrics,buildTitles,frameStatus,syncUnlocks,equip,ensureMonthlySeason,finalizeSeason,syncMissions,inviteCode};
