'use strict';
const crypto=require('crypto');
const{sql}=require('./db');
const{creditDirtyCoins}=require('./playerStats');
const achievementService=require('./achievementService');
const defs=require('./achievementDefinitions');
const LEGACY_WEEKLY_KEYS=new Set(['w-play','w-win','w-rounds','w-borrowed','w-react']);

async function periodInfo(){return(await sql`SELECT to_char(now() AT TIME ZONE 'America/Sao_Paulo','YYYY-MM-DD') daily,to_char(date_trunc('week',now() AT TIME ZONE 'America/Sao_Paulo'),'IYYY-IW') weekly,(date_trunc('day',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo') daily_start,(date_trunc('week',now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo') weekly_start`)[0];}
async function legacyProgress(userId,periodType,start){const id=Number(userId);const matches=Number((await sql`SELECT COUNT(*)::int n FROM match_players mp JOIN match_reward_settlements mrs ON mrs.room_code=mp.room_code AND mrs.valid_for_rewards=true WHERE mp.user_id=${id} AND mp.finished_at>=${start}`)[0]?.n||0),wins=Number((await sql`SELECT COUNT(*)::int n FROM match_players mp JOIN match_reward_settlements mrs ON mrs.room_code=mp.room_code AND mrs.valid_for_rewards=true WHERE mp.user_id=${id} AND mp.won_match=true AND mp.finished_at>=${start}`)[0]?.n||0),rounds=Number((await sql`SELECT COUNT(*)::int n FROM match_rounds mr JOIN match_reward_settlements mrs ON mrs.room_code=mr.room_code AND mrs.valid_for_rewards=true WHERE mr.winner_user_id=${id} AND mr.created_at>=${start}`)[0]?.n||0),reactions=Number((await sql`SELECT COUNT(*)::int n FROM user_reactions ur JOIN match_reward_settlements mrs ON mrs.room_code=ur.room_code AND mrs.valid_for_rewards=true WHERE ur.user_id=${id} AND ur.created_at>=${start}`)[0]?.n||0);let borrowedWins=0;if(periodType==='weekly')borrowedWins=Number((await sql`SELECT COUNT(*)::int n FROM canonical_card_round_events e JOIN match_reward_settlements mrs ON mrs.room_code=e.match_id AND mrs.valid_for_rewards=true WHERE e.event_type='white_win' AND e.source_user_id=${id} AND e.created_at>=${start} AND EXISTS(SELECT 1 FROM canonical_card_authors a WHERE a.canonical_card_id=e.canonical_card_id) AND NOT EXISTS(SELECT 1 FROM canonical_card_authors a WHERE a.canonical_card_id=e.canonical_card_id AND a.user_id=${id})`)[0]?.n||0);return{matches,wins,rounds,reactions,borrowedWins};}
function eventValue(metric,events){const rows=events.filter(e=>e.event_key===metric.eventKey);if(!metric.distinct)return rows.length;return new Set(rows.map(e=>e[metric.distinct]).filter(v=>v!==null&&v!==undefined&&String(v)!=='')).size;}
async function deterministicBuff(userId,periodKey,missionKey){const rows=await sql`SELECT product_key,name,price FROM market_catalog WHERE product_kind='buff_item' AND enabled=true AND price<=400 ORDER BY product_key`,allowed=rows.filter(x=>defs.BUFF_REWARD_POOL.includes(x.product_key));if(!allowed.length)return null;const hex=crypto.createHash('sha256').update(`${userId}:${periodKey}:${missionKey}:p10-v1`).digest('hex'),i=parseInt(hex.slice(0,8),16)%allowed.length;return allowed[i];}
async function grantMissionBuff(userId,missionKey,periodType,periodKey,buffKey){if(!buffKey)return null;const idem=`mission:${periodType}:${periodKey}:${missionKey}:buff:${userId}`;const rows=await sql`WITH led AS (INSERT INTO buff_inventory_ledger(user_id,buff_key,delta,transaction_type,idempotency_key,reference_type,reference_id,metadata) VALUES(${userId},${buffKey},1,'mission_reward',${idem},'mission',${`${periodType}:${periodKey}:${missionKey}`},jsonb_build_object('rewardVersion','p10-v1')) ON CONFLICT(idempotency_key) DO NOTHING RETURNING 1),up AS (INSERT INTO buff_inventory(user_id,buff_key,quantity) SELECT ${userId},${buffKey},1 FROM led ON CONFLICT(user_id,buff_key) DO UPDATE SET quantity=buff_inventory.quantity+1,updated_at=now() RETURNING quantity) SELECT quantity FROM up`;return rows[0]?{buffKey,quantity:Number(rows[0].quantity)}:null;}

async function syncMissions(userId){
 const id=Number(userId),p10=achievementService.enabled();if(p10)await achievementService.syncCanonicalEvents(id);const periods=await periodInfo(),weekEvents=p10?await sql`SELECT event_key,source_key,match_id,related_user_id,canonical_card_id,occurred_at FROM achievement_events WHERE user_id=${id} AND occurred_at>=${periods.weekly_start} ORDER BY occurred_at,id`:[],out=[];
 for(const[periodType,baseList]of[['daily',defs.DAILY],['weekly',defs.WEEKLY]]){const list=p10?baseList:baseList.filter(d=>d.metric.kind==='legacy'),periodKey=periods[periodType],start=periodType==='daily'?periods.daily_start:periods.weekly_start,legacy=await legacyProgress(id,periodType,start),events=periodType==='daily'?weekEvents.filter(e=>new Date(e.occurred_at)>=new Date(periods.daily_start)):weekEvents;
  for(const d of list){const raw=d.metric.kind==='legacy'?Number(legacy[d.metric.key]||0):eventValue(d.metric,events),value=Math.min(raw,d.target),coins=Math.round(d.xp*.20),existing=(await sql`SELECT buff_reward_key,completed,rewarded_at FROM user_missions WHERE user_id=${id} AND mission_key=${d.key} AND period_key=${periodKey} LIMIT 1`)[0],chosen=existing?.buff_reward_key?{product_key:existing.buff_reward_key}:d.randomBuff?await deterministicBuff(id,periodKey,d.key):null;
   await sql`INSERT INTO user_missions(user_id,mission_key,period_type,period_key,progress,target,xp_reward,coin_reward,buff_reward_key,reward_metadata) VALUES(${id},${d.key},${periodType},${periodKey},${value},${d.target},${d.xp},${coins},${chosen?.product_key||null},jsonb_build_object('rewardVersion','p10-v1')) ON CONFLICT(user_id,mission_key,period_key) DO UPDATE SET progress=CASE WHEN user_missions.completed THEN user_missions.progress ELSE EXCLUDED.progress END,target=EXCLUDED.target,xp_reward=EXCLUDED.xp_reward,coin_reward=EXCLUDED.coin_reward,buff_reward_key=COALESCE(user_missions.buff_reward_key,EXCLUDED.buff_reward_key),reward_metadata=user_missions.reward_metadata||EXCLUDED.reward_metadata,updated_at=now()`;
   if(value>=d.target){await sql`WITH claimed AS (UPDATE user_missions SET progress=${value},completed=true,completed_at=COALESCE(completed_at,now()),updated_at=now() WHERE user_id=${id} AND mission_key=${d.key} AND period_key=${periodKey} AND completed=false RETURNING xp_reward) UPDATE users SET xp=xp+COALESCE((SELECT xp_reward FROM claimed),0) WHERE id=${id} AND EXISTS(SELECT 1 FROM claimed)`;await creditDirtyCoins(id,coins,'mission_reward',`mission:${periodType}:${periodKey}:${d.key}:coins:${id}`,{referenceType:'mission',referenceId:`${periodType}:${periodKey}:${d.key}`,metadata:{xp:d.xp,rate:.20,rewardVersion:'p10-v1'}});const row=(await sql`SELECT buff_reward_key,rewarded_at FROM user_missions WHERE user_id=${id} AND mission_key=${d.key} AND period_key=${periodKey}`)[0];if(row?.buff_reward_key)await grantMissionBuff(id,d.key,periodType,periodKey,row.buff_reward_key);await sql`UPDATE user_missions SET rewarded_at=COALESCE(rewarded_at,now()) WHERE user_id=${id} AND mission_key=${d.key} AND period_key=${periodKey} AND completed=true`;}
   const row=(await sql`SELECT completed,buff_reward_key,rewarded_at FROM user_missions WHERE user_id=${id} AND mission_key=${d.key} AND period_key=${periodKey}`)[0]||{};let buffReward=null;if(row.buff_reward_key){const x=(await sql`SELECT name,price FROM market_catalog WHERE product_key=${row.buff_reward_key} LIMIT 1`)[0];buffReward={key:row.buff_reward_key,name:x?.name||row.buff_reward_key,price:Number(x?.price||0)};}out.push({...d,coins,periodType,periodKey,progress:value,rawProgress:raw,completed:!!row.completed,buffReward,rewarded:!!row.rewarded_at});
  }
 }
 const legacyWeekly=out.filter(m=>m.periodType==='weekly'&&LEGACY_WEEKLY_KEYS.has(m.key));if(legacyWeekly.length&&legacyWeekly.every(m=>m.completed))await sql`INSERT INTO user_unlocks(user_id,unlock_type,unlock_key) VALUES(${id},'frame','mission-weekly') ON CONFLICT DO NOTHING`;
 const u=(await sql`SELECT xp FROM users WHERE id=${id}`)[0]||{xp:0},xp=Number(u.xp||0),level=Math.floor(xp/1000)+1;if(xp>=10000)await sql`INSERT INTO user_unlocks(user_id,unlock_type,unlock_key) VALUES(${id},'frame','xp-10000') ON CONFLICT DO NOTHING`;return{missions:out,xp,level,currentLevelXp:xp%1000,nextLevelAt:level*1000};
}
module.exports={syncMissions,periodInfo,legacyProgress,deterministicBuff,grantMissionBuff};
