const{sql}=require('./db');const cardOrigins=require('./cardOrigins');const{ensureMonthlySeason}=require('./metaGame');
async function ensureOwnedCards(userId,type,texts){if(!userId)return;for(const raw of texts||[]){const text=String(raw||'').trim();if(!text)continue;await sql`INSERT INTO user_cards(user_id,type,text,owned,is_player_card) VALUES(${userId},${type},${text},true,true) ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,is_player_card=true,updated_at=now()`;}}
async function sharePlayerCards(room,type,texts){for(const p of room.players.values())if(p.userId&&p.active!==false)await ensureOwnedCards(p.userId,type,texts);}
async function registerSubmittedCards(room,player,type,allTexts,createdTexts){await cardOrigins.registerSubmitted(room,player,type,allTexts,createdTexts);}
async function markCreatedDuplicates(room,userId,type,texts){if(!userId)return;const others=Array.from(room.players.values()).filter(p=>p.active!==false).map(p=>p.userId).filter(id=>id&&String(id)!==String(userId));for(const raw of texts||[]){const text=String(raw||'').trim();if(!text)continue;await ensureOwnedCards(userId,type,[text]);for(const otherId of others)await sql`INSERT INTO user_cards(user_id,type,text,owned,is_player_card,duplicate_creation_count) VALUES(${otherId},${type},${text},true,true,1) ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,is_player_card=true,duplicate_creation_count=user_cards.duplicate_creation_count+1,updated_at=now()`;await cardOrigins.markRecreated(type,text,userId);}}
async function recordUse(roomCode,userId,type,text){if(!userId||!text)return;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_used) VALUES(${userId},${type},${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_used=user_cards.times_used+1,updated_at=now()`;const existing=await sql`SELECT used_count FROM card_match_usage WHERE room_code=${roomCode} AND user_id=${userId} AND type=${type} AND text=${text}`;await sql`INSERT INTO card_match_usage(room_code,user_id,type,text,used_count) VALUES(${roomCode},${userId},${type},${text},1) ON CONFLICT(room_code,user_id,type,text) DO UPDATE SET used_count=card_match_usage.used_count+1`;if(!existing.length)await sql`UPDATE user_cards SET matches_used=matches_used+1 WHERE user_id=${userId} AND type=${type} AND text=${text}`;}
async function recordSeen(room,type,text){if(!text)return;for(const p of room.players.values()){if(!p.userId||p.active===false)continue;const previous=await sql`SELECT seen_count FROM card_match_usage WHERE room_code=${room.code} AND user_id=${p.userId} AND type=${type} AND text=${text}`;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_seen) VALUES(${p.userId},${type},${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_seen=user_cards.times_seen+1,updated_at=now()`;await sql`INSERT INTO card_match_usage(room_code,user_id,type,text,seen_count) VALUES(${room.code},${p.userId},${type},${text},1) ON CONFLICT(room_code,user_id,type,text) DO UPDATE SET seen_count=card_match_usage.seen_count+1`;if(type==='blackCards'&&!previous.length)await sql`UPDATE user_cards SET matches_used=matches_used+1 WHERE user_id=${p.userId} AND type=${type} AND text=${text} AND owned=true`;}}
async function recordBlackWin(userId,text){if(!userId||!text)return;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_won) VALUES(${userId},'blackCards',${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_won=user_cards.times_won+1,updated_at=now()`;}
async function recordRoomCardVisits(room){await cardOrigins.visitRoom(room.code,'blackCards',room.blackDeck||[]);await cardOrigins.visitRoom(room.code,'whiteCards',room.whiteDeck||[]);}
async function recordRoundReplay(room){if(!room.currentRound)return;const r=room.currentRound,master=room.players.get(r.hostId),winner=room.players.get(r.winnerId),submissions=Array.from(r.submissions.entries()).map(([id,s])=>{const p=room.players.get(id);return{userId:p?.userId||Number(id)||null,nickname:p?.nickname||'Jogador',card:s.card};}),scores=Array.from(room.players.values()).map(p=>({userId:p.userId,nickname:p.nickname,score:p.score})).sort((a,b)=>b.score-a.score);await sql`INSERT INTO match_rounds(room_code,round_number,black_card,master_user_id,master_nickname,submissions,winner_user_id,winner_nickname,winner_card,scores) VALUES(${room.code},${r.number},${r.blackCard},${master?.userId||null},${master?.nickname||null},${JSON.stringify(submissions)},${winner?.userId||null},${winner?.nickname||null},${r.winnerCard||null},${JSON.stringify(scores)}) ON CONFLICT(room_code,round_number) DO UPDATE SET submissions=EXCLUDED.submissions,winner_user_id=EXCLUDED.winner_user_id,winner_nickname=EXCLUDED.winner_nickname,winner_card=EXCLUDED.winner_card,scores=EXCLUDED.scores`;if(master?.userId&&winner?.userId)await sql`INSERT INTO round_votes(room_code,round_number,chooser_user_id,winner_user_id) VALUES(${room.code},${r.number},${master.userId},${winner.userId}) ON CONFLICT DO NOTHING`;for(const s of submissions)await recordSeen(room,'whiteCards',s.card);}
async function getActiveSeasonId(){const season=await ensureMonthlySeason();return season?.id||null;}
async function finalizeMatch(room){const ranking=Array.from(room.players.entries()).map(([id,p])=>({userId:p.userId||Number(id)||null,nickname:p.nickname,avatarData:p.avatarData||null,score:p.score})).sort((a,b)=>b.score-a.score),top=ranking[0],seasonId=await getActiveSeasonId(),total=ranking.length;for(let i=0;i<ranking.length;i++){const row=ranking[i];if(!row.userId)continue;await sql`INSERT INTO match_players(room_code,user_id,nickname,avatar_data,final_score,rounds_won,won_match,season_id,final_position,total_players) VALUES(${room.code},${row.userId},${row.nickname},${row.avatarData},${row.score},${row.score},${!!top&&row.userId===top.userId},${seasonId},${i+1},${total}) ON CONFLICT(room_code,user_id) DO UPDATE SET nickname=EXCLUDED.nickname,avatar_data=EXCLUDED.avatar_data,final_score=EXCLUDED.final_score,rounds_won=EXCLUDED.rounds_won,won_match=EXCLUDED.won_match,season_id=EXCLUDED.season_id,final_position=EXCLUDED.final_position,total_players=EXCLUDED.total_players,finished_at=now()`;}return{ranking,seasonId};}
module.exports={ensureOwnedCards,sharePlayerCards,registerSubmittedCards,markCreatedDuplicates,recordUse,recordSeen,recordBlackWin,recordRoomCardVisits,recordRoundReplay,finalizeMatch,getActiveSeasonId};
