const{sql}=require('./db');
const cardOrigins=require('./cardOrigins');
const canonicalCards=require('./canonicalCards');
const{normalizeCardText}=require('./cardIdentity');
const{ensureMonthlySeason}=require('./metaGame');
const rewardRules=require('./rewardEngineRules');
const{REWARD_ENGINE_VERSION,clamp,effortIndex,rewardCurve,payoutForPosition}=rewardRules;

async function ensureWallet(userId){if(!userId)return null;await sql`INSERT INTO dirty_coin_wallets(user_id,balance) VALUES(${userId},0) ON CONFLICT(user_id) DO NOTHING`;return Number((await sql`SELECT balance FROM dirty_coin_wallets WHERE user_id=${userId}`)[0]?.balance||0);}
async function creditDirtyCoins(userId,amount,transactionType,idempotencyKey,{referenceType=null,referenceId=null,metadata={}}={}){const value=Math.max(0,Math.trunc(Number(amount)||0));if(!userId||!value)return{balance:await ensureWallet(userId),amount:0};await ensureWallet(userId);const rows=await sql`WITH ins AS (INSERT INTO dirty_coin_ledger(user_id,amount,transaction_type,idempotency_key,reference_type,reference_id,metadata) VALUES(${userId},${value},${transactionType},${idempotencyKey},${referenceType},${referenceId},${JSON.stringify(metadata)}::jsonb) ON CONFLICT(idempotency_key) DO NOTHING RETURNING amount) UPDATE dirty_coin_wallets SET balance=balance+COALESCE((SELECT SUM(amount) FROM ins),0),updated_at=now() WHERE user_id=${userId} RETURNING balance`;return{balance:Number(rows[0]?.balance||0),amount:value};}
async function ensureStarterCoins(userId){return creditDirtyCoins(userId,5000,'starter_grant',`starter:coins:${userId}`,{referenceType:'user',referenceId:String(userId),metadata:{grantVersion:'v1'}});}
async function getEconomy(userId,limit=20){await ensureWallet(userId);const wallet=(await sql`SELECT balance,updated_at FROM dirty_coin_wallets WHERE user_id=${userId}`)[0]||{balance:0},ledger=await sql`SELECT amount,transaction_type,reference_type,reference_id,metadata,created_at FROM dirty_coin_ledger WHERE user_id=${userId} ORDER BY created_at DESC,id DESC LIMIT ${Math.max(1,Math.min(50,Number(limit)||20))}`;return{balance:Number(wallet.balance||0),updatedAt:wallet.updated_at||null,ledger};}

async function roundParticipation(roomCode,ranking){const rounds=await sql`SELECT round_number,master_user_id,submissions FROM match_rounds WHERE room_code=${roomCode} ORDER BY round_number`;const counts=new Map(),active=[];for(const r of rounds){const ids=new Set();if(r.master_user_id)ids.add(String(r.master_user_id));for(const s of Array.isArray(r.submissions)?r.submissions:[])if(s?.userId)ids.add(String(s.userId));active.push(ids.size);for(const id of ids)counts.set(id,(counts.get(id)||0)+1);}const totalRounds=rounds.length,effectivePlayers=totalRounds?clamp(3,10,active.reduce((a,b)=>a+b,0)/totalRounds):clamp(3,10,ranking.filter(r=>r.userId).length);return{rounds,totalRounds,effectivePlayers,byUser:new Map(ranking.filter(r=>r.userId).map(r=>{const participated=counts.get(String(r.userId))||0,ratio=totalRounds?participated/totalRounds:0;return[String(r.userId),{eligibleRounds:totalRounds,participatedRounds:participated,ratio,survivalEligible:ratio>=0.70}];}))};}

async function settleMatchRewards(room,ranking,{validForRewards=true}={}){const prior=(await sql`SELECT * FROM match_reward_settlements WHERE room_code=${room.code} LIMIT 1`)[0];if(prior?.settled_at){const payouts=await sql`SELECT * FROM match_reward_participation WHERE room_code=${room.code} ORDER BY final_position,user_id`;return{alreadySettled:true,validForRewards:!!prior.valid_for_rewards,engineVersion:prior.engine_version,effectivePlayers:Number(prior.effective_players),effort:Number(prior.effort_index),multiplier:Number(prior.money_multiplier),survivalBonus:Number(prior.survival_bonus),payouts};}
 const participation=await roundParticipation(room.code,ranking),pointsToWin=clamp(3,20,room.pointsToWin||5),curve=rewardCurve(pointsToWin,participation.effectivePlayers),eligibleUsers=ranking.filter(r=>r.userId),valid=Boolean(validForRewards&&participation.totalRounds>0&&eligibleUsers.length>=3),snapshot={pointsToWin,effectivePlayers:participation.effectivePlayers,totalRounds:participation.totalRounds,ranking:eligibleUsers.map((r,i)=>({userId:r.userId,position:i+1,score:r.score}))};
 await sql`INSERT INTO match_reward_settlements(room_code,engine_version,points_to_win,effective_players,effort_index,money_multiplier,survival_bonus,total_rounds,valid_for_rewards,snapshot) VALUES(${room.code},${REWARD_ENGINE_VERSION},${pointsToWin},${participation.effectivePlayers},${curve.effort},${curve.multiplier},${curve.survival},${participation.totalRounds},${valid},${JSON.stringify(snapshot)}::jsonb) ON CONFLICT(room_code) DO NOTHING`;
 const payouts=[];for(let i=0;i<eligibleUsers.length;i++){const row=eligibleUsers[i],position=i+1,p=participation.byUser.get(String(row.userId))||{eligibleRounds:participation.totalRounds,participatedRounds:0,ratio:0,survivalEligible:false},reward=valid?payoutForPosition(position,eligibleUsers.length,curve,p.survivalEligible):{placement:0,survival:0,consolation:0,total:0};await sql`INSERT INTO match_reward_participation(room_code,user_id,eligible_rounds,participated_rounds,participation_ratio,survival_eligible,final_position,placement_reward,survival_reward,consolation_reward,total_reward) VALUES(${room.code},${row.userId},${p.eligibleRounds},${p.participatedRounds},${p.ratio},${p.survivalEligible},${position},${reward.placement},${reward.survival},${reward.consolation},${reward.total}) ON CONFLICT(room_code,user_id) DO UPDATE SET eligible_rounds=EXCLUDED.eligible_rounds,participated_rounds=EXCLUDED.participated_rounds,participation_ratio=EXCLUDED.participation_ratio,survival_eligible=EXCLUDED.survival_eligible,final_position=EXCLUDED.final_position,placement_reward=EXCLUDED.placement_reward,survival_reward=EXCLUDED.survival_reward,consolation_reward=EXCLUDED.consolation_reward,total_reward=EXCLUDED.total_reward`;
 if(valid&&reward.placement)await creditDirtyCoins(row.userId,reward.placement,'match_placement',`match:${room.code}:placement:${row.userId}`,{referenceType:'match',referenceId:room.code,metadata:{position,engineVersion:REWARD_ENGINE_VERSION}});
 if(valid&&reward.survival)await creditDirtyCoins(row.userId,reward.survival,'match_survival',`match:${room.code}:survival:${row.userId}`,{referenceType:'match',referenceId:room.code,metadata:{participation:p.ratio,engineVersion:REWARD_ENGINE_VERSION}});
 if(valid&&reward.consolation)await creditDirtyCoins(row.userId,reward.consolation,'match_consolation',`match:${room.code}:consolation:${row.userId}`,{referenceType:'match',referenceId:room.code,metadata:{position}});
 payouts.push({userId:row.userId,position,...p,...reward});}
 await sql`UPDATE match_reward_settlements SET settled_at=now() WHERE room_code=${room.code}`;return{alreadySettled:false,validForRewards:valid,engineVersion:REWARD_ENGINE_VERSION,effectivePlayers:participation.effectivePlayers,effort:curve.effort,multiplier:curve.multiplier,survivalBonus:curve.survival,payouts};}

async function ensureLegacyOwnedCard(userId,type,text){const rows=await sql`INSERT INTO user_cards(user_id,type,text,owned,is_player_card) VALUES(${userId},${type},${text},true,true) ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,is_player_card=true,updated_at=now() RETURNING id`;return rows[0]?.id||null;}
async function ensureOwnedCards(userId,type,texts,meta={}){if(!userId)return;for(const raw of texts||[]){const text=String(raw||'').trim();if(!text)continue;const legacyUserCardId=await ensureLegacyOwnedCard(userId,type,text);await canonicalCards.resolveCanonicalCard({type,text,userId,acquisitionSource:meta.acquisitionSource||'legacy_import',sourceUserId:meta.sourceUserId||null,sourceMatchId:meta.sourceMatchId||null,legacyUserCardId});}}
async function sharePlayerCards(room,type,texts){for(const p of room.players.values())if(p.userId&&p.active!==false)await ensureOwnedCards(p.userId,type,texts,{acquisitionSource:'legacy_auto_share',sourceMatchId:room.code});}
async function registerSubmittedCards(room,player,type,allTexts,createdTexts){const created=new Set((createdTexts||[]).map(normalizeCardText));for(const raw of allTexts||[]){const text=String(raw||'').trim();if(!text)continue;const isCreation=created.has(normalizeCardText(text));await canonicalCards.resolveCanonicalCard({type,text,userId:player.userId,creatorName:player.nickname,matchId:room.code,isCreation,acquisitionSource:isCreation?null:'legacy_import',sourceMatchId:room.code});await cardOrigins.ensureOrigin(type,text,{creatorUserId:isCreation?player.userId:null,creatorName:isCreation?player.nickname:null,roomCode:room.code});}}
async function markCreatedDuplicates(room,userId,type,texts){if(!userId)return;const others=Array.from(room.players.values()).filter(p=>p.active!==false).map(p=>p.userId).filter(id=>id&&String(id)!==String(userId));for(const raw of texts||[]){const text=String(raw||'').trim();if(!text)continue;await ensureOwnedCards(userId,type,[text]);for(const otherId of others){const rows=await sql`INSERT INTO user_cards(user_id,type,text,owned,is_player_card,duplicate_creation_count) VALUES(${otherId},${type},${text},true,true,1) ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,is_player_card=true,duplicate_creation_count=user_cards.duplicate_creation_count+1,updated_at=now() RETURNING id`;await canonicalCards.resolveCanonicalCard({type,text,userId:otherId,acquisitionSource:'legacy_auto_share',sourceUserId:userId,sourceMatchId:room.code,legacyUserCardId:rows[0]?.id||null});}await cardOrigins.markRecreated(type,text,userId);}}
async function recordUse(roomCode,userId,type,text){if(!userId||!text)return;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_used) VALUES(${userId},${type},${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_used=user_cards.times_used+1,updated_at=now()`;const existing=await sql`SELECT used_count FROM card_match_usage WHERE room_code=${roomCode} AND user_id=${userId} AND type=${type} AND text=${text}`;await sql`INSERT INTO card_match_usage(room_code,user_id,type,text,used_count) VALUES(${roomCode},${userId},${type},${text},1) ON CONFLICT(room_code,user_id,type,text) DO UPDATE SET used_count=card_match_usage.used_count+1`;if(!existing.length)await sql`UPDATE user_cards SET matches_used=matches_used+1 WHERE user_id=${userId} AND type=${type} AND text=${text}`;}
async function recordSeen(room,type,text){if(!text)return;for(const p of room.players.values()){if(!p.userId||p.active===false)continue;const previous=await sql`SELECT seen_count FROM card_match_usage WHERE room_code=${room.code} AND user_id=${p.userId} AND type=${type} AND text=${text}`;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_seen) VALUES(${p.userId},${type},${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_seen=user_cards.times_seen+1,updated_at=now()`;await sql`INSERT INTO card_match_usage(room_code,user_id,type,text,seen_count) VALUES(${room.code},${p.userId},${type},${text},1) ON CONFLICT(room_code,user_id,type,text) DO UPDATE SET seen_count=card_match_usage.seen_count+1`;if(type==='blackCards'&&!previous.length)await sql`UPDATE user_cards SET matches_used=matches_used+1 WHERE user_id=${p.userId} AND type=${type} AND text=${text} AND owned=true`;}}
async function recordBlackWin(userId,text){if(!userId||!text)return;await sql`INSERT INTO user_cards(user_id,type,text,owned,times_won) VALUES(${userId},'blackCards',${text},false,1) ON CONFLICT(user_id,type,text) DO UPDATE SET times_won=user_cards.times_won+1,updated_at=now()`;}
async function recordRoomCardVisits(room){await cardOrigins.visitRoom(room.code,'blackCards',room.blackDeck||[]);await cardOrigins.visitRoom(room.code,'whiteCards',room.whiteDeck||[]);}
async function recordRoundReplay(room){if(!room.currentRound)return;const r=room.currentRound,master=room.players.get(r.hostId),winner=room.players.get(r.winnerId),submissions=Array.from(r.submissions.entries()).map(([id,s])=>{const p=room.players.get(id);return{userId:Number(p?.userId||id)||null,nickname:p?.nickname||'Jogador',card:s.card};}),scores=Array.from(room.players.values()).map(p=>({userId:Number(p.userId)||null,nickname:p.nickname,score:p.score})).sort((a,b)=>b.score-a.score);await sql`INSERT INTO match_rounds(room_code,round_number,black_card,master_user_id,master_nickname,submissions,winner_user_id,winner_nickname,winner_card,scores) VALUES(${room.code},${r.number},${r.blackCard},${master?.userId||null},${master?.nickname||null},${JSON.stringify(submissions)},${winner?.userId||null},${winner?.nickname||null},${r.winnerCard||null},${JSON.stringify(scores)}) ON CONFLICT(room_code,round_number) DO UPDATE SET submissions=EXCLUDED.submissions,winner_user_id=EXCLUDED.winner_user_id,winner_nickname=EXCLUDED.winner_nickname,winner_card=EXCLUDED.winner_card,scores=EXCLUDED.scores`;if(master?.userId&&winner?.userId)await sql`INSERT INTO round_votes(room_code,round_number,chooser_user_id,winner_user_id) VALUES(${room.code},${r.number},${master.userId},${winner.userId}) ON CONFLICT DO NOTHING`;for(const s of submissions)await recordSeen(room,'whiteCards',s.card);}
async function getActiveSeasonId(){const season=await ensureMonthlySeason();return season?.id||null;}
async function finalizeMatch(room,options={}){const ranking=Array.from(room.players.entries()).map(([id,p])=>({userId:p.userId||Number(id)||null,nickname:p.nickname,avatarData:p.avatarData||null,score:p.score})).sort((a,b)=>b.score-a.score),top=ranking[0],seasonId=await getActiveSeasonId(),total=ranking.length;for(let i=0;i<ranking.length;i++){const row=ranking[i];if(!row.userId)continue;await sql`INSERT INTO match_players(room_code,user_id,nickname,avatar_data,final_score,rounds_won,won_match,season_id,final_position,total_players) VALUES(${room.code},${row.userId},${row.nickname},${row.avatarData},${row.score},${row.score},${!!top&&row.userId===top.userId},${seasonId},${i+1},${total}) ON CONFLICT(room_code,user_id) DO UPDATE SET nickname=EXCLUDED.nickname,avatar_data=EXCLUDED.avatar_data,final_score=EXCLUDED.final_score,rounds_won=EXCLUDED.rounds_won,won_match=EXCLUDED.won_match,season_id=EXCLUDED.season_id,final_position=EXCLUDED.final_position,total_players=EXCLUDED.total_players,finished_at=now()`;}const economy=process.env.ECONOMY_SETTLEMENTS_ENABLED==='false'?null:await settleMatchRewards(room,ranking,{validForRewards:options.validForRewards!==false});return{ranking,seasonId,economy};}
module.exports={ensureOwnedCards,sharePlayerCards,registerSubmittedCards,markCreatedDuplicates,recordUse,recordSeen,recordBlackWin,recordRoomCardVisits,recordRoundReplay,finalizeMatch,getActiveSeasonId,REWARD_ENGINE_VERSION,effortIndex,rewardCurve,payoutForPosition,ensureWallet,creditDirtyCoins,ensureStarterCoins,getEconomy,settleMatchRewards};