'use strict';
const rewardRules=require('./rewardEngineRules');
const lootRules=require('./matchLootRules');
const{CONFIG}=require('./balanceConfig');
const CLASSES=CONFIG.durationClasses;
function matchClass(effort){const e=Math.max(0,Number(effort)||0);let out=CLASSES[0];for(const row of CLASSES)if(e>=row.min)out=row;return{...out};}
function preview({pointsToWin=10,participants=6,handSize=5}={}){const points=Math.round(rewardRules.clamp(CONFIG.reward.pointsMin,CONFIG.reward.pointsMax,pointsToWin)),players=Math.round(rewardRules.clamp(CONFIG.reward.playersMin,CONFIG.reward.playersMax,participants)),hand=Math.round(rewardRules.clamp(5,15,handSize));const curve=rewardRules.rewardCurve(points,players),klass=matchClass(curve.effort),payout=position=>rewardRules.payoutForPosition(position,players,curve,true),first=payout(1),second=payout(2),third=payout(3),other=players>3?payout(4):null,last=players>3?payout(players):null;return{engineVersion:curve.engineVersion,pointsToWin:points,participants:players,handSize:hand,effort:curve.effort,moneyMultiplier:curve.multiplier,class:klass,payouts:{first,second,third,other,last,survivalBonus:curve.survival},loot:{first:lootRules.requestedLootQuota(1,curve.effort),second:lootRules.requestedLootQuota(2,curve.effort),third:lootRules.requestedLootQuota(3,curve.effort),other:players>3?lootRules.requestedLootQuota(4,curve.effort):0}};}
function freezeRoom(room){const participants=Array.from(room.players?.values?.()||[]).filter(p=>p.active!==false).length,p=preview({pointsToWin:room.pointsToWin,participants,handSize:room.handSize});return{engineVersion:p.engineVersion,pointsToWin:p.pointsToWin,participantsAtStart:p.participants,maxPlayersConfigured:Number(room.maxPlayers)||p.participants,handSizeAtStart:p.handSize,effortAtStart:p.effort,moneyMultiplierAtStart:p.moneyMultiplier,classKey:p.class.key,classLabel:p.class.label,frozenAt:new Date().toISOString()};}
module.exports={CLASSES,matchClass,preview,freezeRoom};
