const { sql } = require('./db');
function rowsToRoom(roomRow,playerRows){const players=new Map();for(const p of playerRows){const key=String(p.user_id||p.id);players.set(key,{userId:p.user_id||null,visualId:p.visual_id||null,nickname:p.nickname,avatarData:p.avatar_data||null,score:p.score,hand:p.hand||[],cardsReady:p.cards_ready,blackCards:p.black_cards||[],whiteCards:p.white_cards||[],connected:p.connected,active:p.active!==false,lastActive:new Date(p.last_active).getTime()});}let currentRound=null;if(roomRow.current_round){const cr=roomRow.current_round;currentRound={number:cr.number,blackCard:cr.blackCard,hostIndex:cr.hostIndex,hostId:String(cr.hostId),submissions:new Map(Object.entries(cr.submissions||{})),winnerId:cr.winnerId?String(cr.winnerId):null,winnerCard:cr.winnerCard||null};}return{code:roomRow.code,creatorId:String(roomRow.creator_id),state:roomRow.state,maxPlayers:roomRow.max_players,blackCardsPerPlayer:roomRow.black_cards_per_player,whiteCardsPerPlayer:roomRow.white_cards_per_player,pointsToWin:roomRow.points_to_win,handSize:roomRow.hand_size,useStandardDeck:roomRow.use_standard_deck,cardCreationEnabled:roomRow.card_creation_enabled!==false,blackDeck:roomRow.black_deck||[],whiteDeck:roomRow.white_deck||[],playerOrder:(roomRow.player_order||[]).map(String),currentRound,players};}
async function loadRoom(code){if(!code)return null;const c=String(code).toUpperCase().trim(),rooms=await sql`SELECT * FROM rooms WHERE code=${c}`;if(!rooms.length)return null;const players=await sql`SELECT * FROM players WHERE room_code=${c}`;return rowsToRoom(rooms[0],players);}
function serializeCurrentRound(r){if(!r)return null;return{number:r.number,blackCard:r.blackCard,hostIndex:r.hostIndex,hostId:r.hostId,submissions:Object.fromEntries(r.submissions||new Map()),winnerId:r.winnerId||null,winnerCard:r.winnerCard||null};}
async function insertRoom(room){const c=room.code.toUpperCase().trim();await sql`INSERT INTO rooms(code,creator_id,state,max_players,black_cards_per_player,white_cards_per_player,points_to_win,hand_size,use_standard_deck,card_creation_enabled,black_deck,white_deck,player_order,current_round,updated_at) VALUES(${c},${room.creatorId},${room.state},${room.maxPlayers},${room.blackCardsPerPlayer},${room.whiteCardsPerPlayer},${room.pointsToWin},${room.handSize},${room.useStandardDeck},${room.cardCreationEnabled!==false},${JSON.stringify(room.blackDeck)},${JSON.stringify(room.whiteDeck)},${JSON.stringify(room.playerOrder)},${room.currentRound?JSON.stringify(serializeCurrentRound(room.currentRound)):null},now())`;await syncPlayers(room);}
async function saveRoom(room){const c=room.code.toUpperCase().trim();await sql`UPDATE rooms SET state=${room.state},max_players=${room.maxPlayers},black_cards_per_player=${room.blackCardsPerPlayer},white_cards_per_player=${room.whiteCardsPerPlayer},points_to_win=${room.pointsToWin},hand_size=${room.handSize},use_standard_deck=${room.useStandardDeck},card_creation_enabled=${room.cardCreationEnabled!==false},black_deck=${JSON.stringify(room.blackDeck)},white_deck=${JSON.stringify(room.whiteDeck)},player_order=${JSON.stringify(room.playerOrder)},current_round=${room.currentRound?JSON.stringify(serializeCurrentRound(room.currentRound)):null},updated_at=now() WHERE code=${c}`;await syncPlayers(room);}
async function syncPlayers(room){const c=room.code.toUpperCase().trim(),ids=[];for(const[key,p]of room.players){const id=String(p.userId||key);ids.push(id);await sql`INSERT INTO players(id,room_code,user_id,visual_id,nickname,avatar_data,score,hand,cards_ready,black_cards,white_cards,connected,active,last_active) VALUES(${id},${c},${p.userId||null},${p.visualId||null},${p.nickname},${p.avatarData||null},${p.score},${JSON.stringify(p.hand)},${p.cardsReady},${JSON.stringify(p.blackCards)},${JSON.stringify(p.whiteCards)},${p.connected},${p.active!==false},to_timestamp(${p.lastActive/1000})) ON CONFLICT(id,room_code) DO UPDATE SET user_id=EXCLUDED.user_id,visual_id=EXCLUDED.visual_id,nickname=EXCLUDED.nickname,avatar_data=EXCLUDED.avatar_data,score=EXCLUDED.score,hand=EXCLUDED.hand,cards_ready=EXCLUDED.cards_ready,black_cards=EXCLUDED.black_cards,white_cards=EXCLUDED.white_cards,connected=EXCLUDED.connected,active=EXCLUDED.active,last_active=EXCLUDED.last_active`;}
 if(ids.length)await sql`DELETE FROM players WHERE room_code=${c} AND id != ALL(${ids})`;else await sql`DELETE FROM players WHERE room_code=${c}`;}
async function deleteRoom(code){await sql`DELETE FROM rooms WHERE code=${String(code).toUpperCase().trim()}`;}
async function roomExists(code){const r=await sql`SELECT 1 FROM rooms WHERE code=${String(code).toUpperCase().trim()}`;return r.length>0;}
module.exports={loadRoom,insertRoom,saveRoom,deleteRoom,roomExists};
