const { broadcast } = require('./pusherServer');
const gameManager = require('./gameManager');
const roomStore = require('./roomStore');
const { sql } = require('./db');
const playerStats = require('./playerStats');

async function broadcastPlayerListUpdate(room){await broadcast(room.code,'player_list_update',{players:gameManager.getPlayerList(room),state:room.state,playerCount:room.players.size,maxPlayers:room.maxPlayers});}
async function broadcastNewRound(room){const r=room.currentRound,p=room.players.get(r.hostId);await broadcast(room.code,'new_round',{roundNumber:r.number,blackCard:r.blackCard,hostNickname:p?p.nickname:'Desconhecido',hostId:r.hostId,scores:gameManager.getScoresForRoom(room)});}
async function broadcastGameOver(room,message){const ranking=gameManager.calculateRanking(room);await broadcast(room.code,'game_over',{message,ranking,winnerNickname:ranking[0]?.nickname||'Desconhecido'});await sql`INSERT INTO match_history(room_code,ranking,winner_nickname) VALUES(${room.code},${JSON.stringify(ranking)},${ranking[0]?.nickname||null})`;await playerStats.finalizeMatch(room);}
async function applyPresenceSweep(room){const events=gameManager.sweepPresence(room);if(!events.disconnected.length&&!events.removed.length)return{deleted:false};if(!room.players.size){await roomStore.deleteRoom(room.code);return{deleted:true};}await roomStore.saveRoom(room);for(const d of events.disconnected)await broadcast(room.code,'player_disconnected',{nickname:d.nickname,id:d.playerId});for(const r of events.removed){if(r.destroyed){await broadcast(room.code,'room_closed',{message:'O Host desconectou. A sala foi encerrada.'});await roomStore.deleteRoom(room.code);return{deleted:true};}await broadcast(room.code,'player_left',{nickname:r.nickname});if(r.gameOver){await broadcastGameOver(room,'Jogadores insuficientes. O jogo acabou!');}else if((r.masterDropped||r.czarDropped)&&room.currentRound){await broadcast(room.code,'round_skipped',{message:'O Mestre da rodada foi removido. Pulando...'});const{gameOver}=await gameManager.nextRound(room);await roomStore.saveRoom(room);if(gameOver)await broadcastGameOver(room,'O jogo acabou! Não há mais cartas pretas.');else await broadcastNewRound(room);}}if(!room.players.size){await roomStore.deleteRoom(room.code);return{deleted:true};}await broadcastPlayerListUpdate(room);return{deleted:false};}
module.exports={broadcastPlayerListUpdate,broadcastNewRound,broadcastGameOver,applyPresenceSweep};
