'use strict';
const{sql}=require('./db');
const enabled=()=>process.env.TELEMETRY_ENABLED!=='false';
async function safe(label,fn){if(!enabled())return null;try{return await fn();}catch(e){console.warn(`[telemetry:${label}]`,e?.message||e);return null;}}
function activeCount(room){return Array.from(room?.players?.values?.()||[]).filter(p=>p.active!==false).length;}
async function startMatch(room){const snap=room?.rewardConfigSnapshot||{},code=String(room?.code||'');if(!code)return null;const started=snap.frozenAt?new Date(snap.frozenAt):new Date();return safe('start',()=>sql`INSERT INTO match_telemetry(room_code,started_at,points_to_win,participants_at_start,max_players_configured,hand_size_at_start,class_key,class_label,effort_at_start,engine_version,metadata) VALUES(${code},${started},${Number(snap.pointsToWin||room.pointsToWin||0)},${Number(snap.participantsAtStart||activeCount(room))},${Number(snap.maxPlayersConfigured||room.maxPlayers||0)},${Number(snap.handSizeAtStart||room.handSize||0)},${snap.classKey||null},${snap.classLabel||null},${Number(snap.effortAtStart||0)},${snap.engineVersion||null},${JSON.stringify({balanceVersion:'metagame-v1.4-p12'})}::jsonb) ON CONFLICT(room_code) DO NOTHING`);}
async function bump(roomCode,kind,amount=1){const code=String(roomCode||''),n=Math.max(0,Math.trunc(Number(amount)||0));if(!code||!n)return null;if(kind==='disconnect')return safe('disconnect',()=>sql`UPDATE match_telemetry SET disconnect_count=disconnect_count+${n} WHERE room_code=${code}`);if(kind==='rejoin')return safe('rejoin',()=>sql`UPDATE match_telemetry SET rejoin_count=rejoin_count+${n} WHERE room_code=${code}`);if(kind==='abandon')return safe('abandon',()=>sql`UPDATE match_telemetry SET abandon_count=abandon_count+${n} WHERE room_code=${code}`);return null;}
async function event(eventType,{roomCode=null,sourceKey=null,phase=null,status=null,metadata={},idempotencyKey=null}={}){const type=String(eventType||'').trim();if(!type)return null;return safe('event',()=>sql`INSERT INTO operational_events(event_type,room_code,source_key,phase,status,metadata,idempotency_key) VALUES(${type},${roomCode?String(roomCode):null},${sourceKey?String(sourceKey):null},${phase?String(phase):null},${status?String(status):null},${JSON.stringify(metadata||{})}::jsonb,${idempotencyKey?String(idempotencyKey):null}) ON CONFLICT(idempotency_key) DO NOTHING`);}
async function finishMatch(room,{validForRewards=false,reason='completed',economy=null}={}){const code=String(room?.code||'');if(!code)return null;await startMatch(room);return safe('finish',async()=>{const rounds=Number((await sql`SELECT COUNT(*)::int n FROM match_rounds WHERE room_code=${code}`)[0]?.n||0);const effective=economy?.effectivePlayers===undefined||economy?.effectivePlayers===null?null:Number(economy.effectivePlayers);return sql`UPDATE match_telemetry SET finished_at=COALESCE(finished_at,now()),duration_seconds=COALESCE(duration_seconds,GREATEST(0,EXTRACT(EPOCH FROM(now()-started_at))::int)),total_rounds=COALESCE(total_rounds,${rounds}),effective_players=COALESCE(effective_players,${effective}),valid_for_rewards=COALESCE(valid_for_rewards,${!!validForRewards}),finish_reason=COALESCE(finish_reason,${String(reason||'completed')}),metadata=metadata||${JSON.stringify({finalActivePlayers:activeCount(room)})}::jsonb WHERE room_code=${code}`;});}
module.exports={enabled,startMatch,finishMatch,bump,event};
