'use strict';
const{sql}=require('../../lib/db');
const{withErrors,ok,requireMethod}=require('../../lib/http');
const{requireUser,cardMaterialTier,nextTierProgress}=require('../../lib/auth');
const{canonicalIdentity}=require('../../lib/cardIdentity');
const progression=require('../../lib/cardProgressionRules');
function authorLabel(authors){const names=(authors||[]).map(a=>a.display_name).filter(Boolean);if(!names.length)return'Legado do Cartaralho';if(names.length<=3)return names.join(', ').replace(/, ([^,]*)$/, ' e $1');return`${names.slice(0,2).join(', ')} e +${names.length-2}`;}
function metaKey(type,text){try{const x=canonicalIdentity(type,text);return`${x.cardType}:${x.normalizedText}`;}catch(_){return null;}}
function borderState(score){const p=progression.progressFor(Number(score||0),'border');return{tier:p.tier,progress:{current:p.score,nextTier:p.nextTier,target:p.target,remaining:p.remaining}};}
module.exports=withErrors(async(req,res)=>{
 if(!requireMethod(req,res,'GET'))return;
 const user=await requireUser(req,res);if(!user)return;
 const rows=await sql`SELECT c.id,c.type,c.text,c.owned,c.is_player_card,c.is_favorite,c.times_used,c.matches_used,c.times_seen,c.times_won,c.duplicate_creation_count,c.created_at,c.updated_at,COALESCE(d.is_native,false) is_native,co.creator_user_id legacy_creator_user_id,COALESCE(u.display_name,co.creator_name_snapshot) legacy_creator_name,u.username legacy_creator_username,co.first_room_code legacy_first_room_code,co.first_seen_at legacy_first_seen_at,co.recreated_count legacy_recreated_count,(SELECT COUNT(DISTINCT crp.room_code)::int FROM card_room_presence crp WHERE crp.type=c.type AND lower(regexp_replace(trim(crp.text),'\\s+',' ','g'))=lower(regexp_replace(trim(c.text),'\\s+',' ','g'))) tables_visited FROM user_cards c LEFT JOIN deck_cards d ON d.type=c.type AND lower(regexp_replace(trim(d.text),'\\s+',' ','g'))=lower(regexp_replace(trim(c.text),'\\s+',' ','g')) LEFT JOIN card_origins co ON co.type=c.type AND co.text_key=lower(regexp_replace(trim(c.text),'\\s+',' ','g')) LEFT JOIN users u ON u.id=co.creator_user_id WHERE c.user_id=${user.id} ORDER BY c.is_favorite DESC,c.type,c.text`;
 const canonicalRows=await sql`SELECT cc.id,cc.card_type,cc.normalized_text,cc.display_text,cc.origin_match_id,cc.origin_uncertain,cc.created_at,o.acquisition_source,o.source_user_id,o.source_match_id,o.acquired_at,su.display_name source_display_name,su.username source_username,COALESCE(p.white_personal_wins,0)::int white_personal_wins,COALESCE(p.external_presence_matches,0)::int external_presence_matches,(SELECT COUNT(DISTINCT h.user_id)::int FROM canonical_card_ownerships h WHERE h.canonical_card_id=cc.id) holders,(SELECT COUNT(DISTINCT h.user_id)::int FROM canonical_card_ownerships h WHERE h.canonical_card_id=cc.id AND h.acquisition_source='match_loot') adoptions,(SELECT COUNT(*)::int FROM canonical_card_round_events e WHERE e.canonical_card_id=cc.id AND e.event_type IN('white_revealed','black_used')) global_plays,(SELECT COUNT(*)::int FROM canonical_card_round_events e WHERE e.canonical_card_id=cc.id AND e.event_type='white_win') global_wins,COALESCE((SELECT json_agg(json_build_object('user_id',a.user_id,'display_name',COALESCE(au.display_name,a.author_name_snapshot,au.username,'Criador desconhecido'),'username',au.username,'authored_at',a.authored_at) ORDER BY a.authored_at,a.user_id) FROM canonical_card_authors a LEFT JOIN users au ON au.id=a.user_id WHERE a.canonical_card_id=cc.id),'[]'::json) authors FROM canonical_card_ownerships o JOIN canonical_cards cc ON cc.id=o.canonical_card_id LEFT JOIN user_card_progress p ON p.user_id=o.user_id AND p.canonical_card_id=o.canonical_card_id LEFT JOIN users su ON su.id=o.source_user_id WHERE o.user_id=${user.id}`;
 const canonicalByKey=new Map(canonicalRows.map(x=>[`${x.card_type}:${x.normalized_text}`,x]));
 const merged=[],byKey=new Map();
 for(const row of rows){
  const meta=row.is_player_card?canonicalByKey.get(metaKey(row.type,row.text)):null,key=meta?`canonical:${meta.id}`:`legacy:${row.id}`;
  if(byKey.has(key)){const target=byKey.get(key);target.is_favorite=Boolean(target.is_favorite||row.is_favorite);target.owned=Boolean(target.owned||row.owned);target.times_used+=Number(row.times_used||0);target.matches_used+=Number(row.matches_used||0);target.times_seen+=Number(row.times_seen||0);target.times_won+=Number(row.times_won||0);target.duplicate_creation_count+=Number(row.duplicate_creation_count||0);continue;}
  const authors=Array.isArray(meta?.authors)?meta.authors:[],creatorName=row.is_native?'Cartaralho':(authors.length?authorLabel(authors):(row.legacy_creator_name||'Legado do Cartaralho')),isOriginal=authors.some(a=>String(a.user_id)===String(user.id));
  const personalRoundWins=Number(meta?.white_personal_wins??row.times_won??0),worldHolders=Number(meta?.holders||0),lootCollectors=Number(meta?.adoptions||0),externalPresenceMatches=Number(meta?.external_presence_matches??row.times_seen??0),globalPlays=Math.max(0,Number(meta?.global_plays??row.times_used??0)),globalWins=Math.max(0,Math.min(globalPlays,Number(meta?.global_wins??row.times_won??0))),globalLosses=Math.max(0,globalPlays-globalWins),createdAt=meta?.created_at||row.created_at||row.legacy_first_seen_at||null,border=borderState(lootCollectors);
  const card={...row,text:meta?.display_text||row.text,canonicalCardId:meta?.id||null,isOriginal,times_used:Number(row.times_used||0),matches_used:Number(row.matches_used||0),times_seen:Number(row.times_seen||0),times_won:Number(row.times_won||0),duplicate_creation_count:Number(row.duplicate_creation_count||0),personalRoundWins,worldHolders,lootCollectors,externalPresenceMatches,globalPlays,globalWins,globalLosses,borderTier:border.tier,borderProgress:border.progress,origin:{authors:authors.map(a=>({userId:a.user_id,displayName:a.display_name,username:a.username||null,authoredAt:a.authored_at})),creatorUserId:authors[0]?.user_id||row.legacy_creator_user_id||null,creatorName,creatorUsername:authors[0]?.username||row.legacy_creator_username||null,createdAt,firstRoomCode:meta?.origin_match_id||row.legacy_first_room_code||null,firstSeenAt:meta?.created_at||row.legacy_first_seen_at||null,originUncertain:Boolean(meta?.origin_uncertain),tablesVisited:globalPlays,holders:worldHolders,adoptions:lootCollectors,recreatedCount:Number(row.legacy_recreated_count||0),seenByCurrentUser:externalPresenceMatches,globalPlays,globalWins,globalLosses},genealogy:{acquisitionSource:meta?.acquisition_source||'legacy_import',sourceUserId:meta?.source_user_id||null,sourceUserName:meta?.source_display_name||null,sourceUsername:meta?.source_username||null,sourceMatchId:meta?.source_match_id||null,acquiredAt:meta?.acquired_at||row.created_at||null}};
  byKey.set(key,card);merged.push(card);
 }
 ok(res,{cards:merged.map(c=>({...c,materialTier:cardMaterialTier(c.personalRoundWins),materialProgress:nextTierProgress(c.personalRoundWins,'material'),rarityExplanation:{material:'O fundo evolui pela quantidade de rodadas que você venceu utilizando esta carta.',border:'A borda evolui pela quantidade de jogadores distintos que coletaram esta Carta Canônica em Espólios.'}}))});
});
