'use strict';
const{withErrors,ok,fail,requireMethod,getBody}=require('../../lib/http');
const{requireUser}=require('../../lib/auth');
const roomStore=require('../../lib/roomStore');
const{GAME_STATES}=require('../../lib/constants');
const cleanCards=require('../../lib/cleanCards');

module.exports=withErrors(async(req,res)=>{
 if(!requireMethod(req,res,'POST'))return;
 const user=await requireUser(req,res);if(!user)return;
 if(process.env.PAID_CARD_CREATION_ENABLED==='false')return fail(res,503,'Criação paga temporariamente indisponível.');
 const{code,type,text,creationId}=getBody(req);
 if(!code)return fail(res,400,'Código da sala é obrigatório.');
 if(String(creationId||'').trim().length<8)return fail(res,400,'Identificador de criação inválido.');
 const room=await roomStore.loadRoom(code);
 if(!room)return fail(res,404,'Sala não encontrada.');
 const player=Array.from(room.players.values()).find(p=>String(p.userId)===String(user.id));
 if(!player||player.active===false)return fail(res,403,'Você não está ativo nesta sala.');
 if(!room.cardCreationEnabled)return fail(res,403,'A criação de novas cartas está desativada nesta sala.');
 if(![GAME_STATES.CADASTRO_CARTAS,GAME_STATES.AGUARDANDO_JOGADORES].includes(room.state))return fail(res,409,'Não é possível criar cartas neste momento.');
 const cardType=cleanCards.normalizeType(type),display=String(text||'').trim();
 if(!cardType)return fail(res,400,'Tipo de carta inválido.');
 const limit=cardType==='black'?200:120;
 if(!display)return fail(res,400,'Digite o texto da carta.');
 if(display.length>limit)return fail(res,400,`A carta deve ter no máximo ${limit} caracteres.`);
 const result=await cleanCards.create({userId:user.id,type:cardType,text:display,matchId:room.code,creatorName:player.nickname||user.display_name,creationId});
 if(result.status==='invalid_idempotency_key')return fail(res,400,'Identificador de criação inválido.');
 if(result.status==='invalid_text'||result.status==='invalid_type')return fail(res,400,'Carta inválida.');
 if(result.status==='duplicate_owned')return fail(res,409,'Você já possui essa Carta de Jogador. Selecione-a gratuitamente na sua coleção.');
 if(result.status==='insufficient_clean_cards')return fail(res,409,`Sem Cartas Limpas ${cardType==='black'?'Pretas':'Brancas'}. Compre 1 por ${cleanCards.UNIT_PRICE} Moedas Sujas.`);
 if(result.status!=='created')return fail(res,400,'Não foi possível sujar esta carta.');
 ok(res,{message:'Carta sujada com sucesso.',card:{type:cardType==='black'?'blackCards':'whiteCards',text:display,canonicalCardId:result.canonicalCardId,creationKind:result.creationKind||null},inventory:result});
});
