'use strict';
const{withErrors,ok,fail,getBody}=require('../../lib/http');
const{requireUser}=require('../../lib/auth');
const roomStore=require('../../lib/roomStore');
const cardSelection=require('../../lib/cardSelection');
const gameManager=require('../../lib/gameManager');
const{broadcast}=require('../../lib/pusherServer');
const{applyPresenceSweep}=require('../../lib/roomEvents');
module.exports=withErrors(async(req,res)=>{
 const user=await requireUser(req,res);if(!user)return;
 const code=String(req.method==='GET'?req.query?.code:getBody(req).code||'').trim().toUpperCase();if(!code)return fail(res,400,'code é obrigatório.');
 const room=await roomStore.loadRoom(code);if(!room)return fail(res,404,'Sala não encontrada.');
 const swept=await applyPresenceSweep(room);if(swept.deleted)return fail(res,404,'Sala não encontrada.');
 if(req.method==='GET')return ok(res,{selection:cardSelection.get(room,String(user.id))});
 if(req.method!=='POST')return fail(res,405,'Método não permitido. Use GET ou POST.');
 const{blackCards=[],whiteCards=[]}=getBody(req),result=await cardSelection.save(room,String(user.id),blackCards,whiteCards);
 await roomStore.saveRoom(room);
 const players=gameManager.getPlayerList(room),statuses=players.map(p=>({nickname:p.nickname,cardsReady:p.cardsReady}));
 await broadcast(room.code,'cards_submitted',{playerStatuses:statuses,changed:result.changed,message:result.changed?'Seleção de Cartas de Jogador atualizada.':'Seleção de Cartas de Jogador salva.'});
 ok(res,{selection:{blackCards:result.blackCards,whiteCards:result.whiteCards,cardsReady:result.cardsReady},changed:result.changed,state:room.state});
});
