'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const engine=require('../lib/advancedRoundEngine');
const{GAME_STATES}=require('../lib/constants');
function player(id,hand=[]){return{userId:Number(id),nickname:`P${id}`,hand:[...hand],active:true,connected:true,score:0};}
function room(){const players=new Map([['1',player(1)],['2',player(2,['A','B','C'])],['3',player(3,['D','E','F'])]]),r={code:'P09TEST',state:GAME_STATES.EM_ANDAMENTO,pointsToWin:5,playerOrder:['1','2','3'],players,whiteDeck:['W1','W2','W3','W4'],blackDeck:['Q3','Q2']};r.currentRound=engine.makeRound(r,{number:1,blackCard:'Q1',hostIndex:0,hostId:'1'});return r;}
test('duas submissões do mesmo usuário têm submission_id independentes',()=>{const r=room();engine.roundState(r.currentRound).requiredSubmissions['2']=2;const a=engine.playCard(r,'2',0),b=engine.playCard(r,'2',0);assert.notEqual(a.submissionId,b.submissionId);assert.equal(engine.forUser(r.currentRound,'2').length,2);assert.equal(r.state,GAME_STATES.EM_ANDAMENTO);const c=engine.playCard(r,'3',0);assert.equal(c.allPlayed,true);assert.equal(r.state,GAME_STATES.VOTACAO);assert.equal(new Set(engine.entries(r.currentRound).map(x=>x.id)).size,3);});
test('posse temporária acompanha a submissão e não se torna pessoal',()=>{const r=room();engine.addTemporaryMeta(r.currentRound,'2',{card:'A',originalUserId:99,progressEligible:false});const out=engine.playCard(r,'2',0),sub=engine.findSubmission(r,out.submissionId);assert.equal(out.temporary,true);assert.equal(sub.temporary,true);assert.equal(sub.temporaryOriginalUserId,99);assert.equal(engine.tempList(r.currentRound,'2').length,0);});
test('Mestre preserva a própria mão para a rotação futura, mas não pode jogar na rodada atual',()=>{const r=room(),master=r.players.get('1');master.hand=['M1','M2','M3'];const before=[...master.hand];assert.throws(()=>engine.playCard(r,'1',0),/Mestre da rodada não pode jogar cartas/);assert.deepEqual(master.hand,before);assert.equal(engine.required(r.currentRound,'1'),1);assert.equal(engine.progress(r).players.includes('1'),false);});
test('O poder subiu repete Mestre uma vez e preserva direção invertida',async()=>{const r=room(),rs=engine.roomState(r.currentRound);rs.repeatCurrentMasterOnce=true;rs.rotationDirection=-1;let n=await engine.nextRound(r);assert.equal(n.repeatedMaster,true);assert.equal(r.currentRound.hostId,'1');assert.equal(engine.roomState(r.currentRound).rotationDirection,-1);n=await engine.nextRound(r);assert.equal(n.repeatedMaster,false);assert.equal(r.currentRound.hostId,'3');assert.equal(engine.roomState(r.currentRound).rotationDirection,-1);});
test('CAOS TOTAL redige conteúdo no servidor e mantém apenas posições',()=>{const r=room();engine.roundState(r.currentRound).chaosActivators=['2'];const styled=[{text:'segredo 1'},{text:'segredo 2'}],victim=engine.redactHand(r,'3',styled),actor=engine.redactHand(r,'2',styled);assert.deepEqual(victim.map(x=>x.text),['████','████']);assert.deepEqual(victim.map(x=>x.position),[0,1]);assert.deepEqual(actor,styled);});
test('visão de espectador nunca contém mãos ou autoria privada',()=>{const r=room();engine.playCard(r,'2',0);engine.playCard(r,'3',0);const v=engine.spectatorView(r);assert.equal('hand' in v,false);assert.ok(Array.isArray(v.submissions));assert.equal(v.submissions.some(x=>'authorUserId' in x||'authorNickname' in x||'userId' in x),false);});
