'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
if(!process.env.DATABASE_URL){test('integração P04 requer DATABASE_URL',{skip:'DATABASE_URL ausente'},()=>{});}else{
 const{sql}=require('../lib/db'),p=require('../lib/cardProgression');
 test('progressão pessoal, borda e eventos são idempotentes',async()=>{
  const suffix=`p04_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,users=[],cards=[];
  const mkRoom=(code,players,currentRound)=>({code,players:new Map(players.map(x=>[String(x.userId),x])),currentRound});
  try{
   for(const k of['a','b','c','d'])users.push((await sql`INSERT INTO users(username,display_name,password_hash) VALUES(${`${suffix}_${k}`},${`P04 ${k}`},'test') RETURNING id,display_name`)[0]);
   const makeCard=async(type,text,ownerIds,authorIds=[])=>{const c=(await sql`INSERT INTO canonical_cards(card_type,normalized_text,display_text,origin_match_id,origin_uncertain) VALUES(${type},${text.toLowerCase()},${text},${suffix+'_origin'},false) RETURNING id`)[0];cards.push(c.id);for(const id of ownerIds)await sql`INSERT INTO canonical_card_ownerships(user_id,canonical_card_id,acquisition_source) VALUES(${id},${c.id},'created_independent')`;for(const id of authorIds)await sql`INSERT INTO canonical_card_authors(canonical_card_id,user_id,author_name_snapshot) VALUES(${c.id},${id},'P04')`;return c;};
   const shared=await makeCard('white',`${suffix} shared`,users.map(u=>u.id),[users[1].id]);
   const plist=users.map(u=>({userId:u.id,nickname:u.display_name,active:true,whiteCards:[`${suffix} shared`],blackCards:[]}));
   const room=mkRoom(`${suffix}_m1`,plist,{number:1,blackCard:'nativa',hostId:String(users[0].id),submissions:new Map([[String(users[1].id),{card:`${suffix} shared`}],[String(users[2].id),{card:`${suffix} shared`}],[String(users[3].id),{card:`${suffix} shared`}]]),winnerId:String(users[1].id),winnerCard:`${suffix} shared`});
   const first=await p.recordResolvedRound(room),second=await p.recordResolvedRound(room);assert.equal(first.winnerOriginal,true);assert.ok(first.originalPlays.some(x=>String(x.userId)===String(users[1].id)));assert.equal(second.winnerOriginal,true);
   const prog=await sql`SELECT * FROM user_card_progress WHERE canonical_card_id=${shared.id} ORDER BY user_id`;const owner=prog.find(x=>String(x.user_id)===String(users[0].id)),winner=prog.find(x=>String(x.user_id)===String(users[1].id));assert.equal(Number(owner.external_presence_matches),1);assert.equal(Number(winner.white_personal_wins),1);
   assert.equal(Number((await sql`SELECT COUNT(*)::int n FROM card_external_presence_events WHERE user_id=${users[0].id} AND canonical_card_id=${shared.id} AND match_id=${room.code}`)[0].n),1);
   assert.equal(Number((await sql`SELECT COUNT(*)::int n FROM card_personal_progress_events WHERE user_id=${users[1].id} AND canonical_card_id=${shared.id} AND metric='white_personal_win'`)[0].n),1);

   const own=await makeCard('white',`${suffix} own`,[users[0].id],[users[0].id]);const ownRoom=mkRoom(`${suffix}_own`,[{userId:users[0].id,nickname:'A',active:true,whiteCards:[`${suffix} own`],blackCards:[]}],{number:1,blackCard:'nativa',hostId:String(users[0].id),submissions:new Map([[String(users[0].id),{card:`${suffix} own`}]]),winnerId:String(users[0].id),winnerCard:`${suffix} own`});await p.recordResolvedRound(ownRoom);const ownProg=(await sql`SELECT * FROM user_card_progress WHERE user_id=${users[0].id} AND canonical_card_id=${own.id}`)[0];assert.equal(Number(ownProg.external_presence_matches),0);assert.equal(Number(ownProg.white_personal_wins),1);

   const temp=await makeCard('white',`${suffix} temp`,[users[0].id],[users[0].id]);const tempRoom=mkRoom(`${suffix}_temp`,[{userId:users[0].id,nickname:'A',active:true,whiteCards:[],blackCards:[]},{userId:users[1].id,nickname:'B',active:true,whiteCards:[],blackCards:[]}],{number:1,blackCard:'nativa',hostId:String(users[0].id),submissions:new Map([[String(users[1].id),{card:`${suffix} temp`}]]),winnerId:String(users[1].id),winnerCard:`${suffix} temp`});await p.recordResolvedRound(tempRoom);assert.equal((await sql`SELECT COUNT(*)::int n FROM card_personal_progress_events WHERE user_id=${users[1].id} AND canonical_card_id=${temp.id}`)[0].n,0);

   const black=await makeCard('black',`${suffix} black`,[users[0].id,users[1].id],[users[0].id]);const blackRoom=mkRoom(`${suffix}_black`,[{userId:users[0].id,nickname:'A',active:true,whiteCards:[],blackCards:[`${suffix} black`]},{userId:users[1].id,nickname:'B',active:true,whiteCards:[],blackCards:[`${suffix} black`]}],{number:1,blackCard:`${suffix} black`,hostId:String(users[0].id),submissions:new Map(),winnerId:null,winnerCard:null});await p.recordResolvedRound(blackRoom);const bp=(await sql`SELECT * FROM user_card_progress WHERE user_id=${users[0].id} AND canonical_card_id=${black.id}`)[0],bp2=(await sql`SELECT * FROM user_card_progress WHERE user_id=${users[1].id} AND canonical_card_id=${black.id}`)[0];assert.equal(Number(bp.black_personal_uses),1);assert.equal(Number(bp.external_presence_matches),0);assert.equal(Number(bp2.external_presence_matches),1);
  }finally{for(const u of users)await sql`DELETE FROM users WHERE id=${u.id}`;for(const id of cards)await sql`DELETE FROM canonical_cards WHERE id=${id}`;}
 });
}
