'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),defs=require(path.join(root,'lib','achievementDefinitions')),src=fs.readFileSync(path.join(root,'lib','missionService.js'),'utf8'),migration=fs.readFileSync(path.join(root,'db','metagame_v1_4_package10.sql'),'utf8');
test('missões legadas continuam presentes e novas missões usam a mesma fonte user_missions',()=>{for(const k of['d-play','d-rounds','d-react'])assert.ok(defs.DAILY.some(x=>x.key===k));for(const k of['w-play','w-win','w-rounds','w-borrowed','w-react'])assert.ok(defs.WEEKLY.some(x=>x.key===k));assert.match(src,/INSERT INTO user_missions/);assert.doesNotMatch(migration,/CREATE TABLE IF NOT EXISTS .*mission/i);});
test('toda missão paga 20 por cento do XP em moedas',()=>{for(const m of[...defs.DAILY,...defs.WEEKLY])assert.equal(Math.round(m.xp*.20),Math.round(m.xp*0.20));assert.match(src,/Math\.round\(d\.xp\*\.20\)/);assert.match(src,/rate:\.20/);});
test('apenas a missão semanal de variedade sorteia um Buff',()=>{const rewarded=[...defs.DAILY,...defs.WEEKLY].filter(x=>x.randomBuff);assert.deepEqual(rewarded.map(x=>x.key),['w-buff-variety']);});
test('pool de Buff gratuito é pequeno e exclui premium',()=>{assert.deepEqual(defs.BUFF_REWARD_POOL,['buff_dedo_no_olho','buff_foi_sem_querer','buff_amigo_de_merda','buff_vou_fingir']);assert.ok(!defs.BUFF_REWARD_POOL.includes('buff_saqueador'));assert.match(src,/price<=400/);});
test('sorteio é determinístico e recompensa de Buff é idempotente',()=>{assert.match(src,/createHash\('sha256'\)/);assert.match(src,/mission:\$\{periodType\}:\$\{periodKey\}:\$\{missionKey\}:buff:\$\{userId\}/);assert.match(src,/ON CONFLICT\(idempotency_key\) DO NOTHING/);assert.match(migration,/mission_reward/);});
test('frame semanal legado não fica mais difícil com as novas missões',()=>{assert.match(src,/LEGACY_WEEKLY_KEYS/);assert.match(src,/legacyWeekly\.every/);});
