'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),roomConfig=require('../lib/roomConfigP7');
const reward=read('public/js/rewardPreviewUI.js'),createRoom=read('public/js/screens/createRoom.js'),lobby=read('public/js/screens/lobby.js'),rules=read('public/js/roomRulesUI.js'),narrator=read('public/js/narrator.js'),roomDomain=read('public/js/domains/roomUI.js'),shop=read('public/js/marketplaceShop.js'),cosmetics=read('public/js/domains/cosmeticsUI.js'),p14=read('public/css/p14.css'),rulesCss=read('public/css/roomRulesCardBaseCurrent.css'),baseFrames=read('public/css/cosmeticFramesBaseCurrent.css'),p17=read('public/css/animatedCosmeticFramesBaseCurrent.css'),p33=read('public/css/cosmeticSpecialFramesCurrent.css'),p36=read('public/css/cosmeticWingsCurrent.css'),p16=read('public/css/buffCardPresentationCurrent.css'),socket=read('public/js/socket.js'),api=read('api/rooms/config.js'),store=read('lib/roomStore.js'),migration=read('db/p14_narrator_frames.sql'),index=read('public/index.html'),doc=read('docs/P14_NARRADOR_LOJA_RECOMPENSAS_SALA.md');
for(const[file,src]of[['rewardPreviewUI.js',reward],['createRoom.js',createRoom],['lobby.js',lobby],['roomRulesUI.js',rules],['narrator.js',narrator],['roomUI.js',roomDomain],['marketplaceShop.js',shop],['cosmeticsUI.js',cosmetics]])test(`${file} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('reward preview atual mantém Espólio explícito por colocação sem aproximação',()=>{assert.doesNotMatch(reward,/~\$\{/);assert.match(reward,/economy-placement-grid/);assert.match(reward,/economy-reward-loot/);for(const label of["'1º lugar'","'2º lugar'","'3º lugar'","'Demais'"])assert.ok(reward.includes(label),label);});

test('criação de sala atual mantém regras, resumo, estimativa e Como Jogar separados',()=>{for(const marker of['how-to-play-card','dashboard-estimate-card','create-room-dashboard','dashboard-config-card','dashboard-summary-slot'])assert.match(createRoom,new RegExp(marker));assert.doesNotMatch(createRoom,/create-room-sidebar/);assert.match(roomDomain,/normalizeCreate/);});

test('Lobby mantém regras editáveis antes do início através de resumo e modal',()=>{assert.match(lobby,/RoomRulesUI\.summary\(cfg/);assert.match(lobby,/RoomRulesUI\.openEditor/);assert.match(lobby,/SocketClient\.updateRoomConfig/);assert.match(lobby,/App\.state\.isCreator/);assert.match(rules,/Narrador da partida/);assert.match(rules,/data-room-input/);assert.match(rulesCss,/room-rules-card/);assert.match(rulesCss,/room-rules-fields/);});

test('servidor preserva autoridade do criador e inclui Narrador',()=>{const state=[...roomConfig.PRE_START][0],room={creatorId:'7',state,players:new Map([['7',{active:true}]]),maxPlayers:6,pointsToWin:10,handSize:5,useStandardDeck:true,cardCreationEnabled:true,playerCardsEnabled:true,afkEnabled:true,buffsEnabled:false,narratorEnabled:false,rewardConfigSnapshot:null};roomConfig.apply(room,'7',{narratorEnabled:true,pointsToWin:12});assert.equal(room.narratorEnabled,true);assert.equal(room.pointsToWin,12);assert.throws(()=>roomConfig.apply(room,'8',{narratorEnabled:false}),/Apenas o criador/);assert.equal(roomConfig.publicConfig(room).narratorEnabled,true);});

test('Narrador persiste, transmite e sincroniza por owner roomUI atual',()=>{assert.match(store,/narrator_enabled/);assert.match(migration,/ADD COLUMN IF NOT EXISTS narrator_enabled/);assert.match(api,/room_config_updated/);assert.match(api,/broadcast/);assert.match(socket,/room_config_updated/);assert.match(roomDomain,/registerConfigEvents/);assert.match(roomDomain,/room_config_updated/);assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/roomP14Sync\.js"/);});

test('Narrador lê somente eventos públicos e roda no dispositivo do criador',()=>{assert.match(narrator,/App\?\.state\?\.isCreator/);for(const event of['game_started','new_round','all_cards_played','round_result','game_over'])assert.ok(narrator.includes(`'${event}'`),event);assert.doesNotMatch(narrator,/App\.state\.hand|_fetchHand|handState/);assert.match(narrator,/speechSynthesis/);assert.match(narrator,/pt-BR/);});

test('cards de BUFF usam renderer atual e apresentação visual P16',()=>{assert.match(shop,/market-buff-header/);assert.match(shop,/buff-type-pill/);assert.match(shop,/cosmetic-rarity rarity-/);assert.doesNotMatch(shop,/buff-rarity-pill/);assert.match(shop,/market-buff-presentation/);assert.match(p16,/market-buff-main/);assert.doesNotMatch(p14,/market-buff-product/);});

test('P14 introduziu dez molduras compráveis e o catálogo atual é ordenado por rarity',()=>{const keys=['cosmetic_frame_lisa','cosmetic_frame_dupla','cosmetic_frame_pontilhada','cosmetic_frame_neon_roxa','cosmetic_frame_faisca','cosmetic_frame_ornamental','cosmetic_frame_cintilante','cosmetic_frame_arco_iris','cosmetic_frame_folhas','cosmetic_frame_asas'];for(const key of keys)assert.ok(migration.includes(`'${key}'`),key);assert.equal((migration.match(/\('cosmetic_frame_/g)||[]).length,10);assert.match(cosmetics,/RARITY_ORDER/);assert.match(cosmetics,/sortByRarity/);});

test('molduras-base de P14 sobrevivem; Cintilante/Arco-íris/Asas seguem owners posteriores',()=>{for(const key of['lisa','dupla','pontilhada','neon-roxa','faisca','ornamental','folhas'])assert.ok(baseFrames.includes(`frame-cosmetic-${key}`),key);assert.doesNotMatch(baseFrames,/frame-cosmetic-cintilante|frame-cosmetic-arco-iris|frame-cosmetic-asas/);assert.match(p17,/frame-cosmetic-arco-iris/);assert.match(p33,/frame-cosmetic-cintilante/);assert.match(p36,/frame-cosmetic-asas/);assert.doesNotMatch(baseFrames,/frame-bronze|frame-silver|frame-gold|frame-platinum/);});

test('P14 preserva shim histórico fora do runtime e carrega owners diretos na posição da cascata',()=>{assert.match(p14,/roomRulesCardBaseCurrent\.css/);assert.match(p14,/cosmeticFramesBaseCurrent\.css/);assert.equal(index.indexOf('css/p14.css'),-1);const rulesPos=index.indexOf('css/roomRulesCardBaseCurrent.css'),framesPos=index.indexOf('css/cosmeticFramesBaseCurrent.css'),next=index.indexOf('css/roomSummaryCurrent.css');assert.ok(rulesPos>0&&framesPos>rulesPos&&next>framesPos);assert.match(doc,/Não depender de patches de DOM por seletor frágil/);assert.match(doc,/Narrador/);assert.match(doc,/Espólio/);assert.match(doc,/Regras da mesa/);});
