'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const roomConfig=require(path.join(root,'lib','roomConfigP7'));
const reward=read('public/js/rewardPreviewUI.js'),createRoom=read('public/js/screens/createRoom.js'),lobby=read('public/js/screens/lobby.js'),rules=read('public/js/roomRulesUI.js'),narrator=read('public/js/narrator.js'),sync=read('public/js/roomP14Sync.js'),shop=read('public/js/marketplaceShop.js'),cosmeticUI=read('public/js/cosmeticUI.js'),css=read('public/css/p14.css'),socket=read('public/js/socket.js'),api=read('api/rooms/config.js'),store=read('lib/roomStore.js'),migration=read('db/p14_narrator_frames.sql'),index=read('public/index.html'),doc=read('docs/P14_NARRADOR_LOJA_RECOMPENSAS_SALA.md');

for(const[file,src]of[['rewardPreviewUI.js',reward],['createRoom.js',createRoom],['lobby.js',lobby],['roomRulesUI.js',rules],['narrator.js',narrator],['roomP14Sync.js',sync],['marketplaceShop.js',shop]])test(`${file} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('reward preview fonte não usa til e mantém Espólio explícito por colocação',()=>{assert.doesNotMatch(reward,/~\$\{/);assert.match(reward,/economy-placement-grid/);assert.match(reward,/economy-reward-loot/);assert.match(reward,/'1º lugar'/);assert.match(reward,/'2º lugar'/);assert.match(reward,/'3º lugar'/);assert.match(reward,/'Demais'/);});

test('Como Jogar e estimativas permanecem blocos próprios na criação de sala',()=>{const rulesAt=createRoom.indexOf('how-to-play-card'),rewardAt=createRoom.indexOf('dashboard-estimate-card');assert.ok(rulesAt>0&&rewardAt>0&&rulesAt!==rewardAt);assert.match(createRoom,/create-room-dashboard/);assert.match(createRoom,/dashboard-config-card/);assert.match(createRoom,/dashboard-summary-slot/);assert.doesNotMatch(createRoom,/create-room-sidebar/);});

test('Lobby mantém regras editáveis antes do início através do resumo e modal',()=>{assert.match(lobby,/RoomRulesUI\.summary\(cfg/);assert.match(lobby,/RoomRulesUI\.openEditor/);assert.match(lobby,/SocketClient\.updateRoomConfig/);assert.match(lobby,/App\.state\.isCreator/);assert.doesNotMatch(lobby,/save-room-rules-btn/);assert.match(rules,/Narrador da partida/);assert.match(rules,/data-room-input/);});

test('servidor preserva autoridade do criador e inclui Narrador',()=>{const state=[...roomConfig.PRE_START][0],room={creatorId:'7',state,players:new Map([['7',{active:true}]]),maxPlayers:6,pointsToWin:10,handSize:5,useStandardDeck:true,cardCreationEnabled:true,playerCardsEnabled:true,afkEnabled:true,buffsEnabled:false,narratorEnabled:false,rewardConfigSnapshot:null};roomConfig.apply(room,'7',{narratorEnabled:true,pointsToWin:12});assert.equal(room.narratorEnabled,true);assert.equal(room.pointsToWin,12);assert.throws(()=>roomConfig.apply(room,'8',{narratorEnabled:false}),/Apenas o criador/);assert.equal(roomConfig.publicConfig(room).narratorEnabled,true);});

test('Narrador persiste, transmite e sincroniza para todos no Lobby',()=>{assert.match(store,/narrator_enabled/);assert.match(migration,/ADD COLUMN IF NOT EXISTS narrator_enabled/);assert.match(api,/room_config_updated/);assert.match(api,/broadcast/);assert.match(socket,/room_config_updated/);assert.match(socket,/return this\._post\('\/api\/rooms\/config'/);assert.match(sync,/LobbyScreen/);});

test('Narrador lê somente eventos públicos e roda apenas no dispositivo do criador',()=>{assert.match(narrator,/App\?\.state\?\.isCreator/);for(const event of['game_started','new_round','all_cards_played','round_result','game_over'])assert.ok(narrator.includes(`'${event}'`),event);assert.doesNotMatch(narrator,/App\.state\.hand|_fetchHand|handState/);assert.match(narrator,/speechSynthesis/);assert.match(narrator,/pt-BR/);});

test('cards de BUFF mantêm categoria, raridade autoritativa e layout com ícone',()=>{assert.match(shop,/market-buff-header/);assert.match(shop,/buff-type-pill/);assert.match(shop,/cosmetic-rarity rarity-/);assert.doesNotMatch(shop,/buff-rarity-pill/);assert.match(shop,/CartBuffPresentation/);assert.match(shop,/market-buff-presentation/);assert.match(css,/market-buff-header\{display:flex;align-items:center;justify-content:space-between/);});

test('P14 adiciona 10 molduras compráveis com escala de raridade e preço',()=>{const expected=[['cosmetic_frame_lisa',4000,'common'],['cosmetic_frame_dupla',5000,'common'],['cosmetic_frame_pontilhada',6000,'common'],['cosmetic_frame_neon_roxa',8000,'rare'],['cosmetic_frame_faisca',9000,'rare'],['cosmetic_frame_ornamental',10000,'rare'],['cosmetic_frame_cintilante',65000,'epic'],['cosmetic_frame_arco_iris',110000,'legendary'],['cosmetic_frame_folhas',125000,'legendary'],['cosmetic_frame_asas',135000,'legendary']];for(const[key,price,rarity]of expected){assert.ok(migration.includes(`'${key}'`),key);assert.ok(migration.includes(`,${price},`),`${key}:${price}`);assert.ok(migration.includes(`\\"rarity\\":\\"${rarity}\\"`)||migration.includes(`\"rarity\":\"${rarity}\"`),`${key}:${rarity}`);}assert.equal((migration.match(/\('cosmetic_frame_/g)||[]).length,10);assert.match(cosmeticUI,/common:'Comum'/);});

test('as 10 novas molduras têm render visual próprio sem tocar progressão',()=>{for(const key of['lisa','dupla','pontilhada','neon-roxa','faisca','ornamental','cintilante','arco-iris','folhas','asas'])assert.ok(css.includes(`frame-cosmetic-${key}`),key);assert.doesNotMatch(css,/frame-bronze|frame-silver|frame-gold|frame-platinum/);});

test('assets P14 continuam carregados na ordem necessária',()=>{const rulesAt=index.indexOf('js/roomRulesUI.js'),createAt=index.indexOf('js/screens/createRoom.js'),narratorAt=index.indexOf('js/narrator.js'),appAt=index.indexOf('js/app.js'),syncAt=index.indexOf('js/roomP14Sync.js'),cssAt=index.indexOf('css/p14.css');assert.ok(cssAt>0);assert.ok(rulesAt>0&&rulesAt<createAt);assert.ok(narratorAt>0&&narratorAt<appAt);assert.ok(syncAt>appAt);});

test('documento P14 descreve implementação fonte e não monkey-patch',()=>{assert.match(doc,/Não depender de patches de DOM por seletor frágil/);assert.match(doc,/Narrador/);assert.match(doc,/Espólio/);assert.match(doc,/Regras da mesa/);});
