'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const readiness=require('../lib/roomReadiness'),{CONFIG}=require('../lib/balanceConfig'),{GAME_STATES}=require('../lib/constants');
const lobby=read('public/js/screens/lobby.js'),cards=read('public/js/screens/cardCreation.js'),selection=read('lib/cardSelection.js'),readyApi=read('api/rooms/ready.js'),submitApi=read('api/cards/submit.js'),startApi=read('api/game/start.js'),recycling=read('lib/cardRecycling.js'),recyclingApi=read('api/recycling.js'),recyclingUI=read('public/js/marketplaceRecycling.js'),market=read('public/js/marketplaceUI.js'),ledger=read('public/js/marketplaceLedger.js'),shop=read('public/js/marketplaceShop.js'),css=read('public/css/p16.css'),migration=read('db/p16_recycling.sql'),index=read('public/index.html');

for(const[file,src]of[['lobby.js',lobby],['cardCreation.js',cards],['marketplaceRecycling.js',recyclingUI],['marketplaceUI.js',market],['marketplaceShop.js',shop]])test(`${file} compila no P16`,()=>assert.doesNotThrow(()=>new Function(src)));

test('Pronto é estado explícito e reversível para todos, inclusive Host',()=>{const players=new Map([['1',{active:true,cardsReady:false}],['2',{active:true,cardsReady:false}],['3',{active:true,cardsReady:false}]]),room={state:GAME_STATES.CADASTRO_CARTAS,players};assert.equal(readiness.sync(room).allReady,false);readiness.setReady(room,'1',true);readiness.setReady(room,'2',true);const final=readiness.setReady(room,'3',true);assert.equal(final.allReady,true);assert.equal(room.state,GAME_STATES.PRONTA_PARA_INICIAR);readiness.setReady(room,'1',false);assert.equal(room.state,GAME_STATES.CADASTRO_CARTAS);players.get('3').active=false;assert.equal(readiness.sync(room).state,GAME_STATES.AGUARDANDO_JOGADORES);});

test('Lobby mantém menu de Cartas de Jogador aberto a reedição e separa botão Pronto',()=>{assert.match(lobby,/id="register-cards-btn"/);assert.match(lobby,/id="ready-toggle-btn"/);assert.match(lobby,/✅ Pronto/);assert.match(lobby,/setReady\(ready\)/);assert.match(lobby,/\/api\/rooms\/ready/);assert.doesNotMatch(lobby,/Cartas de Jogador concluídas/);assert.doesNotMatch(lobby,/!cardFeatures&&!ready/);assert.match(lobby,/players\.every\(p=>p\.cardsReady\)/);});

test('editor de Cartas de Jogador salva ao sair sem confirmação e pode ser reaberto',()=>{assert.match(cards,/\/api\/cards\/submit\?code=/);assert.match(cards,/saveAndReturn/);assert.match(cards,/Salvar e voltar ao Lobby/);assert.match(cards,/o botão Pronto fica separado/);assert.doesNotMatch(cards,/Sem Cartas de Jogador\?/);assert.doesNotMatch(cards,/Deseja concluir assim/);assert.doesNotMatch(cards,/submit-cards-btn/);assert.match(selection,/if\(changed\)player\.cardsReady=false/);assert.match(submitApi,/req\.method==='GET'/);});

test('início da partida exige todos explicitamente Prontos',()=>{assert.match(readyApi,/readiness\.setReady/);assert.match(readyApi,/player_list_update/);assert.match(startApi,/readiness\.sync\(room\)/);assert.match(startApi,/todos os jogadores estiverem Prontos/);});

test('Reciclagem usa taxa conservadora de 10 cartas por 250 moedas',()=>{assert.equal(CONFIG.recycling.batchSize,10);assert.equal(CONFIG.recycling.rewardPerBatch,250);assert.equal(CONFIG.recycling.rewardPerBatch/CONFIG.recycling.batchSize,25);assert.match(recycling,/CONFIG\.recycling\.batchSize/);assert.match(recycling,/CONFIG\.recycling\.rewardPerBatch/);});

test('Reciclagem remove somente ownership e preserva carta canônica/autoria',()=>{assert.match(recycling,/DELETE FROM canonical_card_ownerships/);assert.match(recycling,/UPDATE user_cards uc SET owned=false/);assert.doesNotMatch(recycling,/DELETE FROM canonical_cards/);assert.doesNotMatch(recycling,/DELETE FROM canonical_card_authors/);assert.match(recycling,/card_recycling_batches/);assert.match(migration,/card_recycling/);assert.match(migration,/card_count%10=0/);assert.match(recyclingApi,/recycling\.recycle/);});

test('Mercado Paralelo expõe aba Reciclagem com lote, projeção e confirmação destrutiva',()=>{assert.match(market,/data-market-tab="recycling"/);assert.match(market,/MarketRecycling\.render/);assert.match(recyclingUI,/10|batchSize/);assert.match(recyclingUI,/Reciclar Cartas de Jogador\?/);assert.match(recyclingUI,/múltiplo exato/);assert.match(ledger,/card_recycling:'Reciclagem de cartas'/);const script=index.indexOf('js/marketplaceRecycling.js'),ui=index.indexOf('js/marketplaceUI.js');assert.ok(script>0&&script<ui);});

test('BUFF coloca título e descrição logo abaixo das pills e ao lado do ícone',()=>{assert.match(shop,/market-buff-main market-buff-presentation/);assert.match(shop,/market-buff-copy/);assert.match(css,/grid-template-columns:minmax\(0,1fr\) 48px/);assert.match(css,/market-buff-copy h4\{display:block!important;min-height:0!important;margin:0!important;padding:0!important/);assert.match(css,/market-buff-copy p\{margin:6px 0 0!important/);});

test('P16 é carregado depois de P15 para vencer hacks visuais antigos',()=>{const p15=index.indexOf('css/p15.css'),p16=index.indexOf('css/p16.css');assert.ok(p15>0&&p16>p15);});
