'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const readiness=require('../lib/roomReadiness'),{CONFIG}=require('../lib/balanceConfig'),{GAME_STATES}=require('../lib/constants');
const lobby=read('public/js/screens/lobby.js'),cards=read('public/js/screens/cardCreation.js'),selection=read('lib/cardSelection.js'),readyApi=read('api/rooms/ready.js'),submitApi=read('api/cards/submit.js'),startApi=read('api/game/start.js'),recycling=read('lib/cardRecycling.js'),recyclingApi=read('api/recycling.js'),recyclingUI=read('public/js/marketplaceRecycling.js'),marketDomain=read('public/js/domains/marketplaceUI.js'),market=read('public/js/marketplaceUI.js'),ledger=read('public/js/marketplaceLedger.js'),shop=read('public/js/marketplaceShop.js'),p16=read('public/css/p16.css'),readyCss=read('public/css/lobbyReadinessCurrent.css'),recyclingCss=read('public/css/recyclingBaseCurrent.css'),buffCss=read('public/css/buffCardPresentationCurrent.css'),migration=read('db/p16_recycling.sql'),migrationP41=read('db/p41_recycling_any_count.sql'),index=read('public/index.html');
for(const[file,src]of[['lobby.js',lobby],['cardCreation.js',cards],['marketplaceRecycling.js',recyclingUI],['marketplaceUI.js',market],['marketplaceShop.js',shop],['marketplaceDomain',marketDomain]])test(`${file} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('Pronto é estado explícito e reversível para todos, inclusive Host',()=>{const players=new Map([['1',{active:true,cardsReady:false}],['2',{active:true,cardsReady:false}],['3',{active:true,cardsReady:false}]]),room={state:GAME_STATES.CADASTRO_CARTAS,players};assert.equal(readiness.sync(room).allReady,false);readiness.setReady(room,'1',true);readiness.setReady(room,'2',true);assert.equal(readiness.setReady(room,'3',true).allReady,true);assert.equal(room.state,GAME_STATES.PRONTA_PARA_INICIAR);readiness.setReady(room,'1',false);assert.equal(room.state,GAME_STATES.CADASTRO_CARTAS);players.get('3').active=false;assert.equal(readiness.sync(room).state,GAME_STATES.AGUARDANDO_JOGADORES);});

test('Lobby separa edição de cartas e Pronto e owner visual mantém estados',()=>{assert.match(lobby,/id="register-cards-btn"/);assert.match(lobby,/id="ready-toggle-btn"/);assert.match(lobby,/✅ Pronto/);assert.match(lobby,/setReady\(ready\)/);assert.match(lobby,/\/api\/rooms\/ready/);assert.match(lobby,/players\.every\(p=>p\.cardsReady\)/);assert.match(readyCss,/lobby-ready-btn/);assert.match(readyCss,/is-ready/);});

test('editor salva ao sair e congela somente enquanto Pronto',()=>{assert.match(cards,/\/api\/cards\/submit\?code=/);assert.match(cards,/saveAndReturn/);assert.match(cards,/Salvar e voltar ao Lobby/);assert.match(cards,/readyLocked/);assert.match(cards,/Desmarque Pronto/);assert.doesNotMatch(cards,/submit-cards-btn/);assert.match(selection,/player\.cardsReady===true/);assert.match(submitApi,/req\.method==='GET'/);});

test('início da partida exige todos Prontos e payload permanece compacto',()=>{assert.match(readyApi,/readiness\.setReady/);assert.match(readyApi,/cards_submitted/);assert.match(readyApi,/playerStatuses/);assert.doesNotMatch(readyApi,/player_list_update/);assert.match(startApi,/readiness\.sync\(room\)/);assert.match(startApi,/todos os jogadores estiverem Prontos/);});

test('Reciclagem atual usa taxa fixa de 25 moedas por carta e preserva autoria/canônico',()=>{assert.equal(CONFIG.recycling.rewardPerCard,25);assert.match(recycling,/CONFIG\.recycling\.rewardPerCard/);assert.match(recycling,/ids\.length\*p\.rewardPerCard/);assert.match(recycling,/DELETE FROM canonical_card_ownerships/);assert.match(recycling,/UPDATE user_cards uc SET owned=false/);assert.doesNotMatch(recycling,/DELETE FROM canonical_cards/);assert.doesNotMatch(recycling,/DELETE FROM canonical_card_authors/);assert.match(migration,/card_recycling/);assert.match(migrationP41,/CHECK\(card_count>=1\)/);assert.match(recyclingApi,/recycling\.recycle/);});

test('owner marketplace atual controla projeção e confirmação visual da Reciclagem',()=>{assert.match(market,/data-market-tab="recycling"/);assert.match(market,/MarketRecycling\.render/);assert.match(marketDomain,/installRecycling/);assert.match(marketDomain,/rewardPerCard/);assert.match(marketDomain,/p41-recycle-confirm-overlay/);assert.match(marketDomain,/Cancelar/);assert.match(marketDomain,/Reciclar por/);assert.match(ledger,/card_recycling:'Reciclagem de cartas'/);assert.match(recyclingCss,/recycling-hero/);assert.match(recyclingCss,/recycling-toolbar/);});

test('BUFF mantém título/descrição ao lado do ícone',()=>{assert.match(shop,/market-buff-main market-buff-presentation/);assert.match(shop,/market-buff-copy/);assert.match(buffCss,/grid-template-columns:minmax\(0,1fr\) 48px/);assert.match(buffCss,/market-buff-copy h4/);assert.match(buffCss,/market-buff-copy p/);});

test('P16 é shim de três owners e P41 histórico não executa',()=>{for(const name of['lobbyReadinessCurrent.css','recyclingBaseCurrent.css','buffCardPresentationCurrent.css'])assert.match(p16,new RegExp(name.replace('.','\\.')));assert.ok(index.indexOf('css/p16.css')>index.indexOf('css/p15.css'));assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/p41\.js/);assert.match(index,/js\/domains\/marketplaceUI\.js/);});
