'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const migration=read('db/p17_frame_rarity_rebalance.sql'),p17=read('public/css/p17.css'),progress=read('public/css/progressionFramesCurrent.css'),animated=read('public/css/animatedCosmeticFramesBaseCurrent.css'),p33=read('public/css/cosmeticSpecialFramesCurrent.css'),ui=read('public/js/domains/cosmeticsUI.js'),profile=read('public/js/domains/profileUI.js'),metagame=read('api/profile/metagame.js'),index=read('public/index.html');

test('cosmeticsUI canônico compila',()=>assert.doesNotThrow(()=>new Function(ui)));

test('P17 reorganiza as 17 molduras com raridade e preço explícitos',()=>{const expected=[['cosmetic_frame_lisa','common',4000,300],['cosmetic_frame_dupla','common',5000,310],['cosmetic_frame_pontilhada','common',6000,320],['cosmetic_frame_fita_isolante','rare',15000,330],['cosmetic_frame_agiota','rare',17500,340],['cosmetic_frame_buraco_negro','rare',20000,350],['cosmetic_frame_ouro_de_pobre','superrare',30000,360],['cosmetic_frame_glitch_radioativo','superrare',35000,370],['cosmetic_frame_neon_roxa','superrare',40000,380],['cosmetic_frame_neon_duvidoso','superrare',45000,390],['cosmetic_frame_ornamental','epic',65000,400],['cosmetic_frame_folhas','epic',75000,410],['cosmetic_frame_asas','epic',85000,420],['cosmetic_frame_cintilante','legendary',110000,430],['cosmetic_frame_arco_iris','legendary',130000,440],['cosmetic_frame_faisca','legendary',150000,450],['cosmetic_frame_lavagem_completa','celestial',250000,460]];for(const[key,rarity,price,sort]of expected)assert.match(migration,new RegExp(`\\('${key}','[^']+','${rarity}',${price},${sort}\\)`),key);assert.equal((migration.match(/\('cosmetic_frame_/g)||[]).length,17);});

test('raridade cosmética segue Comum → Celestial e é separada da progressão de moldura',()=>{assert.match(ui,/RARITY_ORDER=Object\.freeze\(\{common:1,rare:2,superrare:3,epic:4,legendary:5,celestial:6\}\)/);assert.match(ui,/\.sort\(sortByRarity\)/);assert.match(ui,/Bronze, Prata, Ouro e Platina/);assert.match(progress,/Bronze → Prata → Ouro → Platina/);});

test('progressão, cosmético e especial compartilham um único slot de moldura',()=>{assert.match(ui,/compartilham o mesmo slot de aparência/);assert.match(ui,/uma única<\/strong> para exibir/);assert.match(profile,/data\.previewFrame=key/);assert.match(profile,/setAppearanceDraft\(pm,'frame',key\)/);assert.match(profile,/pm\.data\.equipped\.frameKey/);assert.match(profile,/frameClasses\(node\)\.forEach\(c=>node\.classList\.remove\(c\)\)/);assert.match(profile,/if\(frameKey\)node\.classList\.add\(`frame-\$\{frameKey\}`\)/);assert.match(metagame,/equipped:\{titleKey:fresh\.equipped_title_key\|\|null,frameKey:fresh\.equipped_frame_key\|\|null\}/);assert.match(metagame,/const frames=\[\.\.\.state\.frames/);});

test('molduras de progressão continuam selecionáveis depois do desbloqueio',()=>{for(const tier of['bronze','silver','gold','platinum'])assert.match(profile,new RegExp(`${tier}:'[^']+'`));assert.match(profile,/Depois de desbloqueada, esta moldura pode ser equipada livremente no Perfil/);assert.match(metagame,/Depois de desbloqueada, esta moldura pode ser equipada livremente no Perfil/);});

test('Bronze, Prata, Ouro e Platina mantêm aura e faísca por owner próprio',()=>{for(const tier of['bronze','silver','gold','platinum']){assert.match(progress,new RegExp(`frame-${tier}`));assert.match(progress,new RegExp(`frame-${tier}::after`));}for(const marker of['p17ProgressAura','p17ProgressSpark','#ffc27a','#f7fbff','#fff1a3','#dffcff'])assert.ok(progress.includes(marker),marker);});

test('base P17 mantém órbita de Cintilante/Arco-íris/Lavagem e P33 é o override final da foto Cintilante',()=>{assert.match(animated,/frame-cosmetic-cintilante::before/);assert.match(animated,/frame-cosmetic-arco-iris::before/);assert.match(animated,/frame-cosmetic-lavagem-completa::before/);assert.match(animated,/frame-cosmetic-arco-iris>img[^}]*filter:none!important/);assert.match(animated,/frame-cosmetic-lavagem-completa>img[^}]*filter:none!important/);assert.match(p33,/frame-cosmetic-cintilante img/);assert.match(p33,/hue-rotate\(var\(--p33-cintilante-hue\)\)/);assert.ok(index.indexOf('css/p33.css')>index.indexOf('css/animatedCosmeticFramesBaseCurrent.css'));});

test('Lavagem Completa preserva paleta Celestial da moldura',()=>{for(const marker of['frame-cosmetic-lavagem-completa','p17CelestialGlow','p17CelestialSpark','p17FrameOrbit','#a5f3fc','#93c5fd','#c4b5fd'])assert.ok(animated.includes(marker),marker);});

test('P17 preserva shim histórico fora do runtime e owners diretos na posição histórica',()=>{assert.match(p17,/progressionFramesCurrent\.css/);assert.match(p17,/animatedCosmeticFramesBaseCurrent\.css/);assert.equal(index.indexOf('css/p17.css'),-1);const base=index.indexOf('css/buffCardPresentationCurrent.css'),progressPos=index.indexOf('css/progressionFramesCurrent.css'),animatedPos=index.indexOf('css/animatedCosmeticFramesBaseCurrent.css'),next=index.indexOf('css/contributionCurrent.css');assert.ok(base>=0&&progressPos>base&&animatedPos>progressPos&&next>animatedPos);assert.match(index,/js\/domains\/cosmeticsUI\.js/);assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/cosmeticUI\.js"/);});
