'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const contribution=require('../lib/playerContribution'),cardIdentity=require('../lib/cardIdentity'),defs=require('../lib/prestigeDefinitions'),{GAME_STATES}=require('../lib/constants'),readiness=require('../lib/roomReadiness');
const lobby=read('public/js/screens/lobby.js'),cards=read('public/js/screens/cardCreation.js'),rules=read('public/js/roomRulesUI.js'),readyApi=read('api/rooms/ready.js'),loot=read('lib/matchLoot.js'),shop=read('public/js/marketplaceShop.js'),notifyLib=read('lib/appNotifications.js'),notifyBase=read('public/js/notificationsUI.js'),notifyDomain=read('public/js/domains/notificationsUI.js'),notifyApi=read('api/notifications.js'),audio=read('public/js/domains/audioUI.js'),p18=read('public/css/p18.css'),contributionCss=read('public/css/contributionCurrent.css'),libraryCss=read('public/css/cardCreationLibraryBaseCurrent.css'),buffCss=read('public/css/buffRarityCurrent.css'),notificationsCss=read('public/css/notificationsBaseCurrent.css'),p21=read('public/css/roomSetupDashboardCurrent.css'),genesis=read('public/css/genesisFrameBaseCurrent.css'),index=read('public/index.html'),migration=read('db/p18_creator_entitlements.sql'),prestige=read('lib/prestigeService.js'),createApi=read('api/cards/create.js'),cleanCards=read('lib/cleanCards.js'),cardComponent=read('public/js/components/card.js');
for(const[name,src]of[['lobby',lobby],['cardCreation',cards],['roomRules',rules],['marketplaceShop',shop],['notificationsUI',notifyBase],['notificationsDomain',notifyDomain],['audioUI',audio],['cardComponent',cardComponent]])test(`${name} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('contribuição mínima é uma carta e zero exige confirmação somente quando criação está ativa',()=>{const room={state:GAME_STATES.CADASTRO_CARTAS,cardCreationEnabled:true,playerCardsEnabled:true,players:new Map([['1',{active:true,blackCards:[],whiteCards:[],cardsReady:false}],['2',{active:true,blackCards:['A ______?'],whiteCards:[],cardsReady:false}]])};assert.equal(contribution.count(room.players.get('1')),0);assert.equal(contribution.status(room,room.players.get('1')).requiresConfirmation,true);assert.equal(contribution.count(room.players.get('2')),1);readiness.setReady(room,'2',true);assert.equal(room.players.get('2').lootEligible,true);const noCreation={...room,cardCreationEnabled:false,players:new Map([['1',{active:true,blackCards:[],whiteCards:[],cardsReady:false}]])};assert.equal(contribution.status(noCreation,noCreation.players.get('1')).requiresConfirmation,false);assert.equal(contribution.status(noCreation,noCreation.players.get('1')).lootEligible,true);assert.match(contributionCss,/lobby-contribution-note/);assert.match(contributionCss,/is-miser/);});
test('Pronto sem contribuição pede confirmação e broadcast segue compacto',()=>{assert.match(readyApi,/confirmationRequired:true/);assert.match(readyApi,/NO_CONTRIBUTION_LOOT_WARNING/);assert.match(readyApi,/acceptNoContribution/);assert.match(readyApi,/playerStatuses/);assert.doesNotMatch(readyApi,/ok\(res,\{[^}]*players,/s);assert.match(lobby,/Mão de Vaca/);assert.match(lobby,/Ficar Pronto sem Espólio/);});
test('ao ficar Pronto a edição congela e quem não contribui recebe quota zero',()=>{assert.match(lobby,/cardButton\.disabled=myReady/);assert.match(cards,/readyLocked/);assert.match(createApi,/player\.cardsReady===true/);assert.match(loot,/enforceContributionEligibility/);assert.match(loot,/eligible_count=0,quota=0,status='empty'/);assert.match(loot,/contribution\.finalEligibility/);});
test('raridade de BUFF permanece textual, sem pill própria',()=>{assert.match(shop,/cosmetic-rarity rarity-/);assert.doesNotMatch(shop,/buff-rarity-pill/);assert.match(buffCss,/market-buff-header \.cosmetic-rarity/);});
test('configuração mantém output acessível e visual final pertence a P21',()=>{assert.match(rules,/<output class="config-value"/);assert.match(rules,/aria-live="polite"/);assert.doesNotMatch(rules,/>Editável</);assert.match(p21,/\.room-rules-card \.config-value/);assert.doesNotMatch(p18,/\.room-rules-card\s+\.config-value/);});
test('seleção de cartas usa renderer real e grid-base próprio',()=>{assert.match(cards,/CardComponent\.createBlackCard/);assert.match(cards,/CardComponent\.createWhiteCard/);assert.match(cards,/player-card-library-card/);assert.doesNotMatch(cards,/profile-card tier-/);assert.match(libraryCss,/player-card-library-grid/);assert.match(libraryCss,/created-cards-grid/);});
test('Carta Preta nova exige 1 a 2 lacunas e normaliza underscore',()=>{assert.throws(()=>cardIdentity.normalizeBlackCardDisplay('Qual é a resposta?'),/lacuna/i);assert.equal(cardIdentity.normalizeBlackCardDisplay('Qual é _?'),'Qual é ______?');assert.equal(cardIdentity.normalizeBlackCardDisplay('___ ou ____________________'),'______ ou ______');assert.throws(()=>cardIdentity.normalizeBlackCardDisplay('_ + _ + _'),/no máximo 2 lacunas/i);assert.equal(cardIdentity.whiteCardsRequiredForBlack('A ______ ou ______'),2);assert.match(cleanCards,/normalizeBlackCardDisplay\(text,\{requireGap:true\}\)/);assert.match(cardComponent,/replace\(\/_\+\/g/);});
test('Central publica versão, updates e recompensas e owner atual adiciona spoilers sem substituir base',()=>{const version=notifyLib.match(/const APP_VERSION='v(\d+)\.(\d+)\.(\d+)'/);assert.ok(version);assert.match(notifyLib,/Prêmio de boas-vindas/);assert.match(notifyApi,/notifications\.center/);assert.match(notifyBase,/Central de Notificações/);assert.match(notifyDomain,/CartDomains\.claim\('notificationsUI'/);assert.match(notifyDomain,/notifications-spoiler/);assert.match(notificationsCss,/notifications-overlay/);assert.match(notificationsCss,/notifications-shell/);assert.match(index,/js\/domains\/notificationsUI\.js/);});
test('música é owner audioUI e retoma em gestos permitidos',()=>{assert.match(audio,/music-autostart-p18:v1/);assert.match(audio,/setSettings\(\{music:true\}\)/);assert.match(audio,/pointerdown/);assert.match(audio,/CartSoundtrack/);assert.match(audio,/CartDomains\.claim\('audioUI'/);});
test('título O Criador e Gênese seguem entitlement fora do catálogo e visual Gênese pertence a P26+',()=>{assert.equal(defs.SPECIAL_TITLES['o-criador'].name,'O Criador');assert.equal(defs.SPECIAL_TITLES['o-criador'].rarity,'celestial');assert.equal(defs.SPECIAL_FRAMES['genese-celestial'].rarity,'celestial');assert.match(prestige,/SPECIAL_FRAMES/);assert.match(migration,/'o-criador'/);assert.match(migration,/'genese-celestial'/);assert.match(genesis,/frame-genese-celestial/);assert.doesNotMatch(p18,/frame-genese-celestial/);});
test('P18 preserva shim histórico fora do runtime e quatro owners diretos na posição histórica',()=>{for(const name of['contributionCurrent.css','cardCreationLibraryBaseCurrent.css','buffRarityCurrent.css','notificationsBaseCurrent.css'])assert.match(p18,new RegExp(name.replace('.','\\.')));assert.equal(index.indexOf('css/p18.css'),-1);const base=index.indexOf('css/animatedCosmeticFramesBaseCurrent.css'),contributionPos=index.indexOf('css/contributionCurrent.css'),libraryPos=index.indexOf('css/cardCreationLibraryBaseCurrent.css'),buffPos=index.indexOf('css/buffRarityCurrent.css'),notificationsPos=index.indexOf('css/notificationsBaseCurrent.css'),next=index.indexOf('css/doubleAnswerCurrent.css');assert.ok(base>=0&&contributionPos>base&&libraryPos>contributionPos&&buffPos>libraryPos&&notificationsPos>buffPos&&next>notificationsPos);});
