'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const advanced=require('../lib/advancedRoundEngine'),cardIdentity=require('../lib/cardIdentity'),{GAME_STATES}=require('../lib/constants'),defs=require('../lib/achievementDefinitions');
const rewardUI=read('public/js/rewardPreviewUI.js'),previewApi=read('api/rooms/preview.js'),authClient=read('public/js/auth.js'),socket=read('public/js/socket.js'),http=read('lib/http.js'),lobby=read('public/js/screens/lobby.js'),cardCreation=read('public/js/screens/cardCreation.js'),host=read('public/js/screens/host.js'),round=read('public/js/screens/round.js'),result=read('public/js/screens/result.js'),gameplay=read('public/js/domains/gameplayUI.js'),narrator=read('public/js/narrator.js'),playApi=read('api/game/play.js'),handApi=read('api/game/hand.js'),advancedBuff=read('lib/advancedBuffEngine.js'),profile=read('public/js/domains/profileUI.js'),p19=read('public/css/p19.css'),doubleCss=read('public/css/doubleAnswerCurrent.css'),stackCss=read('public/css/cleanCardStackCurrent.css'),index=read('public/index.html'),backfill=read('lib/achievementBackfill.js'),backfillCompat=read('lib/achievementBackfillP19.js'),metagameApi=read('api/profile/metagame.js'),statsApi=read('api/profile/stats.js'),pickWinner=read('api/game/pick-winner.js'),progression=read('lib/cardProgressionService.js');
for(const[name,src]of[['rewardPreviewUI',rewardUI],['authClient',authClient],['socket',socket],['lobby',lobby],['cardCreation',cardCreation],['host',host],['round',round],['result',result],['gameplayUI',gameplay],['narrator',narrator],['profileUI',profile]])test(`${name} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('APIs dinâmicas nunca dependem de 304 sem corpo',()=>{assert.match(rewardUI,/cache:'no-store'/);assert.match(rewardUI,/r\.status===304/);assert.match(previewApi,/Cache-Control/);assert.match(previewApi,/no-store/);assert.match(authClient,/cache:method==='GET'\?'no-store'/);assert.match(authClient,/res\.status===304/);assert.match(socket,/cache:'no-store'/);assert.match(socket,/r\.status===304/);assert.match(http,/function noStore\(res\)/);assert.match(http,/private, no-store, no-cache/);});

test('Mão de Vaca confirma só quando criação está ligada',()=>{const contribution=require('../lib/playerContribution'),empty={blackCards:[],whiteCards:[]};assert.equal(contribution.status({cardCreationEnabled:true},empty).requiresConfirmation,true);assert.equal(contribution.status({cardCreationEnabled:false},empty).requiresConfirmation,false);assert.equal(contribution.status({cardCreationEnabled:false},empty).lootEligible,true);assert.match(lobby,/Ficar Pronto sem Espólio/);assert.match(lobby,/Voltar e contribuir/);});

test('pilhas de Cartas Limpas pertencem à tela real e ao owner visual P21',()=>{assert.match(cardCreation,/cleanStack\(type,count\)/);assert.match(cardCreation,/clean-stack-sheet/);assert.match(cardCreation,/clean-stack-empty/);assert.match(cardCreation,/this\.cleanStacks\(\)/);assert.match(stackCss,/clean-stack-top\.is-consuming/);assert.match(stackCss,/p21CleanConsume/);assert.match(stackCss,/border:2px dashed/);assert.doesNotMatch(p19,/clean-stack-resource/);});

test('Carta Preta aceita uma ou duas lacunas e rejeita a terceira',()=>{assert.equal(cardIdentity.normalizeBlackCardDisplay('A _ B'),'A ______ B');assert.equal(cardIdentity.normalizeBlackCardDisplay('_ ou __________'),'______ ou ______');assert.throws(()=>cardIdentity.normalizeBlackCardDisplay('_ / _ / _'),/no máximo 2 lacunas/i);assert.equal(cardIdentity.whiteCardsRequiredForBlack('Uma ______'),1);assert.equal(cardIdentity.whiteCardsRequiredForBlack('Uma ______ e ______'),2);assert.match(cardCreation,/gaps>2/);});

test('round engine exige duas brancas e revela a dupla como uma resposta',()=>{const players=new Map([['1',{active:true,connected:true,score:0,hand:[]}],['2',{active:true,connected:true,score:0,hand:['A','B','C']}],['3',{active:true,connected:true,score:0,hand:['D','E','F']}]]),room={state:GAME_STATES.EM_ANDAMENTO,players,playerOrder:['1','2','3'],currentRound:null,blackDeck:[],whiteDeck:[]};advanced.startFirstRound(room,'______ com ______',0);assert.equal(advanced.cardsPerAnswer(room.currentRound),2);advanced.playCard(room,'2',0);advanced.playCard(room,'2',0);advanced.playCard(room,'3',0);assert.equal(advanced.playCard(room,'3',0).allPlayed,true);const answers=advanced.revealAnswers(room);assert.deepEqual(answers.map(a=>a.cards.length),[2,2]);const winner=advanced.pickWinner(room,'1',answers[0].answerId);assert.equal(winner.winnerCards.length,2);});

test('Meu Jogo multiplica respostas, não confunde cartas da mesma resposta',()=>{assert.match(advancedBuff,/round\.answerCount\(r,id\)>=2/);assert.match(advancedBuff,/rr\.requiredSubmissions\[id\]=2/);assert.match(advancedBuff,/requiredCards=round\.required\(r,id\)/);assert.doesNotMatch(advancedBuff,/if\(round\.forUser\(r,id\)\.length>=2\).*already_double/);});

test('UI, Narrador e resultado tratam resposta dupla como conjunto',()=>{assert.match(host,/submission-answer-group/);assert.match(host,/submission-answer-cards/);assert.match(host,/submission\.answerId/);assert.match(playApi,/advanced\.revealAnswers/);assert.match(handApi,/advanced\.revealAnswers/);assert.match(handApi,/cardsPerAnswer/);assert.match(round,/Esta Carta Preta tem 2 lacunas/);assert.match(pickWinner,/winnerCards/);assert.match(progression,/winnerTexts=Array\.isArray\(r\.winnerCards\)/);assert.match(narrator,/winnerCards/);assert.match(result,/result-winner-cards/);assert.match(result,/currentWinnerCards/);assert.match(gameplay,/CartDomains\.claim\('gameplayUI'/);assert.match(gameplay,/round_result/);assert.match(gameplay,/currentWinnerCards/);assert.match(doubleCss,/submission-answer-cards\.count-2/);assert.match(doubleCss,/result-winner-cards\.count-2/);});

test('Perfil usa draft e persiste aparência apenas pelo salvar global canônico',()=>{assert.match(profile,/setAppearanceDraft/);assert.match(profile,/syncAppearanceDom/);assert.match(profile,/profile-global-save/);assert.match(profile,/AuthClient\.saveProfile/);assert.match(profile,/titleKey,frameKey/);assert.doesNotMatch(profile,/MetaClient\.equip/);assert.doesNotMatch(p19,/profile-appearance-savebar/);});

test('badges/títulos recentes cobrem progressão Comum → Lendário',()=>{const keys=['reciclagem-primeiro-lote','mercado-primeira-compra','mercado-dez-compras','lacuna-dupla-dez','reciclagem-duzentas','mercado-cem-compras'],selected=keys.map(k=>defs.ACHIEVEMENTS.find(a=>a.key===k)),rank={common:1,rare:2,superrare:3,epic:4,legendary:5};for(const [i,key]of keys.entries())assert.ok(selected[i],`faltou ${key}`);assert.deepEqual([...new Set(selected.map(a=>rank[a.rarity]))].sort((a,b)=>a-b),[1,2,3,4,5]);assert.ok(selected.every(a=>a.title?.key));assert.match(backfill,/marketplace_purchase/);assert.match(backfill,/card_recycling/);assert.match(backfill,/double_gap_win/);assert.match(backfillCompat,/module\.exports=require\('\.\/achievementBackfill'\)/);assert.match(metagameApi,/titles\.sort\(byRarity\)/);assert.match(statsApi,/sortedTitles/);});

test('P19 é shim apenas do owner de resposta dupla e JS legado fica não executável',()=>{assert.match(p19,/doubleAnswerCurrent\.css/);assert.doesNotMatch(p19,/clean-stack-resource|profile-appearance-savebar/);assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/gameplayP19\.js"/);assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/profileAppearanceP19\.js"/);assert.match(index,/js\/domains\/gameplayUI\.js/);assert.match(index,/js\/domains\/profileUI\.js/);});
