'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const metagame=read('api/profile/metagame.js'),publicProfile=read('api/profile/public.js'),start=read('api/game/start.js'),showcaseLib=read('lib/playerShowcase.js'),identity=read('public/js/domains/identityUI.js'),showcase=read('public/js/domains/showcaseUI.js'),profile=read('public/js/domains/profileUI.js'),playerList=read('public/js/components/playerList.js'),scoreboard=read('public/js/components/scoreboard.js'),p20=read('public/css/p20.css'),identityCss=read('public/css/publicIdentityCurrent.css'),homeCss=read('public/css/homeBackdropCurrent.css'),showcaseCss=read('public/css/showcaseCurrent.css'),index=read('public/index.html'),notifications=read('lib/appNotifications.js');
for(const[file,src]of[['identityUI.js',identity],['showcaseUI.js',showcase],['profileUI.js',profile]])test(`${file} compila`,()=>assert.doesNotThrow(()=>new Function(src)));

test('Gênese é garantida por entitlement no Perfil e perfil público',()=>{assert.match(metagame,/genese-celestial/);assert.match(metagame,/special_entitlements/);assert.match(publicProfile,/genese-celestial/);assert.match(publicProfile,/special_entitlements/);});

test('Perfil oferece preview real e salva título/moldura pelo owner canônico',()=>{assert.match(profile,/profile-appearance-live-preview/);assert.match(profile,/data-profile-draft-title/);assert.match(profile,/data-profile-draft-frame/);assert.match(profile,/PRÉVIA PÚBLICA/);assert.match(profile,/AuthClient\.saveProfile/);assert.match(profile,/titleKey,frameKey/);});

test('identidade pública pertence a identityUI e aparece na Home, Lobby e placar',()=>{assert.match(identity,/CartDomains\.claim\('identityUI'/);assert.match(identity,/equipped_frame_key/);assert.match(identity,/equipped_title_key/);assert.match(identity,/account-equipped-title/);assert.match(identity,/public-avatar-frame/);assert.match(identity,/player_list_update/);for(const src of[playerList,scoreboard]){assert.match(src,/frameKey/);assert.match(src,/titleKey/);assert.match(src,/public-avatar-frame/);assert.match(src,/IdentityUI/);}assert.match(identityCss,/\.avatar-frame\.public-avatar-frame/);assert.match(identityCss,/\.profile-appearance-live-preview/);});

test('Home mantém o fundo de cartas visível em desktop e mobile por owner próprio',()=>{assert.match(homeCss,/#mode-selection\.home-form/);assert.match(homeCss,/background:rgba\(9,8,16,\.18\)!important/);assert.match(homeCss,/@media\(max-width:720px\)/);assert.match(homeCss,/background:rgba\(8,8,14,\.07\)!important/);});

test('game_started transporta showcase sem repetir avatar base64 no payload',()=>{assert.match(start,/playerShowcase\.build\(room\)/);assert.match(start,/showcase/);assert.doesNotMatch(showcaseLib,/avatarData:p\.avatarData/);assert.match(showcase,/App\.state\.players/);assert.match(showcase,/avatarData:known\.avatarData/);});

test('showcase prioriza autoria famosa e depois maior progressão',()=>{assert.match(showcaseLib,/famous_authored/);assert.match(showcaseLib,/is_authored/);assert.match(showcaseLib,/highest_progression/);assert.match(showcaseLib,/platinum:4/);assert.match(showcaseLib,/gold:3/);assert.match(showcaseLib,/silver:2/);assert.match(showcaseLib,/copper:1/);});

test('showcase atual segura a primeira rodada só no cliente, narra e aborta com segurança',()=>{assert.match(showcase,/CartDomains\.claim\('showcaseUI'/);assert.match(showcase,/playerShowcaseActive/);assert.match(showcase,/name==='round'\|\|name==='host'/);assert.match(showcase,/pending=\{name,data\}/);assert.match(showcase,/CartNarrator\.speak/);assert.match(showcase,/Conheça os suspeitos/);assert.match(showcase,/room_cancelled/);assert.match(showcase,/room_closed/);assert.match(showcaseCss,/\.player-showcase-screen/);assert.match(showcaseCss,/\.player-showcase-card\.is-speaking/);});

test('P20 é shim de owners e implementações JS históricas não são executáveis',()=>{assert.match(p20,/publicIdentityCurrent\.css/);assert.match(p20,/homeBackdropCurrent\.css/);assert.match(p20,/showcaseCurrent\.css/);for(const file of['identityP20.js','profileAppearanceP20.js','playerShowcaseP20.js'])assert.match(index,new RegExp(`<script type="application/x-cartaralho-legacy" src="js/${file.replace('.','\\.')}"`));assert.match(index,/js\/domains\/identityUI\.js/);assert.match(index,/js\/domains\/profileUI\.js/);assert.match(index,/js\/domains\/showcaseUI\.js/);});

test('Central de Notificações preserva a linhagem P20',()=>{assert.match(notifications,/release:p20/);assert.match(notifications,/version:'v1\.4\.20'/);});
