'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ui=read('public/js/uiP25.js'),p27=read('public/js/homeMenuP27.js'),index=read('public/index.html'),cards=read('public/js/screens/cardCreation.js'),createApi=read('api/cards/create.js'),notifications=read('lib/appNotifications.js');
test('P25 UI compila e permanece rastreável após HomeMenuP24 sem executar no runtime',()=>{assert.doesNotThrow(()=>new Function(ui));assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/homeMenuP24\.js"/);assert.match(index,/type="application\/x-cartaralho-legacy" src="js\/uiP25\.js"/);assert.ok(index.indexOf('js/uiP25.js')>index.indexOf('js/homeMenuP24.js'));assert.doesNotMatch(index,/<script\s+src="js\/uiP25\.js/);});
test('ordem visual histórica da Home P25 permanece rastreável sem reativar o writer',()=>{const expected=['#marketplace-menu-btn','#friends-menu-btn','[data-panel="cards"]','[data-panel="rank"]','#notifications-menu-btn','[data-panel="history"]','[data-panel="stats"]','#audio-settings-menu-btn','[data-panel="credits"]'];let previous=-1;for(const selector of expected){const at=ui.indexOf(`'${selector}'`);assert.ok(at>previous,`${selector} fora de ordem`);previous=at;}assert.match(ui,/style\.setProperty\('order',String\(index\+1\),'important'\)/);assert.doesNotMatch(ui,/new MutationObserver/);assert.match(p27,/new MutationObserver/);assert.match(ui,/pageshow/);assert.match(ui,/visibilitychange/);assert.match(ui,/'#friends-menu-btn':'Amigos de Merda'/);assert.match(ui,/'\[data-panel="stats"\]':'Estatística'/);});
test('editor mantém apenas o botão inferior de salvar quando está editável',()=>{assert.match(ui,/removeRedundantCardEditorSave/);assert.match(ui,/screen\.querySelector\('#save-cards-btn'\)/);assert.match(ui,/screen\.querySelector\('#back-btn'\)/);assert.match(ui,/salvar\\s\+e\\s\+voltar\\s\+ao\\s\+lobby/i);assert.match(ui,/top\.remove\(\)/);assert.match(cards,/id="save-cards-btn"/);assert.match(cards,/saveAndReturn/);assert.match(cards,/if\(this\.readyLocked\).*← Voltar ao Lobby/s);});
test('decisão de produto preserva criação imediata de cartas como no modelo anterior',()=>{assert.match(cards,/AuthClient\.createPaidCard\(/);assert.match(cards,/if\(d\.inventory\)this\.cleanInventory=/);assert.match(createApi,/if\(!libraryMode\)\{/);assert.match(createApi,/matchId=room\.code/);assert.match(createApi,/result=await cleanCards\.create\(\{userId:user\.id,type:cardType,text:display,matchId,creatorName,creationId\}\)/);assert.doesNotMatch(createApi,/draft|reservation|reserve/i);});
test('Central preserva P25 e P24 mesmo quando a versão continua avançando',()=>{const version=notifications.match(/APP_VERSION='v1\.4\.(\d+)'/);assert.ok(version&&Number(version[1])>=25);assert.match(notifications,/release:p25/);assert.match(notifications,/release:p24/);});
