'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const css=read('public/css/p37.css'),history=read('public/js/p37.js'),adminUI=read('public/js/domains/adminUI.js'),server=read('lib/creatorAdmin.js'),compat=read('lib/creatorAdminP37.js'),api=read('api/admin/creator-tools.js'),pusher=read('lib/pusherServer.js'),version=read('api/version.js'),notifications=read('api/notifications.js'),release=read('lib/releaseP37.js'),index=read('public/index.html');

test('owners atuais de admin compilam e P37 permanece legível como proveniência',()=>{assert.doesNotThrow(()=>new Function(history));assert.doesNotThrow(()=>new Function(adminUI));assert.doesNotThrow(()=>new Function(server));assert.doesNotThrow(()=>new Function(api));assert.doesNotThrow(()=>new Function(pusher));});
test('megafone global e aviso de versão vivem no owner adminUI',()=>{assert.match(pusher,/GLOBAL_CHANNEL='cartaralho-global'/);assert.match(adminUI,/subscribe\(GLOBAL_CHANNEL\)/);assert.match(adminUI,/bind\('admin_megaphone'/);assert.match(adminUI,/Nova atualização \$\{current\} disponível/);assert.match(adminUI,/setInterval\(checkVersion,60000\)/);assert.match(version,/currentVersion:APP_VERSION/);});
test('ferramentas do Criador permanecem exclusivas do user_id 1 em cliente e servidor',()=>{assert.match(adminUI,/Number\(AuthClient\?\.user\?\.id\)===1/);assert.match(server,/CREATOR_ADMIN_USER_ID=1/);assert.ok(server.includes('Number(user.id)!==CREATOR_ADMIN_USER_ID'));assert.match(api,/requireCreatorAdmin/);assert.match(css,/#home-admin-btn\{display:none!important\}/);});
test('admin oferece Megafone e Prêmios individual/coletivo',()=>{for(const marker of["action==='megaphone'","action==='reward'","scope==='individual'",'creditIndividual','creditAll','broadcastGlobal'])assert.ok(api.includes(marker),marker);for(const label of['📣 Megafone','🎁 Prêmios','Individual','Coletivo','Premiar jogador','Premiar todos'])assert.ok(adminUI.includes(label),label);assert.match(api,/targetUserIds/);});
test('créditos administrativos continuam transacionais e idempotentes no owner canônico',()=>{assert.match(server,/sql\.transaction/);assert.match(server,/idempotency_key/);assert.match(server,/ON CONFLICT\(idempotency_key\) DO NOTHING/);assert.ok(server.includes("'adjustment'"));assert.match(server,/admin:\$\{operationId\}:\$\{id\}/);assert.match(server,/isolationMode:'Serializable'/);});
test('P37 backend é apenas alias compatível e API usa o owner sem sufixo',()=>{assert.match(compat,/module\.exports=require\('\.\/creatorAdmin'\)/);assert.match(api,/require\('\.\.\/\.\.\/lib\/creatorAdmin'\)/);assert.doesNotMatch(api,/creatorAdminP37/);});
test('Central e endpoint de versão preservam P37 mesmo após releases futuros',()=>{assert.match(release,/APP_VERSION='v1\.4\.37'/);assert.match(notifications,/P37_RELEASE|releaseP37/);assert.match(version,/APP_VERSION/);});
test('P37 frontend é histórico não executável enquanto CSS compatível permanece',()=>{assert.match(index,/css\/p37\.css\?v=1\.4\.37/);assert.match(index,/<script type="application\/x-cartaralho-legacy" src="js\/p37\.js\?v=1\.4\.37"><\/script>/);assert.doesNotMatch(index,/<script src="js\/p37\.js/);assert.match(index,/js\/domains\/adminUI\.js\?v=domain-2/);});
