'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const cards=read('public/js/domains/cardsLibrary.js'),market=read('public/js/domains/marketplaceUI.js'),profile=read('public/js/domains/profileUI.js'),genesis=read('public/js/domains/genesisFrameUI.js'),css=read('public/css/p58.css'),card=read('public/js/components/card.js'),index=read('public/index.html'),release=read('lib/releaseP58.js'),version=read('api/version.js'),notifications=read('api/notifications.js');

test('owners canônicos preservam a trajetória P58 e o script histórico não executa',()=>{assert.doesNotThrow(()=>new Function(cards));assert.doesNotThrow(()=>new Function(market));assert.doesNotThrow(()=>new Function(profile));assert.doesNotThrow(()=>new Function(genesis));assert.match(index,/<script src="js\/domains\/cardsLibrary\.js\?v=domain-2"><\/script>/);assert.match(index,/<script src="js\/domains\/marketplaceUI\.js\?v=domain-2"><\/script>/);assert.match(index,/<script src="js\/domains\/profileUI\.js\?v=domain-2"><\/script>/);assert.match(index,/<script type="application\/x-cartaralho-legacy" src="js\/p58\.js\?v=1\.4\.58"><\/script>/);});
test('lacuna canônica é underline textual ___ rosa/roxo e não barra contínua',()=>{assert.match(card,/black-card-gap[^>]*>___<\/span>/);assert.match(cards,/black-card-gap[^>]*>___<\/span>/);assert.match(css,/\.black-card-gap[\s\S]*color:#d946ef!important/);assert.match(css,/border-bottom:0!important/);});
test('Minhas Cartas mantém proporção e renderer visual definidos pela trajetória',()=>{assert.match(cards,/p57-library-game-card/);assert.match(cards,/p56-card-art p57-detail-game-card/);assert.match(css,/\.p57-library-game-card[\s\S]*aspect-ratio:5\/7!important/);assert.match(css,/\.p57-library-game-card \.card-progression-badge[\s\S]*display:none!important/);});
test('Reciclagem preserva favorito e formatação canônica',()=>{assert.match(market,/p58-recycle-favorite/);assert.match(market,/CardComponent\._formatBlackText\(c\.text\)/);assert.match(market,/p41-recycle-card-preview/);});
test('criador de Minhas Cartas reutiliza linguagem visual do criador da partida',()=>{assert.match(cards,/p58-library-creator card-creation-screen/);assert.match(cards,/card-type-tabs/);assert.match(cards,/clean-stack-grid/);assert.match(cards,/creation-input-row/);assert.match(cards,/async function openCreator/);});
test('Gênese no Perfil preserva a órbita estável',()=>{assert.match(profile,/classList\.add\('p57-live-frame-grid','p58-live-frame-grid'\)/);assert.match(profile,/frame\.classList\.add\('p58-genesis-preview'\)/);assert.match(genesis,/STAR_COUNT=6/);assert.match(css,/p58GenesisPreviewOrbit/);});
test('P58 permanece como proveniência publicada e P75 é a release corrente',()=>{assert.match(release,/APP_VERSION='v1\.4\.58'/);assert.match(version,/releaseP75/);assert.match(notifications,/releaseP75/);assert.match(notifications,/P58_RELEASE/);assert.match(notifications,/P57_RELEASE/);});
