-- Cartaralho v1.4 — Pacote 4: Progressão Dupla, Legado e Carta Original.
-- Aditivo/idempotente. Preserva contadores legados e não paga milestones.
CREATE TABLE IF NOT EXISTS user_card_progress(user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,canonical_card_id BIGINT NOT NULL REFERENCES canonical_cards(id) ON DELETE CASCADE,white_personal_wins INT NOT NULL DEFAULT 0 CHECK(white_personal_wins>=0),black_personal_uses INT NOT NULL DEFAULT 0 CHECK(black_personal_uses>=0),external_presence_matches INT NOT NULL DEFAULT 0 CHECK(external_presence_matches>=0),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(user_id,canonical_card_id));
CREATE INDEX IF NOT EXISTS idx_user_card_progress_card ON user_card_progress(canonical_card_id);
CREATE TABLE IF NOT EXISTS card_personal_progress_events(user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,canonical_card_id BIGINT NOT NULL REFERENCES canonical_cards(id) ON DELETE CASCADE,match_id TEXT NOT NULL,round_number INT NOT NULL,metric TEXT NOT NULL CHECK(metric IN('white_personal_win','black_personal_use')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(user_id,canonical_card_id,match_id,round_number,metric));
CREATE TABLE IF NOT EXISTS card_external_presence_events(user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,canonical_card_id BIGINT NOT NULL REFERENCES canonical_cards(id) ON DELETE CASCADE,match_id TEXT NOT NULL,first_round_number INT,source_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(user_id,canonical_card_id,match_id));
CREATE INDEX IF NOT EXISTS idx_card_external_presence_card ON card_external_presence_events(canonical_card_id,match_id);
CREATE TABLE IF NOT EXISTS canonical_card_round_events(id BIGSERIAL PRIMARY KEY,canonical_card_id BIGINT NOT NULL REFERENCES canonical_cards(id) ON DELETE CASCADE,match_id TEXT NOT NULL,round_number INT NOT NULL,event_type TEXT NOT NULL CHECK(event_type IN('white_revealed','white_win','black_used')),source_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS idx_canonical_card_round_event_unique ON canonical_card_round_events(canonical_card_id,match_id,round_number,event_type,COALESCE(source_user_id,0));
CREATE TABLE IF NOT EXISTS canonical_card_match_presence(canonical_card_id BIGINT NOT NULL REFERENCES canonical_cards(id) ON DELETE CASCADE,match_id TEXT NOT NULL,first_round_number INT,first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(canonical_card_id,match_id));
CREATE TABLE IF NOT EXISTS canonical_card_stats(canonical_card_id BIGINT PRIMARY KEY REFERENCES canonical_cards(id) ON DELETE CASCADE,reach_count INT NOT NULL DEFAULT 0 CHECK(reach_count>=0),adoption_count INT NOT NULL DEFAULT 0 CHECK(adoption_count>=0),creative_coincidence_count INT NOT NULL DEFAULT 0 CHECK(creative_coincidence_count>=0),presence_count INT NOT NULL DEFAULT 0 CHECK(presence_count>=0),total_uses INT NOT NULL DEFAULT 0 CHECK(total_uses>=0),global_wins INT NOT NULL DEFAULT 0 CHECK(global_wins>=0),legacy_score NUMERIC(12,4) NOT NULL DEFAULT 0,legacy_level TEXT NOT NULL DEFAULT 'nascente' CHECK(legacy_level IN('nascente','espalhando','viral','classico','folclore')),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO user_card_progress(user_id,canonical_card_id) SELECT user_id,canonical_card_id FROM canonical_card_ownerships ON CONFLICT(user_id,canonical_card_id) DO NOTHING;
INSERT INTO canonical_card_stats(canonical_card_id,reach_count,adoption_count,creative_coincidence_count) SELECT cc.id,COUNT(DISTINCT o.user_id)::int,COUNT(DISTINCT o.user_id) FILTER(WHERE o.acquisition_source='match_loot')::int,COUNT(DISTINCT ce.user_id) FILTER(WHERE ce.creation_kind='independent')::int FROM canonical_cards cc LEFT JOIN canonical_card_ownerships o ON o.canonical_card_id=cc.id LEFT JOIN canonical_card_creation_events ce ON ce.canonical_card_id=cc.id GROUP BY cc.id ON CONFLICT(canonical_card_id) DO NOTHING;
