-- Baralho nativo original migrado de server/data/deck.json para a aplicação web/Neon.
INSERT INTO deck_cards(type,text,count,is_native,is_hidden) VALUES
('blackCards','O que não pode faltar no meu porão? ___',1,true,false),
('blackCards','Descobriram que a causa da minha depressão é ___',1,true,false),
('blackCards','Fui expulso do grupo da família no zap por postar fotos de ___',1,true,false),
('blackCards','Minha maior fantasia sexual envolve ___ e muito lubrificante.',1,true,false),
('blackCards','Qual é o segredo para um relacionamento duradouro? ___',1,true,false),
('blackCards','O novo sabor de camisinha que vai revolucionar o mercado é ___',1,true,false),
('blackCards','O que me faz questionar todas as minhas escolhas de vida? ___',1,true,false),
('blackCards','Qual será a próxima grande polêmica do BBB? ___',1,true,false),
('blackCards','Em vez de carvão, papai noel me deu ___',1,true,false),
('blackCards','O que me faz rir em velórios? ___',1,true,false),
('blackCards','Minha desculpa pra chegar atrasado no trabalho foi ___',1,true,false),
('blackCards','A pior coisa pra se dizer durante o sexo é ___',1,true,false),
('blackCards','O que tem no fim do arco-íris? ___',1,true,false),
('blackCards','Qual é o fetiche mais estranho do Neymar? ___',1,true,false),
('blackCards','O que os médicos tiraram de dentro de mim? ___',1,true,false),
('blackCards','A nova religião do Brasil adora ___',1,true,false),
('blackCards','O que me faz chorar no banho? ___',1,true,false),
('blackCards','O que arruinou meu primeiro encontro? ___',1,true,false),
('blackCards','A próxima pandemia será causada por ___',1,true,false),
('blackCards','O que me dá gatilho instantâneo? ___',1,true,false),
('whiteCards','Travesti',1,true,false),
('whiteCards','Monobola',1,true,false),
('whiteCards','Micro testículo',1,true,false),
('whiteCards','Anão vestido de spider-man',1,true,false),
('whiteCards','Pokémon fumado',1,true,false),
('whiteCards','Lula',1,true,false),
('whiteCards','Bolsonaro',1,true,false),
('whiteCards','Uma rola de borracha de 30cm',1,true,false),
('whiteCards','Aids',1,true,false),
('whiteCards','Agostinho Carrara rebaixado',1,true,false),
('whiteCards','Meu pau de óculos',1,true,false),
('whiteCards','Fisting',1,true,false),
('whiteCards','Um vibrador que parece uma serra elétrica',1,true,false),
('whiteCards','Necrofilia',1,true,false),
('whiteCards','Uma criança chorando no avião',1,true,false),
('whiteCards','Nazismo',1,true,false),
('whiteCards','Ficar duro num abraço de família',1,true,false),
('whiteCards','Incesto',1,true,false),
('whiteCards','Cheirar pó na bunda de uma GP',1,true,false),
('whiteCards','Minha mãe',1,true,false),
('whiteCards','Uma suruba no asilo',1,true,false),
('whiteCards','Gozar na calça',1,true,false),
('whiteCards','Depressão profunda',1,true,false),
('whiteCards','Suicídio',1,true,false),
('whiteCards','Bater na mãe',1,true,false),
('whiteCards','Calvície precoce',1,true,false),
('whiteCards','Gemidão do zap na hora da missa',1,true,false),
('whiteCards','Broxar',1,true,false),
('whiteCards','Cagar nas calças no primeiro encontro',1,true,false),
('whiteCards','Uma DST inexplicável',1,true,false),
('whiteCards','Adolf Hitler',1,true,false),
('whiteCards','Celso Portiolli e o 11 de setembro',1,true,false),
('whiteCards','Pedofilia',1,true,false),
('whiteCards','Um feto abortado',1,true,false),
('whiteCards','Golden shower',1,true,false),
('whiteCards','Traficantes do Comando Vermelho',1,true,false),
('whiteCards','Um agiota cobrando dívida',1,true,false),
('whiteCards','Dar o cu pra salvar o planeta',1,true,false),
('whiteCards','Fimose gigante',1,true,false),
('whiteCards','Zoofilia',1,true,false),
('whiteCards','Cheiro de virilha suada',1,true,false),
('whiteCards','A grávida de Taubaté',1,true,false),
('whiteCards','Um mendigo cagando na rua',1,true,false),
('whiteCards','Edir Macedo',1,true,false),
('whiteCards','O cu do Felipe Neto',1,true,false),
('whiteCards','Vender pack do pé',1,true,false),
('whiteCards','Crack',1,true,false),
('whiteCards','Chupar um mendigo por 5 reais',1,true,false),
('whiteCards','Ser corno manso',1,true,false),
('whiteCards','Um pinto torto',1,true,false)
ON CONFLICT(type,text) DO UPDATE SET is_native=true,is_hidden=false;

INSERT INTO user_cards(user_id,type,text,owned,is_player_card)
SELECT u.id,d.type,d.text,true,false
FROM users u CROSS JOIN deck_cards d
WHERE d.is_native=true AND d.is_hidden=false
ON CONFLICT(user_id,type,text) DO UPDATE SET owned=true,updated_at=now();
