'use strict';
const{withErrors,ok,requireMethod}=require('../lib/http');
const{requireUser}=require('../lib/auth');
const notifications=require('../lib/appNotifications');
const{APP_VERSION,RELEASE}=require('../lib/releaseP68');
const{RELEASE:P67_RELEASE}=require('../lib/releaseP67');
const{RELEASE:P66_RELEASE}=require('../lib/releaseP66');
const{RELEASE:P65_RELEASE}=require('../lib/releaseP65');
const{RELEASE:P64_RELEASE}=require('../lib/releaseP64');
const{RELEASE:P63_RELEASE}=require('../lib/releaseP63');
const{RELEASE:P62_RELEASE}=require('../lib/releaseP62');
const{RELEASE:P61_RELEASE}=require('../lib/releaseP61');
const{RELEASE:P60_RELEASE}=require('../lib/releaseP60');
const{RELEASE:P59_RELEASE}=require('../lib/releaseP59');
const{RELEASE:P58_RELEASE}=require('../lib/releaseP58');
const{RELEASE:P57_RELEASE}=require('../lib/releaseP57');
const{RELEASE:P56_RELEASE}=require('../lib/releaseP56');
const{RELEASE:P55_RELEASE}=require('../lib/releaseP55');
const{RELEASE:P54_RELEASE}=require('../lib/releaseP54');
const{RELEASE:P53_RELEASE}=require('../lib/releaseP53');
const{RELEASE:P52_RELEASE}=require('../lib/releaseP52');
const{RELEASE:P51_RELEASE}=require('../lib/releaseP51');
const{RELEASE:P50_RELEASE}=require('../lib/releaseP50');
const{RELEASE:P49_RELEASE}=require('../lib/releaseP49');
const{RELEASE:P48_RELEASE}=require('../lib/releaseP48');
const{RELEASE:P47_RELEASE}=require('../lib/releaseP47');
const{RELEASE:P46_RELEASE}=require('../lib/releaseP46');
const{RELEASE:P45_RELEASE}=require('../lib/releaseP45');
const{RELEASE:P44_RELEASE}=require('../lib/releaseP44');
const{RELEASE:P43_RELEASE}=require('../lib/releaseP43');
const{RELEASE:P42_RELEASE}=require('../lib/releaseP42');
const{RELEASE:P41_RELEASE}=require('../lib/releaseP41');
const{RELEASE:P40_RELEASE}=require('../lib/releaseP40');
const{RELEASE:P39_RELEASE}=require('../lib/releaseP39');
const{RELEASE:P38_RELEASE}=require('../lib/releaseP38');
const{RELEASE:P37_RELEASE}=require('../lib/releaseP37');
module.exports=withErrors(async(req,res)=>{
 if(!requireMethod(req,res,'GET'))return;
 const user=await requireUser(req,res);if(!user)return;
 const data=await notifications.center(user.id);data.currentVersion=APP_VERSION;
 const releases=[RELEASE,P67_RELEASE,P66_RELEASE,P65_RELEASE,P64_RELEASE,P63_RELEASE,P62_RELEASE,P61_RELEASE,P60_RELEASE,P59_RELEASE,P58_RELEASE,P57_RELEASE,P56_RELEASE,P55_RELEASE,P54_RELEASE,P53_RELEASE,P52_RELEASE,P51_RELEASE,P50_RELEASE,P49_RELEASE,P48_RELEASE,P47_RELEASE,P46_RELEASE,P45_RELEASE,P44_RELEASE,P43_RELEASE,P42_RELEASE,P41_RELEASE,P40_RELEASE,P39_RELEASE,P38_RELEASE,P37_RELEASE];
 const blocked=new Set(releases.map(x=>x.id));data.updates=[...releases,...(data.updates||[]).filter(x=>!blocked.has(x.id))];ok(res,data);
});
