'use strict';
const{withErrors,ok,requireMethod}=require('../lib/http');
const{requireUser}=require('../lib/auth');
const notifications=require('../lib/appNotifications');
const{APP_VERSION,RELEASE}=require('../lib/releaseP47');
const{RELEASE:P46_RELEASE}=require('../lib/releaseP46');
const{RELEASE:P45_RELEASE}=require('../lib/releaseP45');
const{RELEASE:P44_RELEASE}=require('../lib/releaseP44');
const{RELEASE:P43_RELEASE}=require('../lib/releaseP43');
const{RELEASE:P42_RELEASE}=require('../lib/releaseP42');
const{RELEASE:P41_RELEASE}=require('../lib/releaseP41');
const{RELEASE:P40_RELEASE}=require('../lib/releaseP40');
const{RELEASE:P39_RELEASE}=require('../lib/releaseP39');
const{RELEASE:P38_RELEASE}=require('../lib/releaseP38');
const{RELEASE:P37_RELEASE}=require('../lib/releaseP37');
module.exports=withErrors(async(req,res)=>{
 if(!requireMethod(req,res,'GET'))return;
 const user=await requireUser(req,res);if(!user)return;
 const data=await notifications.center(user.id);
 data.currentVersion=APP_VERSION;
 const blocked=new Set([RELEASE.id,P46_RELEASE.id,P45_RELEASE.id,P44_RELEASE.id,P43_RELEASE.id,P42_RELEASE.id,P41_RELEASE.id,P40_RELEASE.id,P39_RELEASE.id,P38_RELEASE.id,P37_RELEASE.id]);
 data.updates=[RELEASE,P46_RELEASE,P45_RELEASE,P44_RELEASE,P43_RELEASE,P42_RELEASE,P41_RELEASE,P40_RELEASE,P39_RELEASE,P38_RELEASE,P37_RELEASE,...(data.updates||[]).filter(x=>!blocked.has(x.id))];
 ok(res,data);
});
